import {canonicalJson,parseRecord,recordDigest} from '../contracts/canonical.mjs';
import {newId,nextRevision} from '../contracts/identity.mjs';
import {requireThat,Dev2Error} from '../contracts/errors.mjs';
import {h2Delta,requireH2Disjoint,composeH2Entries,h2MemberTuple,h2Composition,h2ResultId,h2EffectId,h2CommitMetadata,decodeH2Tuple} from '../integration/h2-identity.mjs';

const H2_DELTA_BUDGET=2097152;
/** @param {string} status */
const terminal=status=>['succeeded','failed','cancelled'].includes(status);
/** @param {unknown} error */
const codeOf=error=>error instanceof Dev2Error?error.code:'INTEGRITY_FAILURE';
/** @param {unknown} value @returns {Record<string,any>} */
function object(value){requireThat(value!==null&&typeof value==='object'&&!Array.isArray(value),'INTEGRITY_FAILURE');return /** @type {Record<string,any>} */(value);}
/** @param {import('../contracts/ports.js').Action} action @returns {Record<string,any>} */
function href(action){const h=object(/** @type {any} */(action).h2);requireThat(h.version===1&&typeof h.memberTupleDigest==='string'&&typeof h.compositionIdentity==='string'&&typeof h.leaderActionId==='string','INTEGRITY_FAILURE','Missing H2 action reference');return h;}
/** @param {import('../contracts/ports.js').Action} action */
function ordinaryAction(action){const copy={.../** @type {any} */(action)};delete copy.h2;return /** @type {import('../contracts/ports.js').Action} */(copy);}

/** Existing Work/Action/effect specialization only. No independent queue, Work,
 * lifecycle or mutable batch owner is introduced here. */
export class H2Specialization {
 /** @param {import('./engine.mjs').DevelopmentEngine} engine @param {any} options */
 constructor(engine,options){this.engine=engine;this.ledger=engine.ledger;this.objects=options.objects??null;this.enabled=options.h2Enabled===true;this.maxMembers=options.h2MaxMembers??32;this.fault=options.h2Fault??(()=>{});requireThat(Number.isSafeInteger(this.maxMembers)&&this.maxMembers>=2,'INVALID_ARGUMENT','H2 member budget');}
 /** @returns {any} */
 auth(){const a=/** @type {any} */(this.engine.o.authorization);requireThat(typeof a.snapshot==='function'&&typeof a.assertSnapshot==='function','EXECUTION_UNAVAILABLE','H2 requires synchronous authorization fencing');return a;}
 /** @param {import('../contracts/ports.js').Principal} principal @param {readonly string[]} paths */
 authSnapshot(principal,paths){return this.auth().snapshot(principal,this.engine.binding,'integration.write',paths);}
 /** @param {any} retained @param {import('../contracts/ports.js').Principal} principal @param {readonly string[]} paths */
 assertAuth(retained,principal,paths){this.auth().assertSnapshot(retained,principal,this.engine.binding,'integration.write',paths);}
 /** @param {string} actionId @returns {any} */
 selected(actionId){return this.ledger.transact(tx=>tx.getH2Selection(actionId));}
 /** @param {import('../contracts/ports.js').Work} work @param {import('../contracts/ports.js').ValidationPort} validation @returns {Promise<any>} */
 async memberEvidence(work,validation){
  const results=this.ledger.transact(tx=>tx.all('SELECT record FROM prepared WHERE work_id=? ORDER BY result_id',work.workId).map(row=>/** @type {import('../contracts/ports.js').PreparedResult} */(/** @type {unknown} */(parseRecord(String(row.record),2097152)))));
  for(const result of results){
   if(result.repositoryId!==work.repositoryId||result.bindingEpoch!==work.bindingEpoch||result.workId!==work.workId||result.generation!==work.generation||result.baseCommitOid!==work.baseCommitOid||result.baseTreeOid!==work.baseTreeOid||result.candidateTreeOid!==work.candidate.treeOid||result.expectedHead!==work.baseCommitOid||result.resultTreeOid!==work.candidate.treeOid||result.resultTreeSha256!==work.candidate.manifestDigest||result.policyDigest!==this.engine.binding.policyDigest||canonicalJson(result.execution)!==canonicalJson(this.engine.o.policy().policy.execution))continue;
   const receipts=this.ledger.transact(tx=>tx.all('SELECT record FROM validation WHERE result_id=? ORDER BY run_id',result.resultId).map(row=>/** @type {import('../contracts/ports.js').ValidationReceipt} */(/** @type {unknown} */(parseRecord(String(row.record),2097152)))));
   for(const receipt of receipts)if(await validation.eligible(result,receipt,this.engine.binding.policyDigest,this.ledger.ownerEpoch))return {result,receipt};
  }
  return null;
 }
 /** @param {import('../contracts/ports.js').Principal} principal @param {unknown} envelope @param {any[]} outcomes */
 async selectEnvelope(principal,envelope,outcomes){
  if(!this.enabled||!this.objects)return [];
  const remote=/** @type {any} */(this.engine.o.remote);if(typeof remote.prepareCompareUpdate!=='function'||typeof remote.observeSender!=='function')return [];
  const input=object(parseRecord(canonicalJson(envelope),1048576));const raw=Array.isArray(input.items)?/** @type {any[]} */(input.items):[];
  /** @type {any[]} */const admitted=[];
  for(let index=0;index<raw.length;index++){
   let item;try{item=this.engine.inputFromValue(raw[index]);}catch{continue;}
   const outcome=outcomes[index],receipt=outcome&&outcome.ok===true?object(outcome.receipt):null;
   if(item.op!=='integrate'||item.preparedResultId||!receipt||receipt.deduplicated===true||receipt.status!=='queued')continue;
   const actionId=String(receipt.actionId);const frame=this.ledger.transact(tx=>{const action=tx.getAction(actionId),work=action?.workId?tx.getWork(action.workId):null;return action&&work?{action,work}:null;});
   if(!frame||frame.action.principal!==principal.subject||frame.action.operation!=='integrate'||frame.action.requestId!==item.requestId||frame.action.status!=='queued'||frame.work.currentActionId!==frame.action.actionId||frame.work.disposition!=='open'||frame.work.baseCommitOid!==item.expectedHead||frame.work.generation!==item.generation)continue;
   admitted.push({index,item,...frame});
  }
  /** @type {Map<string,any[]>} */const groups=new Map();
  for(const row of admitted){const key=canonicalJson({head:row.work.baseCommitOid,baseTreeOid:row.work.baseTreeOid,policyDigest:row.item.policyDigest});const list=groups.get(key)??[];list.push(row);groups.set(key,list);}
  /** @type {any[]} */const selected=[];
  for(const rows of groups.values()){
   if(rows.length<2||rows.length>this.maxMembers)continue;
   try{const value=await this.selectGroup(principal,rows);if(value){selected.push(value);for(const member of value.members){const out=outcomes[member.index];if(out?.ok&&out.receipt){const receipt=object(out.receipt);receipt.status='running';receipt.revision=member.reservedWorkRevision;}}}}
   catch(error){if(!['INVALID_ARGUMENT','STALE_REVISION','STALE_BASE','STALE_RESULT','ENTRY_CONFLICT','VALIDATION_FAILED','CAPACITY_REJECTED','FORBIDDEN','UNAUTHORIZED','LIMIT_EXCEEDED','INTEGRITY_FAILURE','EXECUTION_UNAVAILABLE'].includes(codeOf(error)))throw error;}
  }
  return selected;
 }
 /** @param {import('../contracts/ports.js').Principal} principal @param {any[]} rows @returns {Promise<any>} */
 async selectGroup(principal,rows){
  const validation=this.engine.o.validation(),policy=this.engine.o.policy();requireThat(policy.policy.digest===this.engine.binding.policyDigest,'STALE_RESULT');
  const head=String(rows[0].work.baseCommitOid),base=await this.engine.o.repository.readCommit(this.engine.binding,head);requireThat(base.source.treeOid===rows[0].work.baseTreeOid,'INTEGRITY_FAILURE');
  /** @type {any[]} */const contexts=[];
  for(const row of rows){
   requireThat(row.work.baseCommitOid===head&&row.work.baseTreeOid===base.source.treeOid&&row.item.expectedHead===head&&row.item.policyDigest===this.engine.binding.policyDigest,'STALE_BASE');
   await this.engine.authorize(principal,row.item);const candidate=await this.engine.candidate(row.work),delta=h2Delta(base.source,candidate),evidence=await this.memberEvidence(row.work,validation);requireThat(evidence,'VALIDATION_FAILED','Missing retained member validation');
   const paths=delta.changes.map(change=>change.path),authorization=this.authSnapshot(principal,paths);contexts.push({...row,candidate,delta,evidence,paths,authorization,reservedWorkRevision:nextRevision(row.work.revision)});
  }
  requireH2Disjoint(contexts.map(row=>row.delta));
  const members=contexts.map(row=>({workId:row.work.workId,actionId:row.action.actionId,principal:row.action.principal,requestId:row.action.requestId,intentDigest:row.action.intentDigest,generation:row.work.generation,reservedWorkRevision:row.reservedWorkRevision,candidateTreeOid:row.work.candidate.treeOid,candidateManifestDigest:row.work.candidate.manifestDigest,memberResultId:row.evidence.result.resultId,memberValidationId:row.evidence.receipt.validationId,memberReceiptRunId:row.evidence.receipt.runId,memberReceiptDigest:row.evidence.receipt.signature,changedPathDigest:row.delta.changedPathDigest}));
  const common={repositoryId:this.engine.binding.repositoryId,provider:this.engine.binding.provider,providerRepositoryId:this.engine.binding.providerRepositoryId,installationId:this.engine.binding.installationId,bindingEpoch:this.engine.binding.bindingEpoch,ref:this.engine.binding.ref,expectedHead:head,baseTreeOid:base.source.treeOid,baseManifestDigest:base.source.manifestDigest,policyDigest:this.engine.binding.policyDigest,execution:structuredClone(policy.policy.execution)};
  const frozen=h2MemberTuple(common,members),ordered=frozen.tuple.members.map(member=>{const row=contexts.find(value=>value.action.actionId===member.actionId);requireThat(row,'INTEGRITY_FAILURE');return /** @type {any} */(row);});
  const entries=composeH2Entries(base.source,ordered.map(row=>row.delta)),tree=await this.engine.o.repository.writeTree(entries),compositionIdentity=h2Composition(frozen.memberTupleDigest,tree),resultId=h2ResultId(compositionIdentity),metadata=h2CommitMetadata(this.engine.o.actor,ordered.map(row=>row.evidence.result));
  const tupleObjectDigest=await this.objects.put(Buffer.from(canonicalJson(frozen.tuple)));const deltaRecord={version:1,memberTupleDigest:frozen.memberTupleDigest,members:ordered.map(row=>({actionId:row.action.actionId,changedPathDigest:row.delta.changedPathDigest,changes:row.delta.changes}))},deltaBytes=Buffer.from(canonicalJson(deltaRecord));requireThat(deltaBytes.byteLength<=H2_DELTA_BUDGET,'LIMIT_EXCEEDED','H2 delta bundle budget');const deltaObjectDigest=await this.objects.put(deltaBytes);
  const leader=ordered[0],selection={version:1,memberTupleDigest:frozen.memberTupleDigest,leaderActionId:leader.action.actionId,tupleObjectDigest,deltaObjectDigest,compositionIdentity,resultId,expectedHead:head,resultTreeOid:tree.treeOid,resultTreeSha256:tree.manifestDigest,policyDigest:this.engine.binding.policyDigest,memberCount:ordered.length,metadata};
  /** @type {import('../contracts/ports.js').Attempt|null} */let attempt=null;
  this.ledger.transact(tx=>{
   requireThat(this.engine.o.policy().policy.digest===selection.policyDigest&&canonicalJson(this.engine.o.policy().policy.execution)===canonicalJson(frozen.tuple.execution),'STALE_RESULT');requireThat(tx.reservations().length<this.engine.coordinator.executionCapacity,'CAPACITY_REJECTED');
   for(const row of ordered){const work=tx.getWork(row.work.workId),action=tx.getAction(row.action.actionId);requireThat(work&&action&&canonicalJson(work)===canonicalJson(row.work)&&canonicalJson(action)===canonicalJson(row.action)&&action.status==='queued'&&work.currentActionId===action.actionId&&tx.get('SELECT value FROM meta WHERE key=?','cancel:'+action.actionId)?.value!=='true'&&action.deadline>this.engine.now(),'STALE_REVISION');this.assertAuth(row.authorization,principal,row.paths);}
   tx.putH2Selection(selection,ordered.map((row,ordinal)=>({actionId:row.action.actionId,workId:row.work.workId,ordinal,reservedWorkRevision:row.reservedWorkRevision})));
   for(const row of ordered){const work=tx.getWork(row.work.workId);requireThat(work&&tx.compareWork(work.revision,{...work,revision:row.reservedWorkRevision}),'STALE_REVISION');this.fault('selection.after-work-'+row.action.actionId);}
   const leaderAction=tx.getAction(selection.leaderActionId);requireThat(leaderAction,'INTEGRITY_FAILURE');attempt={installationId:this.engine.binding.installationId,repositoryId:this.engine.binding.repositoryId,workId:leader.work.workId,actionId:selection.leaderActionId,attemptId:newId(),attempt:nextRevision(leaderAction.attempt),ownerEpoch:this.ledger.ownerEpoch};requireThat(tx.reserveAttempt(/** @type {import('../contracts/ports.js').Attempt} */(attempt),this.engine.coordinator.executionCapacity),'CAPACITY_REJECTED');
   for(const row of ordered){const action=tx.getAction(row.action.actionId);requireThat(action,'INTEGRITY_FAILURE');const role=action.actionId===selection.leaderActionId?'leader':'follower';tx.updateAction(/** @type {any} */({...action,status:'running',step:'h2.selected.'+role,attempt:role==='leader'?/** @type {import('../contracts/ports.js').Attempt} */(attempt).attempt:action.attempt,ownerEpoch:this.ledger.ownerEpoch,h2:{version:1,memberTupleDigest:selection.memberTupleDigest,compositionIdentity:selection.compositionIdentity,leaderActionId:selection.leaderActionId,tupleObjectDigest:selection.tupleObjectDigest,deltaObjectDigest:selection.deltaObjectDigest,role,effectId:null}}));this.fault('selection.after-action-'+action.actionId);}
   tx.run('INSERT INTO meta(key,value) VALUES(?,?)','h2-prepare:'+selection.memberTupleDigest,canonicalJson({version:1,resultId:selection.resultId,metadata:selection.metadata,compositionIdentity:selection.compositionIdentity}));
  });
  requireThat(attempt,'INTEGRITY_FAILURE');const publicMembers=ordered.map(row=>({index:row.index,actionId:row.action.actionId,workId:row.work.workId,reservedWorkRevision:row.reservedWorkRevision}));this.start(selection,/** @type {import('../contracts/ports.js').Attempt} */(attempt));return {selection,attempt,members:publicMembers};
 }
 /** @param {any} selection @param {import('../contracts/ports.js').Attempt} attempt */
 start(selection,attempt){if(this.engine.running.has(selection.leaderActionId))return;this.engine.store('lastAttempt:'+selection.leaderActionId,attempt);const promise=this.execute(selection,attempt).catch(error=>{if(!this.ledger.closed)try{this.engine.store('callback-rejection:'+selection.leaderActionId,{code:codeOf(error)});}catch{}}).finally(()=>{this.engine.running.delete(selection.leaderActionId);queueMicrotask(()=>this.engine.pump());});this.engine.running.set(selection.leaderActionId,promise);}
 /** @param {any} selection @returns {Promise<any>} */
 async immutable(selection){requireThat(this.objects,'EXECUTION_UNAVAILABLE');const tuple=object(decodeH2Tuple(await this.objects.get(selection.tupleObjectDigest)));requireThat(recordDigest('dev2.h2-members.v1',tuple)===selection.memberTupleDigest&&Array.isArray(tuple.members)&&tuple.members.length===selection.memberCount,'INTEGRITY_FAILURE','H2 tuple object mismatch');const delta=object(parseRecord(await this.objects.get(selection.deltaObjectDigest),H2_DELTA_BUDGET));requireThat(delta.version===1&&delta.memberTupleDigest===selection.memberTupleDigest&&Array.isArray(delta.members)&&delta.members.length===selection.memberCount,'INTEGRITY_FAILURE','H2 delta object mismatch');return {tuple,delta};}
 /** @param {import('../storage/ledger.mjs').Transaction} tx @param {any} selection @returns {any} */
 frameIn(tx,selection){const current=tx.getH2SelectionByDigest(selection.memberTupleDigest);requireThat(current&&canonicalJson(current)===canonicalJson(selection),'STALE_REVISION','H2 selection changed');const memberRefs=tx.h2Members(selection.memberTupleDigest);requireThat(memberRefs.length===selection.memberCount,'INTEGRITY_FAILURE');const members=memberRefs.map(member=>{const action=tx.getAction(member.actionId),work=tx.getWork(member.workId);requireThat(action&&work,'INTEGRITY_FAILURE');const h=href(action);requireThat(h.memberTupleDigest===selection.memberTupleDigest&&h.compositionIdentity===selection.compositionIdentity&&h.leaderActionId===selection.leaderActionId,'INTEGRITY_FAILURE');const revision=String(tx.get('SELECT value FROM meta WHERE key=?','actionRevision:'+action.actionId)?.value??'0'),cancelled=tx.get('SELECT value FROM meta WHERE key=?','cancel:'+action.actionId)?.value==='true';return {member,action,work,revision,cancelled};});const leader=members.find(member=>member.action.actionId===selection.leaderActionId);requireThat(leader,'INTEGRITY_FAILURE');const attemptRows=tx.all('SELECT attempt_id FROM attempt WHERE action_id=? AND json_extract(record,\'$.attempt\')=?',selection.leaderActionId,leader.action.attempt);requireThat(attemptRows.length<=1,'INTEGRITY_FAILURE');const reservation=attemptRows.length?tx.retainedAttempt(String(attemptRows[0].attempt_id)):null,effect=tx.getDirectEffect(selection.leaderActionId),sender=effect?tx.get('SELECT value FROM meta WHERE key=?','sender:'+effect.effectId)?.value??null:null;return {selection,current,memberRefs,members,leader,reservation,effect,sender};}
 /** @param {any} frame */
 stamp(frame){return recordDigest('dev2.h2-recovery-frame.v1',{memberTupleDigest:frame.selection.memberTupleDigest,members:frame.members.map((member)=>({member:member.member,action:member.action,work:member.work,revision:member.revision,cancelled:member.cancelled})),reservation:frame.reservation,effect:frame.effect,sender:frame.sender});}
 /** @param {import('../storage/ledger.mjs').Transaction} tx @param {any} selection @param {'running'|'blocked'|null} [status] @returns {any} */
 assertMembers(tx,selection,status='running'){const frame=this.frameIn(tx,selection);for(const row of frame.members)requireThat(row.work.revision===row.member.reservedWorkRevision&&row.work.currentActionId===row.action.actionId&&row.work.disposition==='open'&&(!status||row.action.status===status)&&row.action.ownerEpoch===this.ledger.ownerEpoch,'STALE_REVISION');return frame;}
 /** @param {any} immutable @param {string} actionId */
 paths(immutable,actionId){const item=immutable.delta.members.find((member)=>object(member).actionId===actionId);requireThat(item,'INTEGRITY_FAILURE');const row=object(item);requireThat(Array.isArray(row.changes),'INTEGRITY_FAILURE');return /** @type {any[]} */(row.changes).map(change=>String(object(change).path));}
 /** @param {any} immutable @param {any} selection */
 principals(immutable,selection){return /** @type {any[]} */(immutable.tuple.members).map(member=>{const m=object(member),principal=this.engine.metadata('principal:'+String(m.actionId));requireThat(principal&&typeof principal==='object'&&!Array.isArray(principal),'INTEGRITY_FAILURE');return {member:m,principal:/** @type {import('../contracts/ports.js').Principal} */(/** @type {unknown} */(principal)),item:this.engine.input(String(m.actionId)),paths:this.paths(immutable,String(m.actionId))};});}
 /** @param {any} immutable @param {any} selection */
 async authorizeAll(immutable,selection){const rows=this.principals(immutable,selection);for(const row of rows)await this.engine.authorize(row.principal,row.item);return rows.map(row=>({...row,authorization:this.authSnapshot(row.principal,row.paths)}));}
 /** @param {any} selection @param {import('../contracts/ports.js').Attempt} attempt */
 async result(selection,attempt){const old=this.ledger.transact(tx=>tx.getPrepared(selection.resultId));if(old){const h=object(/** @type {any} */(old).h2);requireThat(h.version===1&&h.memberTupleDigest===selection.memberTupleDigest&&h.compositionIdentity===selection.compositionIdentity&&old.resultTreeOid===selection.resultTreeOid&&old.resultTreeSha256===selection.resultTreeSha256&&old.expectedHead===selection.expectedHead,'INTEGRITY_FAILURE');return old;}const immutable=await this.immutable(selection),base=await this.engine.o.repository.readCommit(this.engine.binding,selection.expectedHead);requireThat(base.source.treeOid===immutable.tuple.baseTreeOid&&base.source.manifestDigest===immutable.tuple.baseManifestDigest,'INTEGRITY_FAILURE');const tree=await this.engine.o.repository.readTree(selection.resultTreeOid);requireThat(tree.manifestDigest===selection.resultTreeSha256,'INTEGRITY_FAILURE');const commitOid=await this.engine.o.repository.freezeCommit(selection.expectedHead,tree,selection.metadata,selection.resultId),leaderMember=object(immutable.tuple.members[0]);const result={resultId:selection.resultId,repositoryId:this.engine.binding.repositoryId,bindingEpoch:this.engine.binding.bindingEpoch,workId:String(leaderMember.workId),generation:String(leaderMember.generation),baseCommitOid:selection.expectedHead,baseTreeOid:String(immutable.tuple.baseTreeOid),candidateTreeOid:String(leaderMember.candidateTreeOid),expectedHead:selection.expectedHead,commitOid,resultTreeOid:selection.resultTreeOid,resultTreeSha256:selection.resultTreeSha256,policyDigest:selection.policyDigest,metadata:selection.metadata,execution:structuredClone(immutable.tuple.execution),h2:{version:1,memberTupleDigest:selection.memberTupleDigest,compositionIdentity:selection.compositionIdentity,leaderActionId:selection.leaderActionId,tupleObjectDigest:selection.tupleObjectDigest,deltaObjectDigest:selection.deltaObjectDigest,memberCount:selection.memberCount}};this.ledger.transact(tx=>{const frame=this.assertMembers(tx,selection,'running');requireThat(frame.members.every(row=>!row.cancelled&&row.action.deadline>this.engine.now()),'STALE_REVISION');requireThat(!frame.effect,'INTEGRITY_FAILURE');tx.putPrepared(/** @type {any} */(result));for(const row of frame.members)tx.updateAction(/** @type {any} */({...row.action,resultId:selection.resultId,step:'h2.prepared'}));});this.fault('after-result-persist');return /** @type {import('../contracts/ports.js').PreparedResult} */(result);}
 /** @param {import('../contracts/ports.js').PreparedResult} result */
 async receipt(result){const validation=this.engine.o.validation(),retained=this.ledger.transact(tx=>tx.all('SELECT record FROM validation WHERE result_id=? ORDER BY run_id',result.resultId).map(row=>/** @type {import('../contracts/ports.js').ValidationReceipt} */(/** @type {unknown} */(parseRecord(String(row.record),2097152)))));for(const receipt of retained)if(await validation.eligible(result,receipt,this.engine.binding.policyDigest,this.ledger.ownerEpoch))return receipt;return null;}
 /** @param {any} selection @param {import('../contracts/ports.js').PreparedResult} result @param {import('../contracts/ports.js').ValidationReceipt} receipt @param {any[]} authorized */
 freezeEffect(selection,result,receipt,authorized){const value={memberTupleDigest:selection.memberTupleDigest,compositionIdentity:selection.compositionIdentity,repositoryId:this.engine.binding.repositoryId,bindingEpoch:this.engine.binding.bindingEpoch,ref:this.engine.binding.ref,expectedHead:selection.expectedHead,commitOid:result.commitOid,resultTreeOid:result.resultTreeOid,resultTreeSha256:result.resultTreeSha256,preparedResultId:result.resultId,validationId:receipt.validationId,policyDigest:selection.policyDigest},effectId=h2EffectId(value),effect={effectId,workId:result.workId,actionId:selection.leaderActionId,repositoryId:this.engine.binding.repositoryId,bindingEpoch:this.engine.binding.bindingEpoch,ref:this.engine.binding.ref,expectedHead:selection.expectedHead,commitOid:result.commitOid,preparedResultId:result.resultId,validationId:receipt.validationId,policyDigest:selection.policyDigest,h2:{version:1,memberTupleDigest:selection.memberTupleDigest,compositionIdentity:selection.compositionIdentity,tupleObjectDigest:selection.tupleObjectDigest,deltaObjectDigest:selection.deltaObjectDigest,memberCount:selection.memberCount}};return this.ledger.transact(tx=>{const frame=this.assertMembers(tx,selection,'running'),old=tx.getDirectEffect(selection.leaderActionId);if(old){requireThat(canonicalJson(old)===canonicalJson(effect),'IDEMPOTENCY_MISMATCH');return old;}requireThat(frame.members.every(row=>!row.cancelled&&row.action.deadline>this.engine.now()),'STALE_REVISION');requireThat(this.engine.o.policy().policy.digest===selection.policyDigest&&canonicalJson(this.engine.o.policy().policy.execution)===canonicalJson(result.execution),'STALE_RESULT');const stored=tx.getPrepared(result.resultId),validationRow=tx.get('SELECT record FROM validation WHERE run_id=?',receipt.runId);requireThat(stored&&canonicalJson(stored)===canonicalJson(result)&&validationRow&&canonicalJson(parseRecord(String(validationRow.record),2097152))===canonicalJson(receipt),'VALIDATION_FAILED');for(const row of authorized)this.assertAuth(row.authorization,row.principal,row.paths);for(const row of frame.members)this.fault('effect.before-member-'+row.action.actionId);tx.putEffect(/** @type {any} */(effect));for(const row of frame.members){const h=href(row.action);tx.updateAction(/** @type {any} */({...row.action,step:'publication.intent',resultId:result.resultId,h2:{...h,effectId}}));}this.fault('effect.after-attach');return /** @type {import('../contracts/ports.js').Effect} */(effect);});}
 /** @param {any} selection @param {any} effect @param {any} result @param {any} receipt @param {any[]} authorized @param {import('../storage/ledger.mjs').Transaction} tx */
 dispatchFenceIn(selection,effect,result,receipt,authorized,tx){const frame=this.assertMembers(tx,selection,null);requireThat(frame.members.every(row=>['running','blocked'].includes(row.action.status)&&!row.cancelled&&row.action.deadline>this.engine.now()),'STALE_REVISION');requireThat(frame.effect&&canonicalJson(frame.effect)===canonicalJson(effect)&&this.engine.o.policy().policy.digest===selection.policyDigest&&canonicalJson(this.engine.o.policy().policy.execution)===canonicalJson(result.execution),'STALE_RESULT');const stored=tx.getPrepared(result.resultId),vr=tx.get('SELECT record FROM validation WHERE run_id=?',receipt.runId);requireThat(stored&&canonicalJson(stored)===canonicalJson(result)&&vr&&canonicalJson(parseRecord(String(vr.record),2097152))===canonicalJson(receipt),'VALIDATION_FAILED');for(const row of authorized)this.assertAuth(row.authorization,row.principal,row.paths);}
 /** @param {any} selection @param {import('../contracts/ports.js').Attempt} attempt @param {import('../contracts/ports.js').Effect} effect @param {import('../contracts/ports.js').PreparedResult} result @param {import('../contracts/ports.js').ValidationReceipt} receipt */
 async publish(selection,attempt,effect,result,receipt){const immutable=await this.immutable(selection),principal=/** @type {import('../contracts/ports.js').Principal} */(/** @type {unknown} */(this.engine.metadata('principal:'+selection.leaderActionId))),integrator=this.engine.integrator(principal,this.engine.input(selection.leaderActionId)),sender0=await this.senderObservation(effect),pre=await integrator.reconcile(effect,sender0.stopped);if(pre.kind!=='retryable'){await this.reconcile(selection,attempt,effect,integrator);return;}const remote=/** @type {any} */(this.engine.o.remote),launch=await remote.prepareCompareUpdate(effect);requireThat(typeof launch==='function','EXECUTION_UNAVAILABLE');const authorized=await this.authorizeAll(immutable,selection);requireThat(await this.engine.o.validation().eligible(result,receipt,this.engine.binding.policyDigest,this.ledger.ownerEpoch),'VALIDATION_FAILED');await launch((/** @type {import('../storage/ledger.mjs').Transaction} */ tx)=>this.dispatchFenceIn(selection,effect,result,receipt,authorized,tx));this.fault('after-send');await this.reconcile(selection,attempt,effect,integrator);}
 /** @param {import('../contracts/ports.js').Effect} effect @returns {Promise<any>} */
 async senderObservation(effect){const remote=/** @type {any} */(this.engine.o.remote);if(typeof remote.observeSender==='function')try{return await remote.observeSender(effect);}catch{}const stopped=await this.engine.senderStopped(effect);return {stopped,delivery:'unknown',state:stopped?'stopped':'unknown'};}
 /** @param {any} selection @param {import('../contracts/ports.js').Attempt} attempt @param {import('../contracts/ports.js').Effect} effect @param {any} integrator */
 async reconcile(selection,attempt,effect,integrator){for(let tries=0;tries<4;tries++){const before=this.ledger.transact(tx=>{const frame=this.frameIn(tx,selection);return {stamp:this.stamp(frame),frame};}),sender=await this.senderObservation(effect),outcome=await integrator.reconcile(effect,sender.stopped);const applied=this.ledger.transact(tx=>{const frame=this.frameIn(tx,selection);if(this.stamp(frame)!==before.stamp)return false;if(sender.stopped&&outcome.kind==='integrated'){this.settleTerminalIn(tx,frame,'succeeded',outcome);return true;}if(sender.stopped&&outcome.kind==='stale'){this.settleTerminalIn(tx,frame,'failed',outcome);return true;}this.blockIn(tx,frame,sender.stopped,'EFFECT_UNCERTAIN',outcome.kind==='retryable'?'publication.retryable':'reconcile');return true;});if(applied)return;}this.ledger.transact(tx=>this.blockIn(tx,this.frameIn(tx,selection),false,'EFFECT_UNCERTAIN','reconcile.frame-churn'));}
 /** @param {import('../storage/ledger.mjs').Transaction} tx @param {any} frame @param {'succeeded'|'failed'} status @param {any} outcome */
 settleTerminalIn(tx,frame,status,outcome){requireThat(frame.effect,'INTEGRITY_FAILURE');tx.run('INSERT INTO meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','effect-observation:'+frame.selection.leaderActionId,canonicalJson(outcome));for(const row of frame.members){tx.updateAction(/** @type {any} */({...row.action,status,step:status==='succeeded'?(row.cancelled?'complete.cancel_too_late':'complete'):'complete',resultId:frame.selection.resultId,errorCode:status==='failed'?'CONTENDED_REF':null}));this.fault('settlement.after-action-'+row.action.actionId);}if(frame.reservation?.held)tx.releaseAttempt(frame.reservation.attempt.attemptId);for(const row of frame.members){const work=tx.getWork(row.work.workId);requireThat(work&&work.currentActionId===row.action.actionId&&work.revision===row.member.reservedWorkRevision,'STALE_REVISION');requireThat(tx.compareWork(work.revision,{...work,currentActionId:null,revision:nextRevision(work.revision),disposition:status==='succeeded'?'integrated':'open'}),'STALE_REVISION');this.fault('settlement.after-work-'+row.work.workId);}}
 /** @param {import('../storage/ledger.mjs').Transaction} tx @param {any} frame @param {boolean} stopped @param {string} errorCode @param {string} step */
 blockIn(tx,frame,stopped,errorCode,step){for(const row of frame.members)if(!terminal(row.action.status)&&row.action.status!=='blocked')tx.updateAction(/** @type {any} */({...row.action,status:'blocked',step,errorCode,ownerEpoch:this.ledger.ownerEpoch}));else if(row.action.status==='blocked')tx.updateAction(/** @type {any} */({...row.action,step,errorCode,ownerEpoch:this.ledger.ownerEpoch}));if(stopped&&frame.reservation?.held)tx.releaseAttempt(frame.reservation.attempt.attemptId);}
 /** @param {import('../storage/ledger.mjs').Transaction} tx @param {any} frame */
 fallbackIn(tx,frame){requireThat(!frame.effect,'INTEGRITY_FAILURE','Frozen H2 effect must resolve before fallback');if(frame.reservation?.held)tx.releaseAttempt(frame.reservation.attempt.attemptId);for(const row of frame.members){const work=tx.getWork(row.work.workId),action=tx.getAction(row.action.actionId);requireThat(work&&action&&work.currentActionId===action.actionId,'STALE_REVISION');const cancelled=row.cancelled||action.deadline<=this.engine.now();if(cancelled){if(['running','blocked'].includes(action.status))tx.updateAction({...ordinaryAction(action),status:'cancelled',step:'cancel.before.h2.effect',errorCode:null});const current=tx.getWork(work.workId);requireThat(current&&tx.compareWork(current.revision,{...current,currentActionId:null,revision:nextRevision(current.revision)}),'STALE_REVISION');}else{let current=action;if(current.status==='running'){current={...current,status:'blocked',step:'h2.fallback',errorCode:null};tx.updateAction(current);}requireThat(current.status==='blocked','STALE_REVISION');tx.updateAction({...ordinaryAction(current),status:'queued',step:'h2.fallback',errorCode:null,ownerEpoch:this.ledger.ownerEpoch});}}tx.retireH2Members(frame.selection.memberTupleDigest);}
 /** Positive sender stop plus exact H unchanged (`retryable`) is authoritative
  * no-publication proof even if a previous physical invocation reported sent.
  * @param {any} selection @param {import('../contracts/ports.js').Attempt} attempt @param {unknown} error */
 async fail(selection,attempt,error){const frame=this.ledger.transact(tx=>this.frameIn(tx,selection)),effect=frame.effect;if(!effect){let stopped=!frame.reservation?.held;if(!stopped&&this.engine.o.attemptStopped)try{stopped=await this.engine.o.attemptStopped(attempt);}catch{stopped=false;}if(stopped&&error instanceof Dev2Error&&['VALIDATION_FAILED','STALE_REVISION','STALE_BASE','STALE_RESULT','FORBIDDEN','UNAUTHORIZED','ENTRY_CONFLICT','LIMIT_EXCEEDED','EXECUTION_UNAVAILABLE'].includes(error.code)){this.ledger.transact(tx=>this.fallbackIn(tx,this.frameIn(tx,selection)));return;}this.ledger.transact(tx=>this.blockIn(tx,this.frameIn(tx,selection),stopped,codeOf(error),'h2.failed'));return;}const sender=await this.senderObservation(effect),principal=/** @type {import('../contracts/ports.js').Principal} */(/** @type {unknown} */(this.engine.metadata('principal:'+selection.leaderActionId))),integrator=this.engine.integrator(principal,this.engine.input(selection.leaderActionId)),outcome=await integrator.reconcile(effect,sender.stopped);if(sender.stopped&&outcome.kind==='retryable'){this.ledger.transact(tx=>{const current=this.frameIn(tx,selection);requireThat(current.effect&&canonicalJson(current.effect)===canonicalJson(effect),'STALE_REVISION');tx.run('INSERT INTO meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','h2-disarmed:'+effect.effectId,canonicalJson({effect,outcome,reason:codeOf(error)}));requireThat(tx.run('DELETE FROM effect WHERE effect_id=? AND action_id=?',effect.effectId,selection.leaderActionId).changes===1,'STALE_REVISION');const next=this.frameIn(tx,selection);this.fallbackIn(tx,{...next,effect:null});});return;}await this.reconcile(selection,attempt,effect,integrator);}
 /** @param {any} selection @param {import('../contracts/ports.js').Attempt} attempt */
 async execute(selection,attempt){let result=/** @type {import('../contracts/ports.js').PreparedResult|null} */(null),receipt=/** @type {import('../contracts/ports.js').ValidationReceipt|null} */(null),effect=/** @type {import('../contracts/ports.js').Effect|null} */(null),validationRunning=false;try{const immutable=await this.immutable(selection);this.ledger.transact(tx=>this.assertMembers(tx,selection,null));effect=this.ledger.transact(tx=>tx.getDirectEffect(selection.leaderActionId));if(effect){result=this.ledger.transact(tx=>tx.getPrepared(effect.preparedResultId));requireThat(result,'INTEGRITY_FAILURE');receipt=await this.receipt(result);requireThat(receipt&&receipt.validationId===effect.validationId,'VALIDATION_FAILED');await this.publish(selection,attempt,effect,result,receipt);return;}result=await this.result(selection,attempt);let current=await this.receipt(result);if(!current){requireThat(this.engine.o.executionAvailable?.()!==false,'EXECUTION_UNAVAILABLE');validationRunning=true;current=await this.engine.o.validation().validate(result,attempt);validationRunning=false;this.engine.assertAttempt(attempt);this.ledger.transact(tx=>{const frame=this.assertMembers(tx,selection,'running');requireThat(frame.members.every(row=>!row.cancelled&&row.action.deadline>this.engine.now()),'STALE_REVISION');tx.putReceipt(current);for(const row of frame.members)tx.updateAction(/** @type {any} */({...row.action,step:'h2.validated',resultId:result.resultId}));});}receipt=current;requireThat(await this.engine.o.validation().eligible(result,receipt,this.engine.binding.policyDigest,this.ledger.ownerEpoch),'VALIDATION_FAILED');const observed=await this.engine.o.remote.resolve();if(observed.head!==selection.expectedHead)throw new Dev2Error('STALE_BASE','Canonical head moved before H2 effect freeze');await this.engine.o.remote.fetch(observed.head);const authorized=await this.authorizeAll(immutable,selection);effect=this.freezeEffect(selection,result,receipt,authorized);this.fault('after-effect-intent');await this.publish(selection,attempt,effect,result,receipt);}catch(error){if(validationRunning&&this.engine.o.attemptStopped)try{await this.engine.o.attemptStopped(attempt);}catch{}await this.fail(selection,attempt,error);}}
 /** @param {string} actionId */
 cancellationFrame(actionId){return this.ledger.transact(tx=>{const selected=tx.getH2Selection(actionId);if(!selected)return null;const frame=this.frameIn(tx,selected.selection);return {selection:selected.selection,attempt:frame.reservation?.attempt??null,effect:frame.effect,leaderActionId:frame.leader.action.actionId};});}
 /** @param {import('../storage/ledger.mjs').Transaction} tx @param {any} selection */
 adoptIn(tx,selection){const frame=this.frameIn(tx,selection);if(frame.reservation)tx.adoptAttempt(frame.reservation.attempt.attemptId);let changed=0;for(const row of frame.members)if(!terminal(row.action.status)&&row.action.ownerEpoch!==this.ledger.ownerEpoch){tx.updateAction(/** @type {any} */({...row.action,status:'blocked',step:'recovery.required',ownerEpoch:this.ledger.ownerEpoch,errorCode:'EFFECT_UNCERTAIN'}));changed++;}return changed;}
 /** @param {import('../contracts/ports.js').Principal} principal @param {string} actionId @param {string} expectedRevision */
 async recoveryPlan(principal,actionId,expectedRevision){const selected=this.selected(actionId);requireThat(selected,'INTEGRITY_FAILURE');const selection=selected.selection,before=this.ledger.transact(tx=>{const frame=this.frameIn(tx,selection),requested=frame.members.find(row=>row.action.actionId===actionId);requireThat(requested&&requested.work.principal===principal.subject&&requested.work.revision===expectedRevision,'STALE_REVISION');return {frame,stamp:this.stamp(frame)};});if(before.frame.members.every(row=>terminal(row.action.status)))return {h2:true,mode:'already',selection,stamp:before.stamp,actionId};requireThat(before.frame.members.every(row=>row.action.status==='blocked')&&!this.engine.running.has(selection.leaderActionId),'EFFECT_UNCERTAIN');let stopped=!before.frame.reservation?.held;if(!stopped&&before.frame.reservation&&this.engine.o.attemptStopped)try{stopped=await this.engine.o.attemptStopped(before.frame.reservation.attempt);}catch{stopped=false;}if(!stopped)return {h2:true,mode:'blocked',selection,stamp:before.stamp,actionId};let sender={stopped:true,delivery:'not_sent',state:'absent'},outcome=null;if(before.frame.effect){sender=await this.senderObservation(before.frame.effect);const leaderPrincipal=/** @type {import('../contracts/ports.js').Principal} */(/** @type {unknown} */(this.engine.metadata('principal:'+selection.leaderActionId)));outcome=await this.engine.integrator(leaderPrincipal,this.engine.input(selection.leaderActionId)).reconcile(before.frame.effect,sender.stopped);if(!sender.stopped)return {h2:true,mode:'blocked',selection,stamp:before.stamp,actionId,outcome,sender};if(outcome.kind==='integrated')return {h2:true,mode:'terminal',status:'succeeded',selection,stamp:before.stamp,actionId,outcome,sender};if(outcome.kind==='stale')return {h2:true,mode:'terminal',status:'failed',selection,stamp:before.stamp,actionId,outcome,sender};if(outcome.kind!=='retryable')return {h2:true,mode:'blocked',selection,stamp:before.stamp,actionId,outcome,sender};}const latest=this.ledger.transact(tx=>this.frameIn(tx,selection));requireThat(this.stamp(latest)===before.stamp,'STALE_REVISION');const cancelled=latest.members.some(row=>row.cancelled||row.action.deadline<=this.engine.now()),policyChanged=this.engine.o.policy().policy.digest!==selection.policyDigest;if(before.frame.effect&&(cancelled||policyChanged)&&sender.stopped&&outcome?.kind==='retryable')return {h2:true,mode:'disarm-fallback',selection,stamp:before.stamp,actionId,outcome,sender};if(!before.frame.effect&&(cancelled||policyChanged))return {h2:true,mode:'fallback',selection,stamp:before.stamp,actionId};const immutable=await this.immutable(selection);await this.authorizeAll(immutable,selection);requireThat(this.engine.o.policy().required().every(profile=>profile.replaySafe),'EFFECT_UNCERTAIN');return {h2:true,mode:'retry',selection,stamp:before.stamp,actionId};}
 /** @param {import('../storage/ledger.mjs').Transaction} tx @param {any} plan @param {import('../contracts/ports.js').Principal} principal */
 applyRecovery(tx,plan,principal){const frame=this.frameIn(tx,plan.selection);requireThat(this.stamp(frame)===plan.stamp,'STALE_REVISION');const requested=frame.members.find(row=>row.action.actionId===plan.actionId);requireThat(requested&&requested.work.principal===principal.subject,'FORBIDDEN');if(plan.mode==='already'||plan.mode==='blocked')return requested.work;if(plan.mode==='terminal'){requireThat(frame.effect&&plan.outcome,'INTEGRITY_FAILURE');this.settleTerminalIn(tx,frame,plan.status,plan.outcome);return tx.getWork(requested.work.workId);}if(plan.mode==='disarm-fallback'){requireThat(frame.effect&&plan.sender?.stopped&&plan.outcome?.kind==='retryable','EFFECT_UNCERTAIN');tx.run('INSERT INTO meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','h2-disarmed:'+frame.effect.effectId,canonicalJson({effect:frame.effect,outcome:plan.outcome,reason:'recovery'}));requireThat(tx.run('DELETE FROM effect WHERE effect_id=?',frame.effect.effectId).changes===1,'STALE_REVISION');const next=this.frameIn(tx,plan.selection);this.fallbackIn(tx,{...next,effect:null});return tx.getWork(requested.work.workId);}if(plan.mode==='fallback'){this.fallbackIn(tx,frame);return tx.getWork(requested.work.workId);}requireThat(plan.mode==='retry','INTEGRITY_FAILURE');requireThat(tx.reservations().length<this.engine.coordinator.executionCapacity,'CAPACITY_REJECTED');if(frame.reservation?.held)tx.releaseAttempt(frame.reservation.attempt.attemptId);for(const row of frame.members){requireThat(row.action.status==='blocked','STALE_REVISION');tx.updateAction(/** @type {any} */({...row.action,status:'queued',step:'h2.reconciled.retry',errorCode:null,ownerEpoch:this.ledger.ownerEpoch}));}const leader=tx.getAction(plan.selection.leaderActionId),leaderWork=frame.leader.work;requireThat(leader,'INTEGRITY_FAILURE');const attempt={installationId:this.engine.binding.installationId,repositoryId:this.engine.binding.repositoryId,workId:leaderWork.workId,actionId:leader.actionId,attemptId:newId(),attempt:nextRevision(leader.attempt),ownerEpoch:this.ledger.ownerEpoch};requireThat(tx.reserveAttempt(attempt,this.engine.coordinator.executionCapacity),'CAPACITY_REJECTED');for(const row of frame.members){const action=tx.getAction(row.action.actionId);requireThat(action&&action.status==='queued','STALE_REVISION');tx.updateAction(/** @type {any} */({...action,status:'running',step:'h2.launch.reserved',attempt:action.actionId===leader.actionId?attempt.attempt:action.attempt,ownerEpoch:this.ledger.ownerEpoch}));}plan.startAttempt=attempt;return tx.getWork(requested.work.workId);}
}
