import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {ActivationJournal} from '../../src/release/journal.mjs';import {ActivationController,activationSteps} from '../../src/release/activation.mjs';import {canonicalJson} from '../../src/contracts/canonical.mjs';
const same=(a,b)=>assert.equal(canonicalJson(a),canonicalJson(b));
const d=n=>'sha256:'+String(n).repeat(64),o=n=>'sha1:'+String(n).repeat(40);
const pair=n=>({releaseId:d(n),schemaDigest:d(3),sourceCommitOid:o(n),deviceReleaseId:d(n),deviceArtifactDigest:d(n),deviceSourceCommitOid:o(n),edgeVersionId:'edge-'+n,edgeArtifactDigest:d(n),edgeSourceCommitOid:o(n),protocol:{min:1,max:1},ledger:{min:1,max:1}});
const intent=(name='a')=>({activationId:name,actionId:name,installationId:'i',repositoryId:'r',bindingEpoch:'1',principalId:'human',createdAt:1000,deadline:2000,previous:pair(1),target:pair(2)});
function fixture(journal){let clock=1100,loseAt=null,failAt=null,uncertain=false;const sent=[],effects=new Map();let observed=pair(1);let stopped=false;
 const receipt=(e,kind,output={},senderStopped=true)=>({effectId:e.effectId,inputDigest:e.inputDigest,kind,senderStopped,observedAt:clock,output});
 const port={reconcile:async e=>uncertain?receipt(e,'pending',{},false):effects.get(e.effectId)??receipt(e,'not_applied'),execute:async e=>{assert.equal(journal.read(e.activationId).pending.state,'sent');sent.push(e);if(failAt===e.step&&e.direction==='forward')return receipt(e,'failed');let output={};if(e.step==='edge.activate'){observed={...observed,edgeVersionId:e.target.edgeVersionId,edgeArtifactDigest:e.target.edgeArtifactDigest,edgeSourceCommitOid:e.target.edgeSourceCommitOid};output={edgeVersionId:e.target.edgeVersionId};}if(e.step==='device.drain')output={drained:true};if(e.step==='device.stop'){stopped=true;output={writerStopped:true};}if(e.step==='device.switch'){assert.equal(stopped,true);observed={...observed,deviceReleaseId:e.target.deviceReleaseId,deviceArtifactDigest:e.target.deviceArtifactDigest,deviceSourceCommitOid:e.target.deviceSourceCommitOid};output={deviceReleaseId:e.target.deviceReleaseId};}if(e.step==='device.start'){stopped=false;output={deviceReleaseId:e.target.deviceReleaseId};}if(e.step==='pair.check'){assert.equal(observed.edgeVersionId,e.target.edgeVersionId);assert.equal(observed.deviceReleaseId,e.target.deviceReleaseId);observed=structuredClone(e.target);output={healthy:true,pair:observed};}const r=receipt(e,'applied',output);effects.set(e.effectId,r);if(loseAt===e.step){loseAt=null;throw Error('response lost AFTER provider applied');}return r;}};
 return {port,sent,effects,receipt,controller:new ActivationController({journal,port,now:()=>clock}),setJournal:j=>journal=j,setClock:v=>clock=v,lose:v=>loseAt=v,fail:v=>failAt=v,uncertain:v=>uncertain=v,observed:()=>observed};}

test('durable exact activation, deduplication and paired health before terminal success',async()=>{const j=new ActivationJournal(':memory:','i');try{assert.equal(j.begin(intent()).revision,'0');assert.equal(j.begin(intent()).revision,'0');assert.throws(()=>j.begin({...intent(),deadline:3000}),{code:'IDEMPOTENCY_MISMATCH'});assert.throws(()=>j.begin(intent('b')),{code:'CAPACITY_REJECTED'});const w=fixture(j);const [a,b]=await Promise.all([w.controller.drive('a'),w.controller.drive('a')]);assert.equal(a.phase,'active');same(a,b);assert.equal(w.sent.length,6);same(a.observedPair,pair(2));assert.equal(j.active(),null);same(await w.controller.drive('a'),a);assert.equal(w.sent.length,6);}finally{j.close();}});

test('response loss blocks only the exact activation, resumes same effect without a second send',async()=>{const j=new ActivationJournal(':memory:','i');try{j.begin(intent());const w=fixture(j);w.lose('edge.activate');const lost=await w.controller.drive('a');assert.equal(lost.phase,'blocked');assert.equal(lost.pending.state,'sent');assert.equal(lost.direction,'forward');assert.equal(w.sent.length,1);w.uncertain(true);assert.equal((await w.controller.drive('a')).phase,'blocked');assert.equal(w.sent.length,1);w.uncertain(false);assert.equal((await w.controller.drive('a')).phase,'active');assert.equal(w.sent.filter(e=>e.step==='edge.activate').length,1);}finally{j.close();}});

test('failed device startup rolls back both components with verified stopped-writer handoffs',async()=>{const j=new ActivationJournal(':memory:','i');try{j.begin(intent());const w=fixture(j);w.fail('device.start');const done=await w.controller.drive('a');assert.equal(done.phase,'rolled_back');same(done.observedPair,pair(1));assert.equal(w.sent.filter(e=>e.step==='device.stop').length,2);assert.ok(w.sent.some(e=>e.direction==='rollback'&&e.step==='edge.activate'));}finally{j.close();}});

test('deadline cannot prove an uncertain sender stopped or trigger an opposite edge update',async()=>{const j=new ActivationJournal(':memory:','i');try{j.begin(intent());const w=fixture(j);w.lose('edge.activate');await w.controller.drive('a');w.setClock(2500);w.uncertain(true);const blocked=await w.controller.drive('a');assert.equal(blocked.phase,'blocked');assert.equal(w.sent.length,1);assert.equal(blocked.direction,'forward');w.uncertain(false);const done=await w.controller.drive('a');assert.equal(done.phase,'rolled_back');same(done.observedPair,pair(1));}finally{j.close();}});

test('partial edge/device readback is never active and late/misbound receipts are rejected',async()=>{for(const variant of ['mixed','wrong-effect','stale']){const j=new ActivationJournal(':memory:','i');try{j.begin(intent());const w=fixture(j),execute=w.port.execute;w.port.execute=async e=>{const r=await execute(e);if(e.step==='pair.check'){if(variant==='mixed')r.output.pair={...pair(2),edgeVersionId:'edge-1'};if(variant==='wrong-effect')r.effectId='another';if(variant==='stale')r.observedAt=-100000;}return r;};assert.equal((await w.controller.drive('a')).phase,'blocked');assert.notEqual(j.read('a').phase,'active');}finally{j.close();}}});

test('real SQLite owner lock and restart reconcile the exact pending effect without duplicate send',async()=>{const dir=await mkdtemp(join(tmpdir(),'dev2-release-journal-'));let j;try{const file=join(dir,'helper.sqlite');j=new ActivationJournal(file,'i');j.begin(intent());const w=fixture(j);w.lose('edge.activate');const blocked=await w.controller.drive('a');assert.throws(()=>new ActivationJournal(file,'i'),{code:'EXECUTION_UNAVAILABLE'});const oldEpoch=j.ownerEpoch;j.close();j=new ActivationJournal(file,'i');assert.notEqual(j.ownerEpoch,oldEpoch);assert.equal(j.read('a').pending.effect.effectId,blocked.pending.effect.effectId);assert.equal(j.read('a').intentDigest,blocked.intentDigest);assert.throws(()=>j.replace(blocked.revision,blocked,oldEpoch),{code:'STALE_REVISION'});w.setJournal(j);const resumed=new ActivationController({journal:j,port:w.port,now:()=>1100});assert.equal((await resumed.drive('a')).phase,'active');assert.equal(w.sent.filter(e=>e.step==='edge.activate').length,1);same(j.read('a').observedPair,pair(2));}finally{j?.close();await rm(dir,{recursive:true,force:true});}});

test('edge-only release never drains or restarts the unrelated device component',async()=>{const j=new ActivationJournal(':memory:','i');try{const input=intent();for(const k of ['deviceReleaseId','deviceArtifactDigest','deviceSourceCommitOid'])input.target[k]=input.previous[k];const record=j.begin(input);assert.deepEqual(activationSteps(record),['edge.activate','pair.check']);const w=fixture(j),done=await w.controller.drive('a');assert.equal(done.phase,'active');assert.deepEqual(w.sent.map(e=>e.step),['edge.activate','pair.check']);same(done.observedPair,input.target);}finally{j.close();}});

test('device-only release never redeploys the unaffected Worker version',async()=>{const j=new ActivationJournal(':memory:','i');try{const input=intent();for(const k of ['edgeVersionId','edgeArtifactDigest','edgeSourceCommitOid'])input.target[k]=input.previous[k];j.begin(input);const w=fixture(j),done=await w.controller.drive('a');assert.equal(done.phase,'active');assert.equal(w.sent.some(e=>e.step==='edge.activate'),false);assert.equal(w.sent.filter(e=>e.step==='device.stop').length,1);same(done.observedPair,input.target);}finally{j.close();}});
