import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile,chmod,symlink} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {Ledger} from '../../src/storage/ledger.mjs';import {ReleaseBackend} from '../../src/release/backend.mjs';import {ReleaseArtifactStore} from '../../src/release/artifacts.mjs';import {ActivationJournal} from '../../src/release/journal.mjs';import {ActivationController} from '../../src/release/activation.mjs';import {releaseIdentity} from '../../src/release/manifest.mjs';import {bytesDigest,recordDigest,canonicalJson} from '../../src/contracts/canonical.mjs';import {Dev2Error} from '../../src/contracts/errors.mjs';
const d=n=>'sha256:'+String(n).repeat(64),o=n=>'sha1:'+String(n).repeat(40);
const equal=(a,b)=>assert.equal(canonicalJson(a),canonicalJson(b));
const pair=()=>({releaseId:d(1),schemaDigest:d(3),sourceCommitOid:o(1),deviceReleaseId:d(1),deviceArtifactDigest:d(1),deviceSourceCommitOid:o(1),edgeVersionId:'old-edge',edgeArtifactDigest:d(1),edgeSourceCommitOid:o(1),protocol:{min:1,max:1},ledger:{min:1,max:1}});
// These provider/builder ports are deterministic fixtures. The test labels do
// not claim a production managed receipt, live Cloudflare effect or Android stop.
async function world(){
 const directory=await mkdtemp(join(tmpdir(),'dev2-release-backend-')),binding={repositoryId:'r',installationId:'i',provider:'fixture',providerRepositoryId:'1',remote:'fixture',ref:'refs/heads/dev-2',bindingEpoch:'1',policyDigest:d(4)},ledger=new Ledger(join(directory,'work.sqlite'),binding),journal=new ActivationJournal(join(directory,'helper.sqlite'),'i');
 const principal={subject:'human',issuer:'fixture',audience:'fixture',expiresAt:10000},source={repositoryId:'r',bindingEpoch:'1',commitOid:o(2),source:{treeOid:o(3),manifestDigest:d(2),entries:[]},policyDigest:d(4),validationId:d(5)};
 const objects=new Map(),store={put:async bytes=>{const key=bytesDigest(bytes);objects.set(key,Buffer.from(bytes));return key;},get:async key=>{assert.ok(objects.has(key));return objects.get(key);}};
 const refs={device:await store.put(Buffer.from('fixture device bytes')),edge:await store.put(Buffer.from('fixture edge bytes')),tools:await store.put(Buffer.from(JSON.stringify(['dev_context','dev_read','dev_work','dev_observe'].map(name=>({name,annotations:{readOnlyHint:true,destructiveHint:false}})))))};
 const manifest={schemaVersion:1,repositoryId:'r',bindingEpoch:'1',sourceCommitOid:o(2),sourceTreeOid:o(3),sourceManifestDigest:d(2),policyDigest:d(4),schemaDigest:d(3),protocol:{min:1,max:1},ledger:{min:1,max:1},installationSealDigest:d(6),requiredValidationId:d(5),releaseValidationId:d(7),device:{artifactDigest:refs.device,sourceCommitOid:o(2)},edge:{artifactDigest:refs.edge,sourceCommitOid:o(2),compatibilityDate:'2026-08-15'},executor:{workflowDigest:d(6),controllerDigest:d(7),sealDigest:d(8)}},build={manifest,refs,receipt:{kind:'fixture-only'}};
 let clock=1100,active=pair(),granted=true,qualified=true,builds=0,uploads=0,loseUpload=false,unknown=false,autoDrive=true,failStart=false;
 const stageEffects=new Map(),activationEffects=new Map(),sent=[];
 const edge={reconcile:async effect=>{if(unknown)return {effectId:effect.effectId,inputDigest:effect.inputDigest,kind:'pending',senderStopped:false,versionId:null,artifactDigest:null,observedAt:clock};return stageEffects.get(effect.effectId)??{effectId:effect.effectId,inputDigest:effect.inputDigest,kind:'absent',senderStopped:true,versionId:null,artifactDigest:null,observedAt:clock};},execute:async effect=>{uploads++;const retained=backend.record('release.stage:stage');assert.equal(retained.effect.effectId,effect.effectId);const result={effectId:effect.effectId,inputDigest:effect.inputDigest,kind:'ready',senderStopped:true,versionId:'new-edge',artifactDigest:effect.artifactDigest,observedAt:clock};stageEffects.set(effect.effectId,result);if(loseUpload){loseUpload=false;throw Error('response lost after exact inactive upload');}return result;}};
 const receipt=(e,kind,output)=>({effectId:e.effectId,inputDigest:e.inputDigest,kind,senderStopped:true,observedAt:clock,output});
 const port={reconcile:async e=>activationEffects.get(e.effectId)??receipt(e,'not_applied',{}),execute:async e=>{sent.push(e);let output={};if(e.step==='edge.activate')output={edgeVersionId:e.target.edgeVersionId};if(e.step==='device.drain')output={drained:true};if(e.step==='device.stop')output={writerStopped:true};if(e.step==='device.switch'||e.step==='device.start')output={deviceReleaseId:e.target.deviceReleaseId};if(e.step==='device.start'&&e.direction==='forward'&&failStart)return receipt(e,'failed',{});if(e.step==='pair.check'){active=structuredClone(e.target);output={healthy:true,pair:active};}const r=receipt(e,'applied',output);activationEffects.set(e.effectId,r);return r;}};
 const controller=new ActivationController({journal,port,now:()=>clock}),helper={activePair:async()=>structuredClone(active),begin:async intent=>{journal.begin(intent);return autoDrive?controller.drive(intent.activationId):journal.read(intent.activationId);},observe:async id=>journal.read(id)};
 const artifacts=new ReleaseArtifactStore({root:join(directory,'releases'),objects:store,schemaDigest:d(3)});
 const options={ledger,binding,authority:{verify:async(commit,policy)=>{assert.equal(commit,source.commitOid);assert.equal(policy,source.policyDigest);return source;}},artifacts,builder:{build:async()=>{builds++;return structuredClone(build);},verify:async()=>qualified,stopped:async()=>true},edge,helper,authorize:async()=>{if(!granted)throw new Dev2Error('FORBIDDEN');},now:()=>clock};
 const backend=new ReleaseBackend(options);
 const action=(name,operation)=>ledger.transact(tx=>tx.insertAction({actionId:name,requestId:name,principal:'human',bindingEpoch:'1',intentDigest:d(9),operation,workId:null,status:'running',step:'special',attempt:'1',ownerEpoch:ledger.ownerEpoch,deadline:9000,resultId:null,errorCode:null}));
 const stageInput={integratedCommit:o(2),policyDigest:d(4),expectedActiveRelease:d(1)};
 return {directory,ledger,journal,binding,source,objects,store,manifest,build,artifacts,backend,options,controller,helper,principal,action,stageInput,sent,stageEffects,builds:()=>builds,uploads:()=>uploads,setUnknown:v=>unknown=v,loseUpload:()=>loseUpload=true,setQualified:v=>qualified=v,setGranted:v=>granted=v,setClock:v=>clock=v,setAuto:v=>autoDrive=v,setFailStart:v=>failStart=v,setActive:v=>active=structuredClone(v),active:()=>active,stage:async()=>{action('stage','release.stage');return backend.stage(principal,stageInput,'stage');},activate:async()=>{action('activate','release.activate');return backend.activate(principal,{stagedReleaseId:releaseIdentity(manifest).slice(7),expectedActiveRelease:d(1)},'activate');},close:async()=>{ledger.close();journal.close();await rm(directory,{recursive:true,force:true});}};
}

test('staging persists exact integrated artifacts and does not activate; duplicate observation never rebuilds or uploads',async()=>{const w=await world();try{const result=await w.stage();assert.equal(result.state,'staged');assert.equal(result.releaseId,releaseIdentity(w.manifest));equal(w.active(),pair());assert.equal(w.builds(),1);assert.equal(w.uploads(),1);w.setClock(1200);equal(await w.backend.stage(w.principal,w.stageInput,'stage'),result);assert.equal(w.builds(),1);assert.equal(w.uploads(),1);assert.equal((await w.backend.recovery('stage')).effectResolved,true);}finally{await w.close();}});

test('lost inactive version upload response resumes exact effect; uncertain observation never issues a replacement upload',async()=>{const w=await world();try{w.loseUpload();await assert.rejects(()=>w.stage());const effect=w.backend.record('release.stage:stage').effect;w.setUnknown(true);await assert.rejects(()=>w.backend.stage(w.principal,w.stageInput,'stage'),{code:'EFFECT_UNCERTAIN'});assert.equal(w.uploads(),1);w.setUnknown(false);assert.equal((await w.backend.stage(w.principal,w.stageInput,'stage')).state,'staged');equal(w.backend.record('release.stage:stage').effect,effect);assert.equal(w.builds(),1);assert.equal(w.uploads(),1);}finally{await w.close();}});

test('invalid release receipt cannot create an artifact directory, provider upload or stage receipt',async()=>{const w=await world();try{w.setQualified(false);await assert.rejects(()=>w.stage(),{code:'VALIDATION_FAILED'});assert.equal(w.uploads(),0);assert.equal(w.backend.record('release.stage:stage').build,null);equal(w.active(),pair());}finally{await w.close();}});

test('wrong integrated-source build and cancelled asynchronous continuation fail before upload',async()=>{for(const variant of ['source','cancel']){const w=await world();try{if(variant==='source')w.manifest.sourceCommitOid=o(8);else w.options.builder.verify=async()=>{w.ledger.transact(tx=>tx.run('INSERT INTO meta VALUES(?,?)','cancel:stage','true'));return true;};await assert.rejects(()=>w.stage(),{code:variant==='source'?'INTEGRITY_FAILURE':'STALE_REVISION'});assert.equal(w.uploads(),0);}finally{await w.close();}}});

test('actual artifact bytes are rehashed; a staged device edit and symlink cannot be activated',async()=>{for(const variant of ['bytes','link']){const w=await world();try{await w.stage();const file=join(w.artifacts.directory(releaseIdentity(w.manifest)),'device.cjs');await chmod(file,0o600);if(variant==='bytes')await writeFile(file,'modified');else{await rm(file);await symlink('/etc/passwd',file);}await assert.rejects(()=>w.activate());assert.equal(w.sent.length,0);}finally{await w.close();}}});

test('staging is not runtime authority; stale active pair and revoked grant reject activation before helper intent',async()=>{for(const variant of ['stale','grant']){const w=await world();try{await w.stage();if(variant==='stale')w.setActive({...pair(),edgeVersionId:'foreign-edge'});else w.setGranted(false);await assert.rejects(()=>w.activate(),{code:variant==='stale'?'STALE_RESULT':'FORBIDDEN'});assert.equal(w.journal.active(),null);assert.equal(w.sent.length,0);}finally{await w.close();}}});

test('paired activation joins the fixed helper and reports exact active runtime instead of source HEAD',async()=>{const w=await world();try{await w.stage();const result=await w.activate();assert.equal(result.state,'active');assert.equal(result.releaseId,releaseIdentity(w.manifest));assert.equal(result.sourceCommitOid,o(2));const observed=await w.backend.recovery('activate');assert.equal(observed.effectResolved,true);equal(observed.output,result);assert.equal(w.sent.length,6);const retained=w.backend.record('release.activation:activate');assert.equal(retained.intent.activationId,result.activationId);}finally{await w.close();}});

test('pending helper survives broker response loss and is recovered by observation of the same activation',async()=>{const w=await world();try{await w.stage();w.setAuto(false);await assert.rejects(()=>w.activate(),{code:'EFFECT_UNCERTAIN'});const old=w.backend.record('release.activation:activate');assert.equal((await w.backend.recovery('activate')).effectResolved,false);const recovered=new ReleaseBackend(w.options);await w.controller.drive(old.intent.activationId);const result=await recovered.recovery('activate');assert.equal(result.output.state,'active');assert.equal(result.output.activationId,old.intent.activationId);assert.equal(w.sent.length,6);}finally{await w.close();}});

test('failed target startup returns exact previous pair after rollback, not an active new release',async()=>{const w=await world();try{await w.stage();w.setFailStart(true);const result=await w.activate();assert.equal(result.state,'rolled_back');assert.equal(result.releaseId,d(1));assert.equal(result.sourceCommitOid,o(1));equal(w.active(),pair());assert.equal((await w.backend.recovery('activate')).output.state,'rolled_back');}finally{await w.close();}});

test('device-only staging reuses exact Worker without an upload; edge-only activation never stops unchanged device',async()=>{for(const changed of ['device','edge']){const w=await world();try{const previous=pair();if(changed==='device'){previous.edgeArtifactDigest=w.manifest.edge.artifactDigest;previous.edgeSourceCommitOid=w.manifest.edge.sourceCommitOid;}else{previous.deviceArtifactDigest=w.manifest.device.artifactDigest;previous.deviceSourceCommitOid=w.manifest.device.sourceCommitOid;}w.setActive(previous);await w.stage();assert.equal(w.uploads(),changed==='device'?0:1);const result=await w.activate();assert.equal(result.state,'active');assert.equal(w.sent.some(e=>e.step==='edge.activate'),changed==='edge');assert.equal(w.sent.some(e=>e.step==='device.stop'),changed==='device');}finally{await w.close();}}});

test('a retained native intent cannot bypass revoked path grants before its first fixed-helper admission',async()=>{const w=await world();try{w.source.source.entries=[{path:'src/owned.mjs'}];await w.stage();const begin=w.options.helper.begin;w.options.helper.begin=async()=>{throw Error('disconnect before helper admission');};await assert.rejects(()=>w.activate());const retained=w.backend.record('release.activation:activate');assert.ok(retained);assert.equal(w.journal.read(retained.intent.activationId),null);w.options.helper.begin=begin;w.options.authorize=async(principal,paths)=>{if(paths.includes('src/owned.mjs'))throw new Dev2Error('FORBIDDEN');};await assert.rejects(()=>w.backend.activate(w.principal,{stagedReleaseId:releaseIdentity(w.manifest).slice(7),expectedActiveRelease:d(1)},'activate'),{code:'FORBIDDEN'});assert.equal(w.journal.active(),null);assert.equal(w.sent.length,0);equal(w.backend.record('release.activation:activate'),retained);}finally{await w.close();}});

test('artifact staging rejects changed public annotation policy and never imports runtime source',async()=>{const w=await world();try{w.build.refs.tools=await w.store.put(Buffer.from(JSON.stringify(['dev_context','dev_read','dev_work','dev_observe'].map(name=>({name,annotations:{readOnlyHint:name!=='dev_work',destructiveHint:false}})))));await assert.rejects(()=>w.stage(),{code:'INTEGRITY_FAILURE'});assert.equal(w.uploads(),0);}finally{await w.close();}});
