import test from 'node:test';
import assert from 'node:assert/strict';
import {ActivationJournal} from '../../src/release/journal.mjs';
import {FixedReleaseService} from '../../src/release/helper-service.mjs';
import {releaseIdentity} from '../../src/release/manifest.mjs';
import {canonicalJson} from '../../src/contracts/canonical.mjs';

const d=n=>'sha256:'+String(n).repeat(64),o=n=>'sha1:'+String(n).repeat(40);
const V0='00000000-0000-4000-8000-000000000001',VT='00000000-0000-4000-8000-000000000002',VD='00000000-0000-4000-8000-000000000003';
const same=(a,b)=>assert.equal(canonicalJson(a),canonicalJson(b));

function world(options={}){
 const journal=new ActivationJournal(':memory:','installation'),previous={releaseId:d(1),schemaDigest:d(6),sourceCommitOid:o(1),deviceReleaseId:d(1),deviceArtifactDigest:d(1),deviceSourceCommitOid:o(1),edgeVersionId:V0,edgeArtifactDigest:d(1),edgeSourceCommitOid:o(1),protocol:{min:1,max:1},ledger:{min:1,max:1}},manifest={schemaVersion:1,identityNamespace:'tdev',repositoryId:'repository',bindingEpoch:'1',sourceCommitOid:o(3),sourceTreeOid:o(4),sourceManifestDigest:d(2),policyDigest:d(3),schemaDigest:d(6),protocol:{min:1,max:1},ledger:{min:1,max:1},installationSealDigest:d(4),requiredValidationId:d(5),releaseValidationId:d(7),device:{artifactDigest:d(8),sourceCommitOid:o(3)},edge:{artifactDigest:d(9),sourceCommitOid:o(3),compatibilityDate:'2026-09-01'},executor:{workflowDigest:d(1),controllerDigest:d(2),sealDigest:d(3)}};
 const releaseId=releaseIdentity(manifest),target={releaseId,schemaDigest:manifest.schemaDigest,sourceCommitOid:manifest.sourceCommitOid,deviceReleaseId:releaseId,deviceArtifactDigest:manifest.device.artifactDigest,deviceSourceCommitOid:manifest.device.sourceCommitOid,edgeVersionId:VT,edgeArtifactDigest:manifest.edge.artifactDigest,edgeSourceCommitOid:manifest.edge.sourceCommitOid,protocol:manifest.protocol,ledger:manifest.ledger},intent={identityNamespace:'tdev',activationId:'retained',actionId:'retained',installationId:'installation',repositoryId:'repository',bindingEpoch:'1',principalId:'human',createdAt:100,deadline:10000,previous,target};
 let record=journal.begin(intent);record=journal.replace(record.revision,{...record,phase:'active',cursor:2,pending:null,observedPair:target},journal.ownerEpoch);
 const build={manifest,refs:{device:manifest.device.artifactDigest,edge:manifest.edge.artifactDigest,tools:d(2)},receipt:{kind:'fixture'}},pointer={deviceReleaseId:target.deviceReleaseId},driftSource=o(9);let active=VD,sends=0,lose=!!options.lose;const receipts=new Map(),clock=1000;
 const native=()=>({schemaVersion:1,installationId:'installation',repositoryId:'repository',bindingEpoch:'1',deviceReleaseId:target.deviceReleaseId,sourceCommitOid:target.deviceSourceCommitOid,bundleDigest:target.deviceArtifactDigest,schemaDigest:target.schemaDigest,ownerEpoch:'1',connected:true,accepting:true,drainActivationId:null,drained:false,edge:{versionId:active===VT?VT:VD,bundleDigest:options.wrongArtifact?d(7):target.edgeArtifactDigest,sourceCommitOid:active===VT?target.edgeSourceCommitOid:driftSource,schemaDigest:target.schemaDigest}});
 const receipt=(effect,kind,output={})=>({effectId:effect.effectId,inputDigest:effect.inputDigest,kind,senderStopped:true,observedAt:clock,output});
 const edge={active:async()=>({versionId:active}),version:async id=>({id}),verifyVersion:(version,commit,artifact)=>{if(version.id===VT){assert.equal(commit,target.edgeSourceCommitOid);assert.equal(artifact,target.edgeArtifactDigest);}else{assert.equal(version.id,VD);assert.equal(commit,driftSource);assert.equal(artifact,target.edgeArtifactDigest);}return {versionId:version.id};},reconcileStage:async()=>{throw Error('unused');},upload:async()=>{throw Error('unused');},reconcileActivation:async effect=>receipts.get(effect.effectId)??(active===effect.expected.edgeVersionId?receipt(effect,'not_applied'):receipt(effect,'conflict',{reason:'provider_contender'})),activate:async effect=>{sends++;active=effect.target.edgeVersionId;const applied=receipt(effect,'applied',{edgeVersionId:effect.target.edgeVersionId});receipts.set(effect.effectId,applied);if(lose){lose=false;throw Error('response lost after provider applied');}return applied;}};
 const configs={pointerFor:async()=>pointer,current:async()=>pointer},artifacts={verify:async()=>({})},service=new FixedReleaseService({journal,controller:{},artifacts,configs,edge,nativeStatus:async()=>native(),baseline:previous,installationId:'installation',repositoryId:'repository',bindingEpoch:'1',installationSealDigest:d(4),executor:manifest.executor,now:()=>clock});
 service.retain('helper.build:'+releaseId,{build,previous});
 return {journal,service,target,state:{get sends(){return sends;},get active(){return active;}},activateForeign(){journal.begin({identityNamespace:'tdev',activationId:'foreign',actionId:'foreign',installationId:'installation',repositoryId:'repository',bindingEpoch:'1',principalId:'human',createdAt:100,deadline:10000,previous:target,target:{...target,releaseId:d(5)}});}};
}

test('retained edge drift repair is inspect/apply fenced and response-loss idempotent',async()=>{const w=world({lose:true});try{const plan=await w.service.recoverEdgeDrift(w.target.releaseId);assert.equal(plan.kind,'tdev.release-edge-drift-recovery-plan');assert.equal(plan.retainedReleaseId,w.target.releaseId);assert.equal(plan.observedEdgeVersionId,VD);assert.equal(plan.targetEdgeVersionId,VT);assert.equal(w.state.sends,0);assert.equal(w.journal.db.prepare("SELECT count(*) n FROM meta WHERE key LIKE 'helper.edge-drift-repair:%'").get().n,0);await assert.rejects(()=>w.service.recoverEdgeDrift(w.target.releaseId,d(0)),{code:'STALE_RESULT'});assert.equal(w.state.sends,0);await assert.rejects(()=>w.service.recoverEdgeDrift(w.target.releaseId,plan.planDigest));assert.equal(w.state.sends,1);assert.equal(w.state.active,VT);assert.equal(w.journal.db.prepare("SELECT count(*) n FROM meta WHERE key LIKE 'helper.edge-drift-repair:%'").get().n,1);const recovered=await w.service.recoverEdgeDrift(w.target.releaseId,plan.planDigest);assert.equal(recovered.kind,'tdev.release-edge-drift-recovered');assert.equal(recovered.effectId,plan.effectId);assert.equal(w.state.sends,1);assert.equal(w.state.active,VT);same(w.service.retainedPair(),w.target);}finally{w.journal.close();}});

test('retained edge drift repair rejects different bytes and active activation',async()=>{const bytes=world({wrongArtifact:true});try{await assert.rejects(()=>bytes.service.recoverEdgeDrift(bytes.target.releaseId),{code:'EFFECT_UNCERTAIN'});assert.equal(bytes.state.sends,0);}finally{bytes.journal.close();}const active=world();try{active.activateForeign();await assert.rejects(()=>active.service.recoverEdgeDrift(active.target.releaseId),{code:'EFFECT_UNCERTAIN'});assert.equal(active.state.sends,0);}finally{active.journal.close();}});
