import test from 'node:test';import assert from 'node:assert/strict';
import {Ledger} from '../../src/storage/ledger.mjs';import {PolicyState,qualifiedPolicy} from '../../src/release/policy.mjs';import {recordDigest,bytesDigest} from '../../src/contracts/canonical.mjs';import {bootstrapPolicy} from '../../src/validation/bootstrap-policy.mjs';import {sourceManifest} from '../../src/repository/entries.mjs';
import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
const d=n=>'sha256:'+String(n).repeat(64),o=n=>'sha1:'+String(n).repeat(40);
function definition(){const profiles=['core','integration'].map(profileId=>{const p={profileId,argv:['/usr/local/bin/node','/source/tools/validate.mjs','--profile',profileId],cwd:'',parameters:{},timeoutMs:300000,killGraceMs:2000,memoryBytes:1073741824,pids:128,cpuMillis:1000,diskBytes:536870912,logBytes:65536,network:'none',imageDigest:d(1),replaySafe:true};return {profile:{...p,digest:recordDigest('dev2.profile.v1',p)},parameterSchema:{type:'object',additionalProperties:false,maxProperties:0}};});const body={profiles,required:['core','integration'],execution:{orderedProfileDigests:profiles.map(p=>p.profile.digest),trustedRunnerDigest:d(2),toolchainDigest:d(3),environmentClass:'github-hosted-rootless-oci',dependencyLockDigest:d(4)}};return {schemaVersion:1,digest:recordDigest('dev2.execution-policy.v1',body),...body};}
function action(j,id='adopt'){j.transact(tx=>tx.insertAction({actionId:id,requestId:id,principal:'human',bindingEpoch:'1',intentDigest:d(8),operation:'policy.adopt',workId:null,status:'running',step:'policy',attempt:'1',ownerEpoch:j.ownerEpoch,deadline:10000,resultId:null,errorCode:null}));}
function world(filename=':memory:'){
 const initial=bootstrapPolicy({toolchainDigest:d(3),dependencyLockDigest:d(4)}),binding={repositoryId:'r',installationId:'i',provider:'github',providerRepositoryId:'1',remote:'https://github.com/example/repo.git',ref:'refs/heads/dev-2',bindingEpoch:'1',policyDigest:initial.policy.digest};
 const enrollment=structuredClone(binding),ledger=new Ledger(filename,enrollment),value=definition(),bytes=Buffer.from(JSON.stringify(value)),entry={path:'config/policy.json',mode:'100644',blobOid:o(7),contentDigest:bytesDigest(bytes),size:bytes.length};let qualifies=true,reads=0;
 const options={ledger,binding,initial,authorize:async()=>{},verifyIntegrated:async(commit,policyDigest)=>{reads++;return {repositoryId:'r',bindingEpoch:'1',commitOid:commit,policyDigest,validationId:d(9),source:{treeOid:o(2),manifestDigest:sourceManifest([entry]),entries:[entry]}};},readBlob:async()=>bytes,qualify:async()=>qualifies,now:()=>1000};
 const state=new PolicyState(options);return {state,options,ledger,binding,enrollment,initial,value,entry,input:{integratedCommit:o(1),policyPath:entry.path,expectedPolicyDigest:initial.policy.digest,newPolicyDigest:value.digest},principal:{subject:'human',issuer:'test',audience:'test',expiresAt:10000},qualify:v=>qualifies=v,reads:()=>reads};
}

test('qualified policy independently recomputes every profile and policy identity',()=>{const p=definition();assert.equal(qualifiedPolicy(p).policy.digest,p.digest);const changed=structuredClone(p);changed.profiles[0].profile.cpuMillis=32000;assert.throws(()=>qualifiedPolicy(changed),{code:'INTEGRITY_FAILURE'});const missing=structuredClone(p);missing.required=['core'];const {schemaVersion,digest,...body}=missing;missing.digest=recordDigest('dev2.execution-policy.v1',body);assert.throws(()=>qualifiedPolicy(missing));const credential=structuredClone(p);credential.deviceToken='forbidden';assert.throws(()=>qualifiedPolicy(credential),{code:'INVALID_ARGUMENT'});});

test('policy adoption is old-policy validated, durable, idempotent and not automatic on source integration',async()=>{const w=world();try{assert.equal(w.state.current.policy.digest,w.initial.policy.digest);action(w.ledger);const result=await w.state.adopt(w.principal,w.input,'adopt');assert.equal(result.policyDigest,w.value.digest);assert.equal(w.binding.policyDigest,w.value.digest);assert.equal(w.state.retained().validationId,d(9));assert.equal(w.reads(),1);assert.deepEqual(await w.state.adopt(w.principal,w.input,'adopt'),result);assert.equal(w.reads(),1);}finally{w.ledger.close();}});

test('uninstalled capability and cancellation during qualification cannot adopt',async()=>{for(const cancel of [false,true]){const w=world();try{action(w.ledger);w.options.qualify=async()=>{if(cancel)w.ledger.transact(tx=>tx.run('INSERT INTO meta VALUES(?,?)','cancel:adopt','true'));return cancel;};await assert.rejects(()=>w.state.adopt(w.principal,w.input,'adopt'),{code:cancel?'STALE_REVISION':'EXECUTION_UNAVAILABLE'});assert.equal(w.state.retained(),null);assert.equal(w.binding.policyDigest,w.initial.policy.digest);}finally{w.ledger.close();}}});

test('concurrent adoptions use exact old digest CAS and do not silently overwrite each other',async()=>{const w=world();try{action(w.ledger,'a');action(w.ledger,'b');const results=await Promise.allSettled([w.state.adopt(w.principal,w.input,'a'),w.state.adopt(w.principal,w.input,'b')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'STALE_RESULT');}finally{w.ledger.close();}});

test('actual SQLite restart restores the adopted policy without mutating enrollment identity or accepting stale config',async()=>{const dir=await mkdtemp(join(tmpdir(),'dev2-policy-'));let w,again;try{const file=join(dir,'work.sqlite');w=world(file);action(w.ledger);await w.state.adopt(w.principal,w.input,'adopt');w.ledger.close();again=new Ledger(file,w.enrollment);const binding=structuredClone(w.enrollment),state=new PolicyState({...w.options,ledger:again,binding});await state.restore();assert.equal(binding.policyDigest,w.value.digest);assert.equal(state.current.policy.digest,w.value.digest);assert.equal(again.binding.policyDigest,w.value.digest);const denied=new PolicyState({...w.options,ledger:again,binding,qualify:async()=>false});await assert.rejects(()=>denied.restore(),{code:'EXECUTION_UNAVAILABLE'});}finally{if(w&&!w.ledger.closed)w.ledger.close();again?.close();await rm(dir,{recursive:true,force:true});}});
