import test from 'node:test';
import assert from 'node:assert/strict';
import {bytesDigest,recordDigest,canonicalJson} from '../../src/contracts/canonical.mjs';
import {currentControllerReleaseControlPlan,retainedControllerRecommissionPair} from '../../src/release/controller-recommissioning.mjs';
const D=n=>'sha256:'+(n%16).toString(16).repeat(64),C='sha1:'+'a'.repeat(40),T='sha1:'+'b'.repeat(40);
function fixture(){
 const old='/data/data/com.termux/files/home/.local/share/tdev/release-control-old',root='/data/data/com.termux/files/home/.local/share/tdev/release-control-current',fixed=old+'/fixed',release=D(1),artifact=D(2),schema=D(3),install='installation',repo='repository',epoch='3';
 const pair={releaseId:release,sourceCommitOid:C,deviceReleaseId:release,deviceSourceCommitOid:C,deviceArtifactDigest:artifact,edgeSourceCommitOid:C,edgeArtifactDigest:D(4),edgeVersionId:'00000000-0000-4000-8000-000000000001',schemaDigest:schema,protocol:{min:1,max:1},ledger:{min:1,max:1}};
 const pointer={schemaVersion:1,installationId:install,repositoryId:repo,bindingEpoch:epoch,deviceReleaseId:release,artifactDigest:artifact,sourceCommitOid:C,schemaDigest:schema,nativeConfigDigest:D(5)};
 const edge={installationId:install,deviceId:'device',origin:'https://tdev.humtr.workers.dev',issuer:'https://example.cloudflareaccess.com',applicationAudience:'aud',deviceCredentialDigest:D(6),allowedOrigins:['https://chatgpt.com'],binding:{repositoryId:repo,installationId:install,provider:'github',providerRepositoryId:'123',remote:'https://github.com/o/r.git',ref:'refs/heads/dev-2',bindingEpoch:epoch,policyDigest:D(7)},grants:[],applicationCapabilities:[],sourceCommitOid:C,edgeBundleDigest:D(4)};
 const wb=Buffer.from('writer'),rb=Buffer.from('runit'),cb=Buffer.from('common'),hb=Buffer.from('helper');
 const sealBody={schemaVersion:1,kind:'tdev.operator-installed-release-boundary',installationId:install,repositoryId:repo,bindingEpoch:epoch,fixedFiles:{runitConfig:D(11)},serviceRunDigest:D(12)},installationSealDigest=recordDigest('tdev.operator-installed-release-boundary.v1',sealBody),installationSeal={...sealBody,installationSealDigest};
 const config={schemaVersion:1,edge,stateDirectory:'/data/data/com.termux/files/home/.local/share/tdev/installations/i',gitExecutable:'/data/data/com.termux/files/usr/bin/git',githubTokenFile:null,gitAskpassFile:null,deviceKeyFile:'/x/device',cursorKeyFile:'/x/cursor',capacity:8,actor:'tdev <tdev@example.invalid>',runtime:{bundleDigest:artifact,schemaDigest:schema,sourceCommitOid:C,sourceTreeOid:T},toolchain:{executionVariants:[]},policy:{schemaVersion:1,digest:D(7)},managedEnrollmentFile:'/old/managed',productionEnrollmentFile:'/old/production',releaseControl:{helperEndpointFile:old+'/rpc/helper-endpoint.json',helperKeyFile:old+'/rpc/helper.key',nativeEndpointFile:old+'/rpc/native-endpoint.json',nativeKeyFile:old+'/rpc/native.key',installationSealDigest,deviceReleaseId:release},releaseArtifactDirectory:old+'/artifacts'};
 const helper={schemaVersion:1,installationId:install,repositoryId:repo,bindingEpoch:epoch,helperBundleDigest:bytesDigest(hb),installationSealDigest,executor:{sealDigest:D(9),controllerDigest:D(9),workflowDigest:D(9)},baseline:pair,baselinePointer:pointer,baseConfigDigest:pointer.nativeConfigDigest,paths:{journalFile:old+'/activation.json',artifactDirectory:old+'/artifacts',objectDirectory:'/objects',pointerFile:old+'/device-pointer.json',nativeConfigDirectory:old+'/native-configs',baseConfigFile:old+'/native-base.json',helperEndpointFile:old+'/rpc/helper-endpoint.json',helperKeyFile:old+'/rpc/helper.key',nativeEndpointFile:old+'/rpc/native-endpoint.json',nativeKeyFile:old+'/rpc/native.key',writerFenceConfigFile:fixed+'/writer-fence.json',runitConfigFile:fixed+'/runit.json',pythonExecutable:'/data/data/com.termux/files/usr/bin/python',writerFenceHelperFile:fixed+'/release-writer-fence.py',runitHelperFile:fixed+'/release-runit-control.py',commonModuleFile:fixed+'/release_native.py',cloudflareTokenFile:old+'/cloudflare-token'},fixedFiles:{writerFenceHelper:bytesDigest(wb),runitHelper:bytesDigest(rb),commonModule:bytesDigest(cb),writerFenceConfig:D(10),runitConfig:D(11)},environment:{PATH:'/data/data/com.termux/files/usr/bin',HOME:old+'/home',TMPDIR:old+'/tmp',LANG:'C.UTF-8',PREFIX:'/data/data/com.termux/files/usr'},cloudflare:{accountId:'1'.repeat(32),workerName:'tdev',routerNamespaceId:'2'.repeat(32),edgeConfig:edge}};
 const runit={schemaVersion:1,installationId:install,repositoryId:repo,bindingEpoch:epoch,pointerFile:old+'/device-pointer.json',serviceDirectory:'/data/data/com.termux/files/usr/var/service/tdev',serviceRunDigest:D(12),stateDirectory:old+'/runit-effects'};
 const writer={schemaVersion:1,installationId:install,repositoryId:repo,bindingEpoch:epoch,pointerFile:old+'/device-pointer.json',launcherLockFile:old+'/launcher.lock',artifactDirectory:old+'/artifacts',nativeConfigDirectory:old+'/native-configs',requestDirectory:old+'/writer-effects',ledgerFile:'/ledger',senderStateDirectory:'/senders',serviceStatusFile:'/data/data/com.termux/files/usr/var/service/tdev/supervise/status'};
 const identities={trustedRunnerDigest:D(13),workflowDigest:D(14),controllerDigest:D(13)},managed={approvedCommitOid:C,sealDigest:D(15)},intent={approvedCommitOid:C,qualificationSealDigest:managed.sealDigest,runtime:config.runtime,identities},body={schemaVersion:1,kind:'tdev.production-enrollment',intent,proofs:[]},production={...body,sealDigest:recordDigest('tdev.production-enrollment.v1',body)};
 return {root,pair,pointer,config,helper,runit,writer,installationSeal,managed,production,hb,wb,rb,cb};
}
test('current controller recommission rebases release control without rewriting installation identity',()=>{
 const f=fixture(),p=currentControllerReleaseControlPlan({newRoot:f.root,managedEnrollmentFile:'/private/managed-current.json',productionEnrollmentFile:'/private/production-current.json',oldHelper:f.helper,oldRunit:f.runit,oldWriter:f.writer,installationSeal:f.installationSeal,activePair:f.pair,activePointer:f.pointer,activeConfig:f.config,managedEnrollment:f.managed,productionEnrollment:f.production,helperBundleBytes:f.hb,writerFenceHelperBytes:f.wb,runitHelperBytes:f.rb,commonModuleBytes:f.cb,launcherBytes:Buffer.from('launcher'),nodeExecutable:'/data/data/com.termux/files/usr/bin/node',nodeDigest:D(16),helperServiceDirectory:'/data/data/com.termux/files/usr/var/service/tdev-release-helper',previousLauncherCommissioningSealDigest:D(17)});
 assert.equal(p.helper.installationId,f.helper.installationId);assert.equal(p.helper.bindingEpoch,f.helper.bindingEpoch);assert.equal(p.helper.baseline.deviceReleaseId,f.pointer.deviceReleaseId);assert.equal(p.baseConfig.managedEnrollmentFile,'/private/managed-current.json');assert.equal(p.baseConfig.productionEnrollmentFile,'/private/production-current.json');assert.equal(p.baselinePointer.nativeConfigDigest,p.baseConfigDigest);assert.match(p.launcher.serviceRun,/release-device-launcher\.py/);assert.equal(p.helper.executor.sealDigest,f.production.sealDigest);assert.equal(p.recommissionSeal.productionEnrollmentSealDigest,f.production.sealDigest);assert.ok(p.planDigest.startsWith('sha256:'));assert.equal(canonicalJson(f.config.runtime),canonicalJson(p.baseConfig.runtime));
});

test('stopped recommission accepts only the durable terminal pair',()=>{
 const f=fixture(),previous={...f.pair,edgeVersionId:'00000000-0000-4000-8000-000000000002'},terminal={phase:'active',intent:{previous,target:f.pair},observedPair:f.pair};
 assert.deepEqual(retainedControllerRecommissionPair(f.helper.baseline,null),f.pair);
 assert.deepEqual(retainedControllerRecommissionPair(f.helper.baseline,terminal),f.pair);
 assert.throws(()=>retainedControllerRecommissionPair(f.helper.baseline,{...terminal,observedPair:previous}),error=>error?.code==='INTEGRITY_FAILURE');
});
