import test from 'node:test';
import assert from 'node:assert/strict';
import {F3_SCOPE,researchBinding,buildResearchSenderConfig,wrapperSource,classifyReadback} from '../../bench/f3-hosted-harness.mjs';
const binding={installationId:'i',repositoryId:'github-1322208918',providerRepositoryId:'1322208918',bindingEpoch:'1',provider:'github',remote:'https://github.com/humtr/tdev.git',ref:'refs/heads/dev-2',policyDigest:'sha256:'+'a'.repeat(64)};

test('F3 one-shot scope cannot target canonical or managed-exec refs',()=>{const value=researchBinding(binding);assert.equal(value.ref,'refs/heads/research/f3-20260914-a2');assert.notEqual(value.ref,binding.ref);assert.ok(!value.ref.startsWith('refs/heads/dev2-exec/'));assert.throws(()=>researchBinding({...binding,repositoryId:'other'}),{code:'FORBIDDEN'});});

test('research sender config pins repository/ref and uses only the fixed barrier wrapper',()=>{const canonical={schemaVersion:1,stateDirectory:'/private/canonical',repositoryId:F3_SCOPE.repositoryId,bindingEpoch:'1',ref:F3_SCOPE.canonicalRef,provider:'github',remote:F3_SCOPE.remote,gitExecutable:'/bin/git',repositoryDirectory:'/private/repo.git',environment:{PATH:'/bin'}};const value=buildResearchSenderConfig(canonical,'/private/f3','/private/f3/git-wrapper.py');assert.equal(value.ref,F3_SCOPE.ref);assert.equal(value.remote,F3_SCOPE.remote);assert.equal(value.gitExecutable,'/private/f3/git-wrapper.py');assert.equal(value.environment.DEV2_F3_REAL_GIT,'/bin/git');assert.equal(value.environment.DEV2_F3_BARRIER,'/private/f3/sender-entered.json');assert.equal(value.environment.DEV2_F3_RELEASE,'/private/f3/sender-release');});

test('wrapper holds only push before provider send and then execs the fixed real git',()=>{const source=wrapperSource('/usr/bin/python3');assert.match(source,/if 'push' in args/);assert.match(source,/held-before-provider-send/);assert.match(source,/os\.execv\(real/);assert.ok(!source.includes('refs/heads/dev-2'));});

test('authoritative readback keeps exact C, descendant, H-uncertain, H-stopped, competing and foreign distinct',()=>{const H='sha1:'+'1'.repeat(40),C='sha1:'+'2'.repeat(40),D='sha1:'+'3'.repeat(40);assert.deepEqual(classifyReadback({available:true,head:C,expectedHead:H,commitOid:C,senderStopped:false}),{kind:'integrated',relation:'commit_or_descendant'});assert.deepEqual(classifyReadback({available:true,head:D,expectedHead:H,commitOid:C,senderStopped:false,commitAncestor:true,expectedAncestor:true}),{kind:'integrated',relation:'commit_or_descendant'});assert.deepEqual(classifyReadback({available:true,head:H,expectedHead:H,commitOid:C,senderStopped:false}),{kind:'uncertain',relation:'expected_head'});assert.deepEqual(classifyReadback({available:true,head:H,expectedHead:H,commitOid:C,senderStopped:true}),{kind:'retryable',relation:'expected_head'});assert.deepEqual(classifyReadback({available:true,head:D,expectedHead:H,commitOid:C,senderStopped:true,commitAncestor:false,expectedAncestor:true}),{kind:'stale',relation:'other_expected_descendant'});assert.deepEqual(classifyReadback({available:true,head:D,expectedHead:H,commitOid:C,senderStopped:true,commitAncestor:false,expectedAncestor:false}),{kind:'binding_fenced',relation:'foreign'});assert.deepEqual(classifyReadback({available:false,expectedHead:H,commitOid:C,senderStopped:false}),{kind:'unknown',relation:null});});
