import test from 'node:test';
import assert from 'node:assert/strict';
import {sourceManifest} from '../../src/repository/entries.mjs';
import {h2Delta,requireH2Disjoint,composeH2Entries,h2MemberTuple,h2Composition,h2ResultId,h2EffectId,h2CommitMetadata} from '../../src/integration/h2-identity.mjs';
const D='sha256:'+'1'.repeat(64),V='sha256:'+'2'.repeat(64),O='sha1:'+'3'.repeat(40);
function source(entries,treeOid=O){return {treeOid,entries,manifestDigest:sourceManifest(entries)};}
function common(){return {repositoryId:'repo',provider:'github',providerRepositoryId:'1',installationId:'installation',bindingEpoch:'1',ref:'refs/heads/dev-2',expectedHead:O,baseTreeOid:O,baseManifestDigest:source([]).manifestDigest,policyDigest:D,execution:{orderedProfileDigests:[D,V],trustedRunnerDigest:D,toolchainDigest:D,environmentClass:'fixture',dependencyLockDigest:D}};}
function member(i){return {workId:'w'+String(i).padStart(2,'0'),actionId:'a'+String(i).padStart(2,'0'),principal:'principal',requestId:'r'+i,intentDigest:D,generation:'0',reservedWorkRevision:'2',candidateTreeOid:O,candidateManifestDigest:D,memberResultId:'result'+i,memberValidationId:V,memberReceiptRunId:'run'+i,memberReceiptDigest:D,changedPathDigest:V};}
for(const n of [2,8,16,32])test('H2 deterministic identities are permutation and retry-order invariant at N='+n,()=>{const members=Array.from({length:n},(_,i)=>member(i));const a=h2MemberTuple(common(),members),b=h2MemberTuple(common(),members.toReversed());assert.equal(a.memberTupleDigest,b.memberTupleDigest);assert.deepEqual(a.tuple,b.tuple);const tree={treeOid:O,manifestDigest:V},k=h2Composition(a.memberTupleDigest,tree);assert.equal(k,h2Composition(b.memberTupleDigest,tree));const r=h2ResultId(k);assert.match(r,/^[0-9a-f]{64}$/);const effect={memberTupleDigest:a.memberTupleDigest,compositionIdentity:k,repositoryId:'repo',bindingEpoch:'1',ref:'refs/heads/dev-2',expectedHead:O,commitOid:O,resultTreeOid:O,resultTreeSha256:V,preparedResultId:r,validationId:V,policyDigest:D};assert.equal(h2EffectId(effect),h2EffectId({...effect}));assert.match(h2EffectId(effect),/^[0-9a-f]{64}$/);});
test('H2 rejects duplicate members before identity freeze',()=>{const members=[member(0),member(1)];assert.throws(()=>h2MemberTuple(common(),[...members,{...members[1]}]),{code:'INTEGRITY_FAILURE'});assert.throws(()=>h2MemberTuple(common(),[members[0],{...members[1],workId:members[0].workId}]),{code:'INTEGRITY_FAILURE'});});
test('exact delta union preserves base entries, put/delete/mode semantics and rejects cross-member path topology collisions',()=>{const base=source([{path:'keep',mode:'100644',blobOid:O,contentDigest:D,size:1},{path:'delete',mode:'100644',blobOid:O,contentDigest:D,size:1}]);const a=source([{path:'keep',mode:'100644',blobOid:O,contentDigest:D,size:1},{path:'delete',mode:'100755',blobOid:O,contentDigest:V,size:1}]),b=source([{path:'keep',mode:'100644',blobOid:O,contentDigest:D,size:1},{path:'delete',mode:'100644',blobOid:O,contentDigest:D,size:1},{path:'new',mode:'100644',blobOid:O,contentDigest:V,size:1}]);const da=h2Delta(base,a),db=h2Delta(base,b);requireH2Disjoint([da,db]);const entries=composeH2Entries(base,[da,db]);assert.equal(entries.find(e=>e.path==='keep').contentDigest,D);assert.equal(entries.find(e=>e.path==='delete').mode,'100755');assert.equal(entries.find(e=>e.path==='new').contentDigest,V);const empty=source([]),file=h2Delta(empty,source([{path:'dir',mode:'100644',blobOid:O,contentDigest:D,size:1}])),child=h2Delta(empty,source([{path:'dir/file',mode:'100644',blobOid:O,contentDigest:V,size:1}]));assert.throws(()=>requireH2Disjoint([file,child]),{code:'ENTRY_CONFLICT'});});
test('H2 commit metadata is deterministic and uses the maximum retained member timestamp',()=>{const metadata=h2CommitMetadata('Actor <actor@example.invalid>',[{metadata:{timestamp:9}},{metadata:{timestamp:3}},{metadata:{timestamp:7}}]);assert.deepEqual(metadata,{author:'Actor <actor@example.invalid>',committer:'Actor <actor@example.invalid>',timestamp:9,message:'tdev composed source change'});});
