import test from 'node:test';import assert from 'node:assert/strict';
import {recordDigest} from '../../src/contracts/canonical.mjs';
import {managedPolicy} from '../../src/validation/managed-policy.mjs';
import {enrollmentRecord,verifyEnrollment} from '../../src/runtime/enrollment.mjs';
const D='sha256:'+'1'.repeat(64),C='2'.repeat(40),N='3'.repeat(40),T='sha1:'+'4'.repeat(40),runId='99';
function fixture(){
 const identities={trustedRunnerDigest:D,controllerDigest:D,toolchainDigest:D,dependencyLockDigest:D,workflowDigest:D,imageDigest:D,seccompDigest:D},policy=managedPolicy(identities),definition={identities,config:{image:'docker.io/library/node@'+D},policy},source={treeOid:T,manifestDigest:D,entries:[]};
 const binding={installationId:'installation',repositoryId:'repository',bindingEpoch:'1',providerRepositoryId:'123',remote:'https://owner.invalid/unused'},ref='refs/heads/dev2-containment/qualification';binding.remote='https://github.com/owner/repo.git';
 const provider={id:99,repository:{id:123,full_name:'owner/repo',owner:{id:456}},head_sha:C,event:'push',path:'.github/workflows/dev2-containment-proof.yml',status:'completed',conclusion:'success',run_attempt:1,head_branch:ref.slice(11)};
 const marker=recordDigest('dev2.qualification-only-assignment.v1',{sourceCommit:C,controller:D,runId});
 const controller={kind:'real-managed-controller-qualification',schemaVersion:1,status:'passed',sourceCommit:C,sourceTree:T,sourceManifest:D,runId,runAttempt:'1',productionValidation:false,productionSeal:false,nativeAssignmentVerified:false,identities,qualificationIdentity:marker,dependencyArtifactIdentity:D,profiles:policy.required().map(p=>({profileId:p.profileId,profileDigest:p.digest,factories:1,launches:1,deliveries:2,exactResponseLossReplay:true,assignmentId:p.profileId,result:{assignmentId:p.profileId,sealDigest:marker,trustedRunnerDigest:D,exitCode:0,signal:null,deadlineExceeded:false,stopped:true,inputDigest:D,outputDigest:D}}))};
 const names=['hostFiles','credentials','procCredentials','nonRoot','noNewPrivileges','noCapabilities','seccomp','sourceReadOnly','rootReadOnly','memoryLimit','pidLimit','cpuLimit','hostLoopback','egress','diskLimit','pidAdmission'];
 const containment={kind:'real-hosted-containment-qualification',schemaVersion:1,status:'passed',productionSeal:false,sourceCommit:C,runId,runAttempt:'1',image:definition.config.image,seccompDigest:D,containmentExit:0,oidc:{signatureVerified:true,nativeAssignmentVerified:false,audience:'https://tdev.humtr.workers.dev/executor',repositoryId:'123',ownerId:'456',sha:C,workflowSha:C,ref,workflowRef:'owner/repo/.github/workflows/dev2-containment-proof.yml@'+ref,runId,runAttempt:'1'},containment:JSON.stringify({checks:Object.fromEntries(names.map(n=>[n,true]))}),memory:{beforeEvents:{oom_kill:0},lastEvents:{oom_kill:1}},duplicateLaunch:{sameContainer:true,materializations:1},deadline:{exitCode:124,elapsedMs:3000},cancellation:{state:'exited',repeatedState:'exited'}};
 const body={schemaVersion:1,kind:'dev2-managed-enrollment',installationId:'installation',repositoryId:'repository',bindingEpoch:'1',repositoryOwnerId:'456',repositoryFullName:'owner/repo',approvedCommitOid:'sha1:'+C,approvedSourceManifestDigest:D,identities,qualification:{providerRunJson:JSON.stringify(provider),controllerReportJson:JSON.stringify(controller),containmentReportJson:JSON.stringify(containment)},nativeJoin:{sourceCommitOid:'sha1:'+N,sourceTreeOid:T,inputDigest:D,coreStatus:'passed',integrationStatus:'passed',productionValidation:false},canonicalRuleset:{rulesetId:8,createdAt:'2026-09-12T00:00:00Z',updatedAt:'2026-09-12T00:00:00Z'}};
 return {body,controller,containment,provider,expected:{binding,definition,source,runtime:{sourceCommitOid:'sha1:'+N,sourceTreeOid:T},origin:'https://tdev.humtr.workers.dev'}};
}
test('private commissioning binds exact native source and qualified controller without relabeling qualification as production',()=>{const f=fixture(),e=enrollmentRecord(f.body),verified=verifyEnrollment(e,f.expected);assert.equal(verified.sealDigest,e.sealDigest);assert.equal(verified.policy.policy.digest,f.expected.definition.policy.policy.digest);assert.equal(verified.qualificationRunId,'99');assert.equal(JSON.parse(e.qualification.controllerReportJson).productionValidation,false);});
test('tampered private fields, another native tree and extra enrollment privileges are rejected',()=>{const f=fixture(),e=enrollmentRecord(f.body);for(const mutate of [x=>x.identities.trustedRunnerDigest='sha256:'+'9'.repeat(64),x=>x.repositoryOwnerId='8',x=>x.nativeJoin.coreStatus='failed',x=>x.unchecked=true]){const copy=structuredClone(e);mutate(copy);assert.throws(()=>verifyEnrollment(copy,f.expected));}assert.throws(()=>verifyEnrollment(e,{...f.expected,runtime:{...f.expected.runtime,sourceTreeOid:'sha1:'+'9'.repeat(40)}}));});
test('freshly hashed but false qualification cannot gain a production seal from a passing fixture or provider run',()=>{
 const changes=[f=>f.provider.conclusion='failure',f=>f.provider.run_attempt=2,f=>f.provider.repository.owner.id=9,f=>f.controller.productionValidation=true,f=>f.controller.nativeAssignmentVerified=true,f=>f.controller.profiles[0].launches=2,f=>f.controller.profiles[1].result.exitCode=1,f=>f.controller.profiles[0].result.outputDigest='sha256:'+'9'.repeat(64),f=>f.containment.memory.lastEvents.oom_kill=0,f=>f.containment.oidc.signatureVerified=false,f=>f.containment.containment=JSON.stringify({checks:{}}),f=>f.containment.duplicateLaunch.materializations=2];
 for(const mutate of changes){const f=fixture();mutate(f);f.body.qualification={providerRunJson:JSON.stringify(f.provider),controllerReportJson:JSON.stringify(f.controller),containmentReportJson:JSON.stringify(f.containment)};assert.throws(()=>verifyEnrollment(enrollmentRecord(f.body),f.expected));}
});
