import test from 'node:test';
import assert from 'node:assert/strict';
import {PodmanSandbox,attemptName} from '../../src/execution/podman.mjs';
const attempt={installationId:'i',repositoryId:'r',workId:'w',actionId:'a',attemptId:'attempt',attempt:'1',ownerEpoch:'1'};
const D='sha256:'+'1'.repeat(64);
const state={Status:'exited',Running:false,ExitCode:-1,Pid:0,StartedAt:'2026-09-12T00:14:55.546843671Z',FinishedAt:'2026-09-12T00:14:57.8067139Z'};
function sandbox(State,labels={}){return new PodmanSandbox({command:async(_exe,args)=>({exitCode:0,signal:null,timedOut:false,spawnFailed:false,discardedBytes:0,stdout:Buffer.from(args[0]==='inspect'?JSON.stringify([{Config:{Labels:{'dev2.attempt':attemptName(attempt),'dev2.profile':D,'dev2.source':D,...labels}},State}]):''),stderr:Buffer.alloc(0)}),executable:'/usr/bin/podman',environment:{},attemptRoot:'/fixture',seccompPath:'/fixture/seccomp',seccompDigest:D,images:{},productionSeal:true,materialize:async()=>{throw Error('no launch');}});}
test('real hosted timeout sentinel is positive stop evidence, never a successful exit status',async()=>{const s=sandbox(state),result=await s.inspect(attempt,{profileDigest:D,sourceManifest:D});assert.equal(result.state,'exited');assert.equal(result.exitCode,null);assert.equal(result.signal,null);assert.equal((await s.cancel(attempt)).state,'exited');});
test('sentinel without exact terminal/PID/timestamp evidence remains uncertain',async()=>{for(const patch of [{Status:'created'},{Status:'stopped'},{Pid:1},{Pid:undefined},{StartedAt:'0001-01-01T00:00:00Z'},{FinishedAt:'0001-01-01T00:00:00Z'},{FinishedAt:'bad'},{ExitCode:-2}])assert.equal((await sandbox({...state,...patch}).inspect(attempt)).state,'uncertain');assert.equal((await sandbox({...state,Running:true}).inspect(attempt)).state,'running');});
test('sentinel cannot bypass attempt or input identity checks',async()=>{for(const labels of [{'dev2.attempt':'wrong'},{'dev2.profile':'wrong'},{'dev2.source':'wrong'}])await assert.rejects(sandbox(state,labels).inspect(attempt,{profileDigest:D,sourceManifest:D}),{code:'INTEGRITY_FAILURE'});});
test('ordinary successful and failed exit codes preserve their exact values',async()=>{for(const exitCode of [0,1,137,255]){const r=await sandbox({...state,ExitCode:exitCode}).inspect(attempt);assert.equal(r.state,'exited');assert.equal(r.exitCode,exitCode);}for(const exitCode of [256,1.5])assert.equal((await sandbox({...state,ExitCode:exitCode}).inspect(attempt)).state,'uncertain');});
