import {canonicalJson,parseRecord,recordDigest,bytesDigest} from '../contracts/canonical.mjs';
import {digest,id} from '../contracts/identity.mjs';
import {requireThat} from '../contracts/errors.mjs';
import {physicalAttempt,executionIdentity} from './payload.mjs';
import {attemptName} from './podman.mjs';
/** @typedef {import('../contracts/ports.js').PreparedResult} Prepared */
/** @typedef {import('../contracts/ports.js').Attempt} Attempt */
/** @typedef {import('../contracts/ports.js').Profile} Profile */
/** @typedef {import('./session-types.js').Assignment} Assignment */
/** @typedef {import('./session-types.js').Session} Session */
/** @typedef {import('./session-types.js').ExecutionResult} Result */
/** @typedef {{container:string,pid:number,cgroup:string,observedAt:number,memoryEvents:Record<string,number>,limits:{memoryBytes:number,pids:number,cpuQuota:number,cpuPeriod:number}}} Kernel */
/** @typedef {{rootReadOnly:boolean,sourceReadOnly:boolean,controllerReadOnly:boolean,dependenciesReadOnly:boolean,noNewPrivileges:boolean,noCapabilities:boolean,seccomp:boolean,nonRoot:boolean,privateNamespaces:boolean,networkNone:boolean,finiteStorage:boolean,cleanEnvironment:boolean,engineDigest:string,seccompDigest:string,imageDigest:string,controllerDigest:string,dependencyArtifactDigest:string}} Isolation */
/** @typedef {{name:'log'|'device.cjs'|'worker.mjs'|'tools.json',digest:string,size:number}} Output */
/** @typedef {{schemaVersion:1,kind:'dev2-production-execution',assignmentId:string,leaseId:string,inputIdentity:string,sessionId:string,runId:string,sealDigest:string,trustedRunnerDigest:string,profileDigest:string,container:string,startedAt:number,endedAt:number,command:{argvDigest:string,exitCode:number|null,signal:string|null,timedOut:boolean,spawnFailed:boolean,discardedBytes:number},before:Kernel|null,after:Kernel|null,isolation:Isolation|null,stopped:true,inputDigest:string,outputDigest:string,outputs:Output[]}} OuterReceipt */
/** @typedef {{schemaVersion:1,contextDigest:string,outerReceiptDigest:string,assignmentId:string,inputIdentity:string,sessionId:string,providerRunId:string,providerRunAttempt:'1',profileDigest:string,sealDigest:string,eligible:boolean}} ProductionProof */
const CHECKS=Object.freeze(['rootReadOnly','sourceReadOnly','controllerReadOnly','dependenciesReadOnly','noNewPrivileges','noCapabilities','seccomp','nonRoot','privateNamespaces','networkNone','finiteStorage','cleanEnvironment']);
/** Strict receipt decoding is not authentication. Authentication comes from the
 * retained selected OIDC assignment and its immutable uploaded object capability.
 * @param {unknown} value @param {readonly string[]} keys */
function closed(value,keys){requireThat(value!==null&&typeof value==='object'&&!Array.isArray(value)&&canonicalJson(Object.keys(value).sort())===canonicalJson([...keys].sort()),'INTEGRITY_FAILURE','Malformed production receipt');}
/** @param {unknown} n */
function natural(n){requireThat(typeof n==='number'&&Number.isSafeInteger(n)&&n>=0,'INTEGRITY_FAILURE','Invalid production evidence integer');}
/** @param {Kernel|null} k */
function kernel(k){if(k===null)return;closed(k,['container','pid','cgroup','observedAt','memoryEvents','limits']);id(k.container);natural(k.pid);natural(k.observedAt);requireThat(k.pid>0&&typeof k.cgroup==='string'&&k.cgroup.startsWith('/')&&!k.cgroup.split('/').includes('..')&&!/[\0\r\n]/.test(k.cgroup),'INTEGRITY_FAILURE');closed(k.limits,['memoryBytes','pids','cpuQuota','cpuPeriod']);for(const n of Object.values(k.limits)){natural(n);requireThat(n>0,'INTEGRITY_FAILURE');}requireThat(k.memoryEvents&&typeof k.memoryEvents==='object'&&!Array.isArray(k.memoryEvents)&&Object.keys(k.memoryEvents).length<=32,'INTEGRITY_FAILURE');for(const [key,value] of Object.entries(k.memoryEvents)){requireThat(/^[a-z_]+$/.test(key),'INTEGRITY_FAILURE');natural(value);}for(const key of ['oom','oom_kill'])natural(k.memoryEvents[key]);}
/** @param {Uint8Array} bytes @returns {OuterReceipt} */
export function decodeOuterReceipt(bytes){requireThat(bytes.byteLength<=65536,'LIMIT_EXCEEDED');const r=/** @type {OuterReceipt} */(/** @type {unknown} */(parseRecord(bytes,65536)));closed(r,['schemaVersion','kind','assignmentId','leaseId','inputIdentity','sessionId','runId','sealDigest','trustedRunnerDigest','profileDigest','container','startedAt','endedAt','command','before','after','isolation','stopped','inputDigest','outputDigest','outputs']);requireThat(r.schemaVersion===1&&r.kind==='dev2-production-execution'&&r.stopped===true,'INTEGRITY_FAILURE');for(const v of [r.assignmentId,r.leaseId,r.sessionId,r.runId,r.container])id(v);for(const v of [r.inputIdentity,r.sealDigest,r.trustedRunnerDigest,r.profileDigest,r.inputDigest,r.outputDigest])digest(v);natural(r.startedAt);natural(r.endedAt);requireThat(r.endedAt>=r.startedAt,'INTEGRITY_FAILURE');closed(r.command,['argvDigest','exitCode','signal','timedOut','spawnFailed','discardedBytes']);digest(r.command.argvDigest);if(r.command.exitCode!==null){natural(r.command.exitCode);requireThat(r.command.exitCode<=255,'INTEGRITY_FAILURE');}requireThat(r.command.signal===null||typeof r.command.signal==='string'&&/^SIG[A-Z0-9]{1,16}$/.test(r.command.signal),'INTEGRITY_FAILURE');requireThat(typeof r.command.timedOut==='boolean'&&typeof r.command.spawnFailed==='boolean','INTEGRITY_FAILURE');natural(r.command.discardedBytes);kernel(r.before);kernel(r.after);
 if(r.isolation!==null){closed(r.isolation,[...CHECKS,'engineDigest','seccompDigest','imageDigest','controllerDigest','dependencyArtifactDigest']);for(const name of CHECKS)requireThat(typeof r.isolation[/** @type {keyof Isolation} */(name)]==='boolean','INTEGRITY_FAILURE');for(const name of ['engineDigest','seccompDigest','imageDigest','controllerDigest','dependencyArtifactDigest'])digest(r.isolation[/** @type {'engineDigest'} */(name)]);}
 requireThat(Array.isArray(r.outputs)&&r.outputs.length<=4&&new Set(r.outputs.map(o=>o.name)).size===r.outputs.length&&new Set(r.outputs.map(o=>o.digest)).size===r.outputs.length,'INTEGRITY_FAILURE');for(const o of r.outputs){closed(o,['name','digest','size']);requireThat(['log','device.cjs','worker.mjs','tools.json'].includes(o.name),'INTEGRITY_FAILURE');digest(o.digest);natural(o.size);requireThat(o.size<=16777216,'LIMIT_EXCEEDED');}return r;
}
/** OOMKilled/exit137/stdout are deliberately not consulted. A same cgroup's
 * kernel counters must be observed around the command and before verified stop.
 * @param {OuterReceipt} r @param {Profile} p */
export function kernelEligible(r,p){const a=r.before,b=r.after;if(!a||!b||!r.isolation)return false;return a.container===r.container&&b.container===r.container&&a.pid===b.pid&&a.cgroup===b.cgroup&&r.startedAt<=a.observedAt&&a.observedAt<=b.observedAt&&b.observedAt<=r.endedAt&&canonicalJson(a.limits)===canonicalJson(b.limits)&&a.limits.memoryBytes===p.memoryBytes&&a.limits.pids===p.pids&&a.limits.cpuQuota*1000===p.cpuMillis*a.limits.cpuPeriod&&a.memoryEvents.oom===b.memoryEvents.oom&&a.memoryEvents.oom_kill===b.memoryEvents.oom_kill&&CHECKS.every(name=>r.isolation?.[/** @type {keyof Isolation} */(name)]===true)&&r.isolation.imageDigest===p.imageDigest;}
/** Full retained identity, not an untrusted source-supplied proof selector.
 * The prepared result includes work/generation/base/commit/tree/policy/execution;
 * the attempt includes installation/action/attempt/owner epoch. Session includes
 * immutable binding epoch, provider repository/owner/workflow and selected run.
 * @param {Prepared} result @param {Attempt} attempt @param {Assignment} a @param {Session} s */
export function productionContext(result,attempt,a,s){return recordDigest('dev2.production-context.v1',{result,attempt,assignmentId:a.assignmentId,inputIdentity:a.inputIdentity,leaseId:a.leaseId,sealDigest:a.sealDigest,sessionIntent:s.intent,sessionIntentDigest:s.intentDigest,providerRun:{runId:s.run?.runId??null,runAttempt:s.run?.runAttempt??null}});}
/** Native join of an authenticated completed assignment. Expected enforcement
 * identities come from the approved private enrollment, never from this receipt.
 * @param {{result:Prepared,attempt:Attempt,profile:Profile,assignment:Assignment,session:Session,execution:Result,outer:OuterReceipt,outerDigest:string,installationId:string,bindingEpoch:string,seccompDigest:string,controllerDigest:string,engineDigest:string,dependencyArtifactDigest:string}} o @returns {ProductionProof} */
export function joinProductionReceipt(o){const {result:r,attempt:t,profile:p,assignment:a,session:s,execution:e,outer:x}=o;for(const v of [o.outerDigest,o.seccompDigest,o.controllerDigest,o.engineDigest,o.dependencyArtifactDigest])digest(v);requireThat(o.outerDigest===bytesDigest(Buffer.from(canonicalJson(x))),'INTEGRITY_FAILURE','Noncanonical outer receipt');decodeOuterReceipt(Buffer.from(canonicalJson(x)));
 requireThat(a.state==='complete'&&a.result&&canonicalJson(a.result)===canonicalJson(e)&&a.inputIdentity===recordDigest('dev2.managed-assignment-input.v1',a.input)&&a.assignmentId===recordDigest('dev2.managed-assignment.v1',{attempt:t,profileDigest:p.digest}).slice(7)&&canonicalJson(a.input.attempt)===canonicalJson(t),'INTEGRITY_FAILURE','Unjoined execution assignment');
 requireThat(s.run&&s.run.runAttempt==='1'&&s.run.runId===a.runId&&s.intent.sessionId===a.sessionId&&s.intentDigest===recordDigest('dev2.managed-session.v1',s.intent)&&s.intent.installationId===o.installationId&&t.installationId===o.installationId&&s.intent.bindingEpoch===o.bindingEpoch&&r.bindingEpoch===o.bindingEpoch&&s.intent.repositoryId===r.repositoryId&&t.repositoryId===r.repositoryId&&t.workId===r.workId&&a.input.resultId===r.resultId&&a.input.sourceManifest===r.resultTreeSha256&&a.input.executionDigest===executionIdentity(r.execution)&&a.input.profileDigest===p.digest,'INTEGRITY_FAILURE','Unjoined result/provider binding');
 requireThat(x.assignmentId===a.assignmentId&&x.leaseId===a.leaseId&&x.inputIdentity===a.inputIdentity&&x.sessionId===a.sessionId&&x.runId===a.runId&&x.sealDigest===a.sealDigest&&x.trustedRunnerDigest===s.intent.trustedRunnerDigest&&x.trustedRunnerDigest===r.execution.trustedRunnerDigest&&x.profileDigest===p.digest&&x.container===attemptName(physicalAttempt(a))&&x.command.argvDigest===recordDigest('dev2.executed-argv.v1',p.argv),'INTEGRITY_FAILURE','Outer identity differs');
 requireThat(e.assignmentId===a.assignmentId&&e.leaseId===a.leaseId&&e.inputIdentity===a.inputIdentity&&e.sealDigest===a.sealDigest&&e.trustedRunnerDigest===x.trustedRunnerDigest&&e.stopped===true&&e.startedAt===x.startedAt&&e.endedAt===x.endedAt&&e.inputDigest===x.inputDigest&&e.outputDigest===x.outputDigest&&e.artifacts.length===x.outputs.length+1&&e.artifacts[e.artifacts.length-1]===o.outerDigest&&canonicalJson(e.artifacts.slice(0,-1))===canonicalJson(x.outputs.map(v=>v.digest)),'INTEGRITY_FAILURE','Outer result/artifact binding differs');
 requireThat(x.isolation===null||x.isolation.seccompDigest===o.seccompDigest&&x.isolation.controllerDigest===o.controllerDigest&&x.isolation.engineDigest===o.engineDigest&&x.isolation.dependencyArtifactDigest===o.dependencyArtifactDigest,'INTEGRITY_FAILURE','Unapproved enforcement/controller/dependency bytes');
 const names=x.outputs.filter(v=>v.name!=='log').map(v=>v.name).sort(),required=p.profileId==='release-build'?['device.cjs','tools.json','worker.mjs']:[];
 const eligible=kernelEligible(x,p)&&x.command.exitCode===0&&x.command.signal===null&&!x.command.timedOut&&!x.command.spawnFailed&&x.command.discardedBytes===0&&e.exitCode===0&&e.signal===null&&!e.deadlineExceeded&&!a.cancelRequested&&!s.cancelRequested&&x.endedAt<=a.input.deadline&&x.endedAt-x.startedAt<=p.timeoutMs&&x.inputDigest===r.resultTreeSha256&&x.outputDigest===r.resultTreeSha256&&canonicalJson(names)===canonicalJson(required);
 return {schemaVersion:1,contextDigest:productionContext(r,t,a,s),outerReceiptDigest:o.outerDigest,assignmentId:a.assignmentId,inputIdentity:a.inputIdentity,sessionId:a.sessionId,providerRunId:a.runId,providerRunAttempt:'1',profileDigest:p.digest,sealDigest:a.sealDigest,eligible};
}
/** Authenticated native ownership, exact ready object bytes, then a fresh owner
 * recheck after asynchronous reads. Objects and qualification records alone never
 * supply production authority. Stale work/result/provider bindings fail closed.
 */
export class ProductionReceipts {
 /** @param {{sessions:import('./sessions.mjs').ManagedSessions,objects:import('../contracts/ports.js').ObjectStorePort,seccompDigest:string,controllerDigest:string,engineDigest:string,dependencyArtifactDigest:string}} options */
 constructor(options){this.o=options;}
 /** @param {Prepared} result @param {Attempt} attempt @param {Profile} profile @param {Result} execution */
 async verify(result,attempt,profile,execution){const id=recordDigest('dev2.managed-assignment.v1',{attempt,profileDigest:profile.digest}).slice(7),{sessions,objects,...enforcement}=this.o;
  const frame=()=>sessions.ledger.transact(tx=>{const a=sessions.assignment(tx,id);return {assignment:a,session:sessions.session(tx,a.sessionId)};});requireThat(execution.artifacts.length>0,'VALIDATION_FAILED','Production outer receipt is missing');const outerDigest=execution.artifacts[execution.artifacts.length-1],bytes=await objects.get(outerDigest);requireThat(bytesDigest(bytes)===outerDigest,'INTEGRITY_FAILURE');const outer=decodeOuterReceipt(bytes),options={result,attempt,profile,execution,outer,outerDigest,installationId:sessions.ledger.binding.installationId,bindingEpoch:sessions.ledger.binding.bindingEpoch,...enforcement};
  joinProductionReceipt({...options,...frame()});for(const output of outer.outputs){const bytes=await objects.get(output.digest);requireThat(bytes.byteLength===output.size&&bytesDigest(bytes)===output.digest,'INTEGRITY_FAILURE','Bound output object differs');}return {proof:joinProductionReceipt({...options,...frame()}),outer};
 }
}
