import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,symlink,link,rm,chmod} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {prepareDependencies,verifyDependencies,inspectDependencies} from '../../src/execution/dependency-artifact.mjs';
const D='sha256:'+'1'.repeat(64);
async function fixture(){const root=await mkdtemp(join(tmpdir(),'dev2-dependencies-')),source=join(root,'approved','node_modules'),cache=join(root,'cache');await mkdir(join(source,'pkg'),{recursive:true});await mkdir(join(source,'.bin'));await writeFile(join(source,'pkg','bin.mjs'),'console.log(42);\n',{mode:0o755});await symlink('../pkg/bin.mjs',join(source,'.bin','pkg'));return {root,source,cache,close:()=>rm(root,{recursive:true,force:true})};}
test('approved dependency snapshot is content addressed, repeatable and outside the source checkout',async()=>{const f=await fixture();try{await writeFile(join(f.root,'approved','control-key'),'private-canary');const result=await prepareDependencies({sourceDirectory:f.source,cacheDirectory:f.cache,lockDigest:D}),again=await prepareDependencies({sourceDirectory:f.source,cacheDirectory:f.cache,lockDigest:D});assert.equal(result.identity,again.identity);assert.equal(result.nodeModules.startsWith(f.source),false);assert.equal(await readFile(join(result.nodeModules,'.bin','pkg'),'utf8'),'console.log(42);\n');await assert.rejects(readFile(join(result.nodeModules,'control-key')),{code:'ENOENT'});assert.equal((await inspectDependencies(f.source)).contentDigest,result.contentDigest);await assert.rejects(verifyDependencies(result.directory,'sha256:'+'2'.repeat(64)),{code:'INTEGRITY_FAILURE'});}finally{await f.close();}});
test('dependency cache corruption and escaping links fail closed',async()=>{const f=await fixture();try{const r=await prepareDependencies({sourceDirectory:f.source,cacheDirectory:f.cache,lockDigest:D});await chmod(join(r.nodeModules,'pkg','bin.mjs'),0o644);await writeFile(join(r.nodeModules,'pkg','bin.mjs'),'tampered');await assert.rejects(verifyDependencies(r.directory,D),{code:'INTEGRITY_FAILURE'});await symlink('/etc/passwd',join(f.source,'escape'));await assert.rejects(prepareDependencies({sourceDirectory:f.source,cacheDirectory:f.cache,lockDigest:D}),{code:'FORBIDDEN'});}finally{await f.close();}});
test('hard links never enter a dependency artifact',async t=>{const f=await fixture();try{try{await link(join(f.source,'pkg','bin.mjs'),join(f.source,'alias'));}catch(error){if(process.platform==='android'&&['EACCES','EPERM'].includes(error.code)){t.skip('Native Android forbids hard-link creation; hosted Linux must run this check');return;}throw error;}await assert.rejects(inspectDependencies(f.source),{code:'FORBIDDEN'});}finally{await f.close();}});
test('reserved checkout metadata never enters a dependency artifact',async()=>{const f=await fixture();try{await mkdir(join(f.source,'.git'));await assert.rejects(inspectDependencies(f.source),{code:'FORBIDDEN'});}finally{await f.close();}});
