import test from 'node:test';
import assert from 'node:assert/strict';
import {engineWorld} from '../fixtures/engine-world.mjs';
import {canonicalJson,recordDigest} from '../../src/contracts/canonical.mjs';
import {retainedExecutionView} from '../../src/runtime/execution-view.mjs';
const D='sha256:'+'1'.repeat(64);
async function world(){const w=await engineWorld();try{
 const created=await w.create('diagnostic-source','diagnostic.txt','candidate\n'),work=w.ledger.transact(tx=>tx.getWork(created.workId));
 const admitted=await w.engine.admit(w.principal,{op:'validate',requestId:'diagnostic-validate',workId:work.workId,generation:work.generation,expectedRevision:work.revision,expectedHead:w.baseHead,policyDigest:w.binding.policyDigest});
 const [action]=await w.finish([admitted.actionId]);assert.equal(action.status,'succeeded');
 const result=w.ledger.transact(tx=>tx.getPrepared(action.resultId));
 const bytes=Buffer.from(canonicalJson({stdout:Buffer.from('bounded candidate test output\n').toString('base64'),stderr:'',discardedBytes:0})),contentDigest=await w.objects.put(bytes);
 const input={attempt:{installationId:w.binding.installationId,repositoryId:w.binding.repositoryId,workId:work.workId,actionId:action.actionId,attemptId:'diagnostic-attempt',attempt:action.attempt,ownerEpoch:action.ownerEpoch},resultId:action.resultId,profileDigest:D,sourceManifest:result.resultTreeSha256,payloadDigest:D,executionDigest:D,deadline:action.deadline},inputIdentity=recordDigest('dev2.managed-assignment-input.v1',input);
 const assignment={assignmentId:'diagnostic-assignment',sessionId:'diagnostic-session',runId:'42',leaseId:'diagnostic-lease',input,inputIdentity,sealDigest:D,revision:'3',state:'complete',cancelRequested:false,result:{assignmentId:'diagnostic-assignment',leaseId:'diagnostic-lease',inputIdentity,sealDigest:D,trustedRunnerDigest:D,startedAt:1,endedAt:2,stopped:true,exitCode:0,signal:null,deadlineExceeded:false,inputDigest:result.resultTreeSha256,outputDigest:result.resultTreeSha256,artifacts:[contentDigest]}};
 w.ledger.transact(tx=>{tx.run('CREATE TABLE managed_assignment(assignment_id TEXT PRIMARY KEY,state TEXT NOT NULL,record TEXT NOT NULL)');tx.run('CREATE TABLE managed_artifact(assignment_id TEXT NOT NULL,digest TEXT NOT NULL,size INTEGER NOT NULL,state TEXT NOT NULL)');tx.run('INSERT INTO managed_assignment VALUES(?,?,?)',assignment.assignmentId,assignment.state,canonicalJson(assignment));tx.run("INSERT INTO managed_artifact VALUES(?,?,?,'ready')",assignment.assignmentId,contentDigest,bytes.length);});
 return {...w,action,assignment,bytes,contentDigest,read:{apiVersion:1,target:{actionId:action.actionId,artifactId:contentDigest.slice(7)},queries:[{kind:'artifact',startByte:0,maxBytes:65536}],maxReturnBytes:4096},observe:{apiVersion:1,selector:{actionIds:[action.actionId]},limit:8,waitMs:0}};
 }catch(error){await w.close();throw error;}}
test('actual public observation exposes exact retained diagnostics and bounded artifact reads without new effects',async()=>{const w=await world();try{const before=w.ledger.transact(tx=>tx.get('SELECT record FROM managed_assignment').record);const v=await w.app.invoke(w.principal,'dev_observe',w.observe);assert.equal(v.ok,true,JSON.stringify(v));const out=v.data.actions[0].output;assert.equal(out.kind,'execution');assert.equal(out.artifacts.length,1);assert.equal(out.artifacts[0].contentDigest,w.contentDigest);assert.equal(out.artifacts[0].size,w.bytes.length);const r=await w.app.invoke(w.principal,'dev_read',w.read);assert.equal(r.ok,true,JSON.stringify(r));assert.equal(Buffer.from(r.data.results[0].content,'base64').toString(),w.bytes.toString());assert.equal(w.ledger.transact(tx=>tx.get('SELECT record FROM managed_assignment').record),before);assert.equal(w.sends.length,0);}finally{await w.close();}});
test('artifact digest knowledge does not authorize a different action, principal or revoked grant',async()=>{const w=await world();try{const other=await w.create('unrelated-source','other.txt','not this log\n');for(const request of [{...w.read,target:{...w.read.target,actionId:other.actionId}},{...w.read,target:{...w.read.target,artifactId:'9'.repeat(64)}}])assert.equal((await w.app.invoke(w.principal,'dev_read',request)).error.code,'FORBIDDEN');assert.equal((await w.app.invoke({...w.principal,subject:'intruder'},'dev_read',w.read)).error.code,'FORBIDDEN');w.access.allowed=false;assert.equal((await w.app.invoke(w.principal,'dev_read',w.read)).error.code,'FORBIDDEN');}finally{await w.close();}});
test('partial, mismatched and unbound assignment records are not diagnostic capabilities',async()=>{const w=await world();try{w.ledger.transact(tx=>tx.run("UPDATE managed_artifact SET state='partial'"));assert.throws(()=>retainedExecutionView(w.ledger,w.action),{code:'INTEGRITY_FAILURE'});w.ledger.transact(tx=>{tx.run("UPDATE managed_artifact SET state='ready'");tx.run('UPDATE managed_assignment SET record=?',canonicalJson({...w.assignment,result:{...w.assignment.result,inputIdentity:'sha256:'+'9'.repeat(64)}}));});assert.throws(()=>retainedExecutionView(w.ledger,w.action),{code:'INTEGRITY_FAILURE'});w.ledger.transact(tx=>tx.run('UPDATE managed_assignment SET record=?',canonicalJson({...w.assignment,state:'running',result:null})));assert.throws(()=>retainedExecutionView(w.ledger,w.action),{code:'INTEGRITY_FAILURE'});}finally{await w.close();}});
test('grant revocation while reading an artifact is checked again before bytes leave the native boundary',async()=>{const w=await world();try{const get=w.objects.get.bind(w.objects);w.objects.get=async digest=>{const result=await get(digest);w.access.allowed=false;return result;};assert.equal((await w.app.invoke(w.principal,'dev_read',w.read)).error.code,'FORBIDDEN');}finally{await w.close();}});
