import test from 'node:test';
import assert from 'node:assert/strict';
import {engineWorld} from '../fixtures/engine-world.mjs';
import {IntegratedSourceAuthority} from '../../src/release/authority.mjs';
import {parseRecord,canonicalJson} from '../../src/contracts/canonical.mjs';

async function validatedWork(w,i){const created=await w.create('release-create-'+i,'release-'+i+'.txt','release '+i+'\n');let work=await w.engine.work(w.principal,created.workId);const validation=await w.engine.admit(w.principal,{op:'validate',requestId:'release-validate-'+i,workId:work.workId,expectedRevision:work.revision,generation:work.generation,expectedHead:w.baseHead,policyDigest:w.binding.policyDigest});const [action]=await w.finish([validation.actionId]);assert.equal(action.status,'succeeded');return w.engine.work(w.principal,work.workId);}
async function joined(w){const works=await Promise.all([validatedWork(w,0),validatedWork(w,1)]);const response=await w.app.invoke(w.principal,'dev_work',{apiVersion:1,items:works.map((work,i)=>({op:'integrate',requestId:'release-integrate-'+i,workId:work.workId,expectedRevision:work.revision,generation:work.generation,expectedHead:w.baseHead,policyDigest:w.binding.policyDigest})),waitMs:0});assert.equal(response.ok,true);const ids=response.data.items.map(item=>item.receipt.actionId),actions=await w.finish(ids);assert.ok(actions.every(action=>action.status==='succeeded'));const result=w.ledger.transact(tx=>tx.getPrepared(actions[0].resultId));assert.ok(result);return {works,ids,actions,result};}
function authority(w){return new IntegratedSourceAuthority({ledger:w.ledger,binding:w.binding,repository:w.repository,remote:w.remote,validation:()=>w.validation,verifyLineage:head=>w.repository.isAncestor(w.binding,w.baseHead,head)});}

test('D0006 release source accepts exact committed H2 tuple only after all members are atomically successful',async()=>{const w=await engineWorld({h2Enabled:true,capacity:4});try{const j=await joined(w),verified=await authority(w).verify(j.result.commitOid,w.binding.policyDigest);assert.equal(verified.commitOid,j.result.commitOid);assert.equal(verified.effect.h2?.memberCount,2);}finally{await w.close();}});

test('leader success cannot authorize release when any H2 follower is not terminal-integrated',async()=>{const w=await engineWorld({h2Enabled:true,capacity:4});try{const j=await joined(w),follower=j.actions.find(action=>action.h2?.role==='follower');assert.ok(follower);w.ledger.transact(tx=>{const row=tx.get('SELECT record FROM action WHERE action_id=?',follower.actionId),action=parseRecord(String(row.record));const changed={...action,status:'blocked',step:'fault.partial-release'};tx.run('UPDATE action SET status=?,record=? WHERE action_id=?','blocked',canonicalJson(changed),follower.actionId);});await assert.rejects(()=>authority(w).verify(j.result.commitOid,w.binding.policyDigest),{code:'INTEGRITY_FAILURE'});}finally{await w.close();}});
