import test from 'node:test';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
import {engineWorld} from '../fixtures/engine-world.mjs';
import {GitRefTransport} from '../../src/integration/git-ref.mjs';
import {canonicalJson} from '../../src/contracts/canonical.mjs';

const OTHER_POLICY='sha256:'+'9'.repeat(64);
function integrate(w,work,id,extra={}){return {op:'integrate',requestId:id,workId:work.workId,expectedRevision:work.revision,generation:work.generation,expectedHead:w.baseHead,policyDigest:w.binding.policyDigest,...extra};}
async function validatedMember(w,id,path='h2-'+id+'.mjs',content='export const '+id.replaceAll('-','_')+'=true;\n'){
 const created=await w.create('create-'+id,path,content);let work=await w.engine.work(w.principal,created.workId);
 const admitted=await w.engine.admit(w.principal,{...integrate(w,work,'validate-'+id),op:'validate'});const [done]=await w.finish([admitted.actionId]);assert.equal(done.status,'succeeded',JSON.stringify(done));
 work=await w.engine.work(w.principal,created.workId);return {work,resultId:done.resultId};
}
async function envelope(w,members,prefix='h2',extras=[]){const response=await w.app.invoke(w.principal,'dev_work',{apiVersion:1,items:members.map((member,index)=>integrate(w,member.work,prefix+'-'+index,extras[index]??{})),waitMs:0});assert.equal(response.ok,true,canonicalJson(response));for(const row of response.data.items)assert.equal(row.ok,true,canonicalJson(row));return response.data.items.map(row=>row.receipt);}
async function idle(engine,timeout=20000){const until=Date.now()+timeout;while(Date.now()<until){if(engine.running.size===0)return;await delay(10);}throw Error('H2 idle deadline');}
function h2EffectCount(w){return Number(w.ledger.transact(tx=>tx.get("SELECT count(*) n FROM effect WHERE json_extract(record,'$.h2.version')=1")?.n??0));}

async function joined(w,n,prefix='joined') {const members=[];for(let i=0;i<n;i++)members.push(await validatedMember(w,prefix+'-'+i));const receipts=await envelope(w,members,prefix+'-integrate'),ids=receipts.map(row=>row.actionId),actions=await w.finish(ids);return {members,receipts,ids,actions};}

test('H2 N=8 performs one composed full validation, one effect/CAS, all-member settlement and truthful follower observation',async()=>{const w=await engineWorld({h2Enabled:true,h2MaxMembers:32});let selectionError=null;const selectGroup=w.engine.h2.selectGroup.bind(w.engine.h2);w.engine.h2.selectGroup=async(...args)=>{try{return await selectGroup(...args);}catch(error){selectionError=error;throw error;}};try{
 const joinedResult=await joined(w,8,'n8');assert.equal(selectionError,null,selectionError instanceof Error?selectionError.stack:String(selectionError));assert.ok(joinedResult.actions.every(action=>action.status==='succeeded'),JSON.stringify(joinedResult.actions));
 assert.equal(w.validationRuns.length,9);assert.equal(w.profileRuns.length,18);assert.equal(w.sends.length,1);assert.equal(h2EffectCount(w),1);
 const effects=joinedResult.ids.map(id=>w.ledger.transact(tx=>tx.getEffect(id)));assert.equal(new Set(effects.map(effect=>effect.effectId)).size,1);assert.equal(effects[0].h2.memberCount,8);
 for(const member of joinedResult.members)assert.equal((await w.engine.work(w.principal,member.work.workId)).disposition,'integrated');
 const follower=joinedResult.ids.at(-1),observed=await w.app.invoke(w.principal,'dev_observe',{apiVersion:1,selector:{actionIds:[follower]}});assert.equal(observed.ok,true,canonicalJson(observed));assert.equal(observed.data.effects.length,1);assert.equal(observed.data.effects[0].effectId,effects[0].effectId);assert.equal(observed.data.results.length,1);assert.equal(observed.data.results[0].resultId,joinedResult.actions[0].resultId);assert.equal(observed.data.results[0].integration.kind,'integrated');
 }finally{await w.close();}});

test('H2 makes progress with execution capacity one and still reserves only the leader',async()=>{const w=await engineWorld({h2Enabled:true,h2MaxMembers:32,capacity:1});try{const result=await joined(w,2,'cap1');assert.ok(result.actions.every(action=>action.status==='succeeded'));assert.equal(w.validationRuns.length,3);assert.equal(w.sends.length,1);assert.equal(w.ledger.transact(tx=>tx.reservations().length),0);}finally{await w.close();}});

async function noPumpEnvelope(w,members,prefix,extras=[]){const pump=w.engine.pump;w.engine.pump=()=>{};try{return await envelope(w,members,prefix,extras);}finally{w.engine.pump=pump;}}

test('explicit preparedResultId excludes H2 grouping and remains ordinary',async()=>{const w=await engineWorld({h2Enabled:true});try{const a=await validatedMember(w,'explicit-a'),b=await validatedMember(w,'explicit-b'),receipts=await noPumpEnvelope(w,[a,b],'explicit-int',[{preparedResultId:a.resultId},{}]);for(const row of receipts)assert.equal(w.ledger.transact(tx=>tx.getH2Selection(row.actionId)),null);}finally{await w.close();}});
test('missing retained member validation falls back with no partial H2 selection',async()=>{const w=await engineWorld({h2Enabled:true});try{const a=await validatedMember(w,'missing-a'),created=await w.create('create-missing-b','missing-b.mjs','export const missing_b=true;\n'),b={work:await w.engine.work(w.principal,created.workId)},receipts=await noPumpEnvelope(w,[a,b],'missing-int');for(const row of receipts)assert.equal(w.ledger.transact(tx=>tx.getH2Selection(row.actionId)),null);}finally{await w.close();}});
test('overlapping path candidates fall back with no partial H2 selection',async()=>{const w=await engineWorld({h2Enabled:true});try{const a=await validatedMember(w,'overlap-a','shared.mjs','export const a=1;\n'),b=await validatedMember(w,'overlap-b','shared.mjs','export const b=2;\n'),receipts=await noPumpEnvelope(w,[a,b],'overlap-int');for(const row of receipts)assert.equal(w.ledger.transact(tx=>tx.getH2Selection(row.actionId)),null);}finally{await w.close();}});
test('unavailable capacity persists no partial H2 selection',async()=>{const w=await engineWorld({h2Enabled:true,capacity:1});try{const a=await validatedMember(w,'busy-a'),b=await validatedMember(w,'busy-b'),created=await w.create('busy-blocker','busy-blocker.mjs','export const blocker=true;\n'),block=await w.engine.work(w.principal,created.workId),queued=await w.engine.admit(w.principal,{...integrate(w,block,'busy-validate'),op:'validate'}),reserved=w.engine.coordinator.takeReady();assert.equal(reserved.action.actionId,queued.actionId);const receipts=await noPumpEnvelope(w,[a,b],'busy-int');for(const row of receipts)assert.equal(w.ledger.transact(tx=>tx.getH2Selection(row.actionId)),null);assert.equal(w.ledger.transact(tx=>tx.reservations().length),1);}finally{await w.close();}});

test('selection transaction rollback leaves ordinary admitted actions and zero tuple rows',async()=>{let w;w=await engineWorld({h2Enabled:true,h2Fault:point=>{if(point.startsWith('selection.after-work-'))throw Error('selection crash');}});try{const a=await validatedMember(w,'select-a'),b=await validatedMember(w,'select-b'),receipts=await noPumpEnvelope(w,[a,b],'select-int');assert.equal(w.ledger.transact(tx=>tx.all('SELECT * FROM h2_selection').length),0);assert.equal(w.ledger.transact(tx=>tx.all('SELECT * FROM h2_member').length),0);for(const receipt of receipts){const action=w.ledger.transact(tx=>tx.getAction(receipt.actionId));assert.equal(action.status,'queued');assert.equal((await w.engine.work(w.principal,action.workId)).revision,receipt.revision);}}finally{await w.close();}});

async function boundaryCase(kind){let w,injected=false,targetAction=null;w=await engineWorld({h2Enabled:true,h2Fault:point=>{if(injected||point!=='before-effect-freeze')return;injected=true;const member=w.ledger.transact(tx=>tx.get('SELECT action_id,work_id FROM h2_member ORDER BY ordinal DESC LIMIT 1'));targetAction=String(member.action_id);if(kind==='cancel')w.engine.store('cancel:'+targetAction,true);else w.ledger.transact(tx=>{const work=tx.getWork(String(member.work_id)),revision=String(BigInt(work.revision)+1n);assert.equal(tx.compareWork(work.revision,{...work,revision}),true);});}});try{const a=await validatedMember(w,kind+'-a'),b=await validatedMember(w,kind+'-b'),pump=w.engine.pump;w.engine.pump=()=>{};const receipts=await envelope(w,[a,b],kind+'-int');await idle(w.engine);w.engine.pump=pump;assert.equal(h2EffectCount(w),0);const actions=receipts.map(row=>w.ledger.transact(tx=>tx.getAction(row.actionId)));if(kind==='cancel')assert.equal(actions.find(action=>action.actionId===targetAction).status,'cancelled');assert.ok(actions.every(action=>['queued','cancelled'].includes(action.status)),JSON.stringify(actions));for(const member of [a,b])assert.equal((await w.engine.work(w.principal,member.work.workId)).disposition,'open');}finally{await w.close();}}

test('last-moment member cancellation immediately before effect freeze attaches no effect and preserves ordinary fallback',()=>boundaryCase('cancel'));
test('last-moment member revision race immediately before effect freeze attaches no effect and preserves ordinary fallback',()=>boundaryCase('revision'));

test('authorization revoke after async checks but before sender reservation is synchronously fenced with zero physical send',async()=>{let w,injected=false;w=await engineWorld({h2Enabled:true,h2Fault:point=>{if(point==='before-sender-reservation'&&!injected){injected=true;w.access.allowed=false;}}});try{const a=await validatedMember(w,'revoke-a'),b=await validatedMember(w,'revoke-b'),receipts=await envelope(w,[a,b],'revoke-int');await idle(w.engine);assert.equal(w.sends.length,0);assert.equal(h2EffectCount(w),0);assert.equal(Number(w.ledger.transact(tx=>tx.get("SELECT count(*) n FROM meta WHERE key LIKE 'h2-disarmed:%'")?.n??0)),1);const actions=receipts.map(row=>w.ledger.transact(tx=>tx.getAction(row.actionId)));assert.ok(actions.every(action=>action.status==='failed'&&action.errorCode==='FORBIDDEN'),JSON.stringify(actions));}finally{await w.close();}});

test('effect attachment crash rolls back the whole tuple with zero partial effect references',async()=>{let w;w=await engineWorld({h2Enabled:true,h2Fault:point=>{if(point==='effect.after-attach')throw Error('effect crash');}});try{const a=await validatedMember(w,'effect-a'),b=await validatedMember(w,'effect-b'),receipts=await envelope(w,[a,b],'effect-int');await idle(w.engine);assert.equal(h2EffectCount(w),0);const actions=receipts.map(row=>w.ledger.transact(tx=>tx.getAction(row.actionId)));assert.ok(actions.every(action=>action.status==='blocked'&&action.h2?.effectId===null),JSON.stringify(actions));}finally{await w.close();}});

async function settlementCrash(prefix){let w,crash=true;w=await engineWorld({h2Enabled:true,h2Fault:point=>{if(crash&&point.startsWith(prefix))throw Error('settlement crash');}});try{const a=await validatedMember(w,prefix.replaceAll('.','-')+'-a'),b=await validatedMember(w,prefix.replaceAll('.','-')+'-b'),receipts=await envelope(w,[a,b],'settle-int-'+prefix.replaceAll('.','-'));await idle(w.engine);const selected=w.ledger.transact(tx=>tx.getH2Selection(receipts[0].actionId));assert.ok(selected);let frame=w.ledger.transact(tx=>w.engine.h2.frameIn(tx,selected.selection));assert.ok(frame.effect&&frame.reservation);let terminal=frame.members.filter(row=>['succeeded','failed','cancelled'].includes(row.action.status)).length;assert.equal(terminal,0,'durable partial settlement observed');assert.ok(frame.members.every(row=>row.work.disposition==='open'));
 crash=false;const principal=w.engine.metadata('principal:'+selected.selection.leaderActionId),integrator=w.engine.integratorFromPrincipal(principal,w.engine.input(selected.selection.leaderActionId));await w.engine.h2.reconcile(selected.selection,frame.reservation.attempt,frame.effect,integrator);frame=w.ledger.transact(tx=>w.engine.h2.frameIn(tx,selected.selection));terminal=frame.members.filter(row=>['succeeded','failed','cancelled'].includes(row.action.status)).length;assert.equal(terminal,2);assert.ok(frame.members.every(row=>row.action.status==='succeeded'&&row.work.disposition==='integrated'));
 }finally{await w.close();}}

test('settlement crash after an Action write is durably 0/N and recovery commits N/N',()=>settlementCrash('settlement.after-action-'));
test('settlement crash after a Work write is durably 0/N and recovery commits N/N',()=>settlementCrash('settlement.after-work-'));

test('sender-unknown H2 blocks only its tuple; unrelated same-ref work wins H CAS and tuple later settles uniformly stale',async()=>{const w=await engineWorld({h2Enabled:true});try{const a=await validatedMember(w,'unknown-a'),b=await validatedMember(w,'unknown-b'),observe=w.remote.observeSender;w.remote.observeSender=async effect=>effect.h2?{stopped:false,delivery:'unknown',state:'unknown'}:observe(effect);const joinedReceipts=await envelope(w,[a,b],'unknown-int'),joinedActions=await w.finish(joinedReceipts.map(row=>row.actionId));assert.ok(joinedActions.every(action=>action.status==='blocked'));assert.equal(w.sends.length,0);assert.equal(h2EffectCount(w),1);
 const independent=await w.create('independent-create','independent-h2.mjs','export const independent=true;\n'),work=await w.engine.work(w.principal,independent.workId),ordinary=await w.engine.admit(w.principal,integrate(w,work,'independent-integrate'));assert.equal((await w.finish([ordinary.actionId]))[0].status,'succeeded');assert.equal(w.sends.length,1);
 w.remote.observeSender=observe;const followerId=joinedReceipts.at(-1).actionId,followerAction=w.ledger.transact(tx=>tx.getAction(followerId)),followerWork=await w.engine.work(w.principal,followerAction.workId);await w.engine.admit(w.principal,{op:'resume',requestId:'unknown-resume',workId:followerWork.workId,expectedRevision:followerWork.revision,actionId:followerId});const final=joinedReceipts.map(row=>w.ledger.transact(tx=>tx.getAction(row.actionId)));assert.ok(final.every(action=>action.status==='failed'&&action.errorCode==='CONTENDED_REF'),JSON.stringify(final));assert.ok((await Promise.all([a,b].map(member=>w.engine.work(w.principal,member.work.workId)))).every(item=>item.disposition==='open'));
 }finally{await w.close();}});

test('lost H2 provider response reconciles the same one effect without a duplicate send',async()=>{let first=true;const w=await engineWorld({h2Enabled:true,afterSend:async()=>{if(first){first=false;throw Error('lost response');}}});try{const result=await joined(w,2,'loss');assert.ok(result.actions.every(action=>action.status==='succeeded'),JSON.stringify(result.actions));assert.equal(w.sends.length,1);assert.equal(h2EffectCount(w),1);}finally{await w.close();}});

test('verified managed descendant of composed C is accepted for whole-tuple settlement',async()=>{let w,extended=false,descendant=null;w=await engineWorld({h2Enabled:true,afterSend:async()=>{if(extended)return;extended=true;const observed=await w.remote.resolve(),current=await w.repository.readCommit(w.binding,observed.head),blob=await w.repository.putBlob(Buffer.from('descendant\n')),tree=await w.repository.writeTree([...current.source.entries,{path:'descendant.txt',mode:'100644',...blob}]);descendant=await w.repository.freezeCommit(observed.head,tree,{author:'Fixture <fixture@example.invalid>',committer:'Fixture <fixture@example.invalid>',timestamp:1700000002000,message:'managed descendant'},'descendant_result');const transport=new GitRefTransport(w.repository,w.binding),effect={effectId:'descendant_effect',workId:'descendant_work',actionId:'descendant_action',repositoryId:w.binding.repositoryId,bindingEpoch:w.binding.bindingEpoch,ref:w.binding.ref,expectedHead:observed.head,commitOid:descendant,preparedResultId:'descendant_result',validationId:w.binding.policyDigest,policyDigest:w.binding.policyDigest};assert.equal((await transport.compareUpdate(effect)).kind,'sent');}});try{const result=await joined(w,2,'desc');assert.ok(result.actions.every(action=>action.status==='succeeded'));assert.equal((await w.remote.resolve()).head,descendant);const selection=w.ledger.transact(tx=>tx.getH2Selection(result.ids[0]));const observation=w.ledger.transact(tx=>tx.effectObservation(selection.selection.leaderActionId));assert.equal(observation.kind,'integrated');assert.equal(observation.observedHead,descendant);}finally{await w.close();}});
