import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Ledger} from '../../src/storage/ledger.mjs';
const D='sha256:'+'1'.repeat(64),K='sha256:'+'2'.repeat(64),O='sha1:'+'3'.repeat(40);
const binding={repositoryId:'repo',installationId:'installation',provider:'fixture',providerRepositoryId:'1',remote:'https://fixture.invalid/repo',ref:'refs/heads/dev-2',bindingEpoch:'1',policyDigest:D};
const candidate={treeOid:O,manifestDigest:D};
function root(){return mkdtempSync(join(tmpdir(),'dev2-h2-storage-'));}
function rows(db){db.transact(tx=>{for(let i=0;i<2;i++){const work={workId:'w'+i,repositoryId:'repo',bindingEpoch:'1',principal:'p',baseCommitOid:O,baseTreeOid:O,candidate,generation:'0',revision:'0',disposition:'open',currentActionId:'a'+i};tx.insertWork(work);tx.insertAction({actionId:'a'+i,requestId:'r'+i,principal:'p',bindingEpoch:'1',intentDigest:D,operation:'integrate',workId:work.workId,status:'queued',step:'admitted',attempt:'0',ownerEpoch:db.ownerEpoch,deadline:9999999999999,resultId:null,errorCode:null},{op:'integrate'});}});}
function selection(){return {version:1,memberTupleDigest:D,leaderActionId:'a0',tupleObjectDigest:D,deltaObjectDigest:K,compositionIdentity:K,resultId:'result',expectedHead:O,resultTreeOid:O,resultTreeSha256:D,policyDigest:D,memberCount:2,metadata:{author:'a',committer:'a',timestamp:1,message:'dev-2 composed source change'}};}
const members=[{actionId:'a0',workId:'w0',ordinal:0,reservedWorkRevision:'1'},{actionId:'a1',workId:'w1',ordinal:1,reservedWorkRevision:'1'}];
test('ledger v2 retains immutable H2 selection and follower resolves the one leader effect',()=>{const r=root(),file=join(r,'work.sqlite'),db=new Ledger(file,binding);try{assert.equal(db.db.prepare('PRAGMA user_version').get().user_version,2);rows(db);db.transact(tx=>tx.putH2Selection(selection(),members));assert.equal(db.transact(tx=>tx.getH2Selection('a1').selection.leaderActionId),'a0');assert.deepEqual(db.transact(tx=>tx.h2Members(D)).map(m=>m.actionId),['a0','a1']);const effect={effectId:'effect',workId:'w0',actionId:'a0',repositoryId:'repo',bindingEpoch:'1',ref:binding.ref,expectedHead:O,commitOid:O,preparedResultId:'result',validationId:K,policyDigest:D,h2:{version:1,memberTupleDigest:D,compositionIdentity:K,tupleObjectDigest:D,deltaObjectDigest:K,memberCount:2}};db.transact(tx=>tx.putEffect(effect));assert.deepEqual(db.transact(tx=>tx.getEffect('a1')),effect);assert.equal(db.transact(tx=>tx.getDirectEffect('a1')),null);}finally{db.close();rmSync(r,{recursive:true,force:true});}});
test('H2 selection writes roll back atomically and leave no partial membership',()=>{const r=root(),db=new Ledger(join(r,'work.sqlite'),binding);try{rows(db);assert.throws(()=>db.transact(tx=>{tx.putH2Selection(selection(),members);throw Error('crash');}),/crash/);assert.equal(db.transact(tx=>tx.getH2SelectionByDigest(D)),null);assert.equal(db.transact(tx=>tx.h2Members(D)).length,0);}finally{db.close();rmSync(r,{recursive:true,force:true});}});
test('v1 ordinary rows migrate without reinterpretation and a version-1 reader refuses v2 state',()=>{const r=root(),file=join(r,'work.sqlite');let db=new Ledger(file,binding);try{rows(db);}finally{db.close();}const raw=new DatabaseSync(file);raw.exec('DROP TABLE h2_member;DROP TABLE h2_selection;PRAGMA user_version=1;');raw.close();db=new Ledger(file,binding);try{assert.equal(db.db.prepare('PRAGMA user_version').get().user_version,2);assert.equal(db.transact(tx=>tx.getWork('w0')).workId,'w0');}finally{db.close();}assert.throws(()=>new Ledger(file,binding,{maxVersion:1}),{code:'INTEGRITY_FAILURE'});rmSync(r,{recursive:true,force:true});});
test('pre-effect membership retirement preserves immutable selection evidence while removing follower routing',()=>{const r=root(),db=new Ledger(join(r,'work.sqlite'),binding);try{rows(db);db.transact(tx=>tx.putH2Selection(selection(),members));db.transact(tx=>tx.retireH2Members(D));assert.equal(db.transact(tx=>tx.h2Members(D)).length,0);assert.equal(db.transact(tx=>tx.getH2SelectionByDigest(D)).memberTupleDigest,D);assert.equal(db.transact(tx=>tx.getH2Selection('a1')),null);}finally{db.close();rmSync(r,{recursive:true,force:true});}});
