import test from 'node:test';
import assert from 'node:assert/strict';
import {writeFile,mkdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {gitWorld} from '../fixtures/git-world.mjs';
import {Ledger} from '../../src/storage/ledger.mjs';
import {DurableGitSender} from '../../src/integration/sender.mjs';
import {bytesDigest} from '../../src/contracts/canonical.mjs';
import {Dev2Error} from '../../src/contracts/errors.mjs';
const python=execFileSync('which',['python3'],{encoding:'utf8'}).trim();
async function fixture(){const w=await gitWorld();await w.repository.readCommit(w.binding,w.baseHead);const ledger=new Ledger(join(w.root,'ledger.sqlite'),w.binding),root=join(w.root,'senders'),config=join(w.root,'sender.json');await mkdir(root);await writeFile(config,JSON.stringify({schemaVersion:1,...w.binding,stateDirectory:root,repositoryDirectory:w.repository.directory,gitExecutable:w.repository.options.executable,environment:w.repository.options.environment,allowLocalFixture:true,timeoutMs:10000}),{mode:0o600});const sender=new DurableGitSender({ledger,stateDirectory:root,configurationPath:config,pythonExecutable:python,helperPath:resolve('tools/git-sender.py'),environment:{PATH:process.env.PATH??'',HOME:w.root,TMPDIR:w.root}});const blob=await w.repository.putBlob(Buffer.from('h2\n')),tree=await w.repository.writeTree([...w.source.entries,{path:'h2.txt',mode:'100644',...blob}]),commit=await w.repository.freezeCommit(w.baseHead,tree,{author:'Fixture <fixture@example.invalid>',committer:'Fixture <fixture@example.invalid>',timestamp:1700000001000,message:'H2 sender fence'},'sender_h2');const effect={effectId:'effect-h2',workId:'work',actionId:'action',repositoryId:w.binding.repositoryId,bindingEpoch:w.binding.bindingEpoch,ref:w.binding.ref,expectedHead:w.baseHead,commitOid:commit,preparedResultId:'prepared',validationId:bytesDigest(Buffer.from('fixture')),policyDigest:w.binding.policyDigest,h2:{version:1,memberTupleDigest:bytesDigest(Buffer.from('tuple')),compositionIdentity:bytesDigest(Buffer.from('composition')),tupleObjectDigest:bytesDigest(Buffer.from('tuple-object')),deltaObjectDigest:bytesDigest(Buffer.from('delta-object')),memberCount:2}};return {...w,ledger,sender,effect,async close(){ledger.close();await w.close();}};}

test('current authority fence executes in the same transaction before invocation reservation becomes remote-possible',async()=>{const w=await fixture();try{let checked=false;await assert.rejects(()=>w.sender.compareUpdate(w.effect,tx=>{checked=true;assert.equal(tx.get('SELECT value FROM meta WHERE key=?','sender:'+w.effect.effectId),undefined);throw new Dev2Error('FORBIDDEN');},true),{code:'FORBIDDEN'});assert.equal(checked,true);assert.equal(w.sender.current(w.effect),null);assert.equal((await w.repository.resolve(w.binding)).head,w.baseHead);}finally{await w.close();}});

test('an existing possibly-live physical invocation is never replaced by an H2 logical retry',async()=>{const w=await fixture();try{const originalCommand=w.sender.command;w.sender.command=async(...args)=>{if(args[1][0]==='inspect')return {spawnFailed:false,timedOut:false,discardedBytes:0,exitCode:0,stdout:Buffer.from(JSON.stringify({invocationId:w.sender.current(w.effect).invocationId,stopped:false,delivery:'unknown',state:'running'})),stderr:Buffer.alloc(0)};return originalCommand(...args);};w.ledger.transact(tx=>tx.run('INSERT INTO meta(key,value) VALUES(?,?)','sender:'+w.effect.effectId,JSON.stringify({invocationId:'already-running',effectDigest:bytesDigest(Buffer.from('wrong'))})));assert.throws(()=>w.sender.current(w.effect),{code:'INTEGRITY_FAILURE'});}finally{await w.close();}});
