import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {HostedSession} from '../../src/execution/hosted-session.mjs';import {recordDigest} from '../../src/contracts/canonical.mjs';import {Dev2Error} from '../../src/contracts/errors.mjs';
const D='sha256:'+'1'.repeat(64),C='2'.repeat(40);
async function fixture(){let time=10000,polls=0,executions=0;const root=await mkdtemp(join(tmpdir(),'dev2-hosted-session-')),expected={commit:C,runId:'19',repositoryId:'123',repositoryFullName:'test/repo',trustedRunnerDigest:D},intent={sessionId:'s',launchCommit:C,providerRepositoryId:'123',repositoryFullName:'test/repo',trustedRunnerDigest:D,ref:'refs/heads/dev2-exec/s',workflowRef:'test/repo/.github/workflows/dev2-executor.yml@refs/heads/dev2-exec/s',createdAt:10000,deadline:810000},session={intent,intentDigest:recordDigest('dev2.managed-session.v1',intent),run:{runId:'19',runAttempt:'1'}},a={assignmentId:'a',sessionId:'s',runId:'19',sealDigest:D};
 const options={stateDirectory:root,expected,deadline:810000,idleTimeoutMs:60000,now:()=>time,sleep:async ms=>{time+=ms;},client:{sessionId:'s',poll:async()=>{polls++;return {session,assignment:polls===1?a:null,cancelRequested:polls>1};}},createRunner:()=>({execute:async(value)=>{executions++;assert.deepEqual(value,a);if(executions===1)throw new Dev2Error('EXECUTION_UNAVAILABLE','lost after native accepted result');return {};}})};return {root,options,session,counts:()=>({polls,executions}),close:()=>rm(root,{recursive:true,force:true})};}
test('hosted loop retains and retries exact pending receipt before polling another assignment',async()=>{const f=await fixture();try{const loop=new HostedSession(f.options),result=await loop.run();assert.deepEqual(result,{state:'cancelled',completed:1});assert.deepEqual(f.counts(),{polls:2,executions:2});const record=JSON.parse(await readFile(join(f.root,'session.json'),'utf8'));assert.equal(record.pending,null);assert.equal(record.completed,1);assert.equal(record.seal,D);}finally{await f.close();}});
test('restart with a pending assignment replays that identity, not a new native poll or deadline',async()=>{const f=await fixture();try{const first=new HostedSession(f.options);first.verify(f.session);first.pending={assignmentId:'a',sessionId:'s',runId:'19',sealDigest:D};first.seal=D;await first.save();let seen;f.options.createRunner=()=>({execute:async a=>{seen=a;throw new Dev2Error('FORBIDDEN');}});const next=new HostedSession(f.options);await assert.rejects(next.run(),{code:'FORBIDDEN'});assert.equal(seen.assignmentId,'a');assert.equal(f.counts().polls,0);assert.equal(next.deadline,810000);}finally{await f.close();}});
test('idle exit requires native retirement; lost retirement response preserves a racing assignment',async()=>{const f=await fixture();try{let retireCalls=0,executions=0;const a={assignmentId:'a',sessionId:'s',runId:'19',sealDigest:D};f.options.client.poll=async()=>({session:f.session,assignment:null,cancelRequested:false});f.options.client.retire=async()=>{retireCalls++;if(retireCalls===1)throw new Dev2Error('EXECUTION_UNAVAILABLE','retirement response lost');return {session:f.session,assignment:executions===0?a:null,cancelRequested:executions>0};};f.options.createRunner=()=>({execute:async value=>{assert.deepEqual(value,a);executions++;return {};}});const loop=new HostedSession(f.options),result=await loop.run();assert.deepEqual(result,{state:'idle',completed:1});assert.equal(retireCalls,3);assert.equal(executions,1);assert.equal(loop.pending,null);}finally{await f.close();}});
test('unacknowledged retirement expires rather than claiming idle termination was accepted',async()=>{const f=await fixture();try{let retireCalls=0;f.options.client.poll=async()=>({session:f.session,assignment:null,cancelRequested:false});f.options.client.retire=async()=>{retireCalls++;throw new Dev2Error('EXECUTION_UNAVAILABLE');};const result=await new HostedSession(f.options).run();assert.equal(result.state,'expired');assert.equal(result.completed,0);assert.ok(retireCalls>1);}finally{await f.close();}});
test('wrong provider run and changed native launch intent cannot execute',async()=>{const f=await fixture();try{const loop=new HostedSession(f.options);assert.throws(()=>loop.verify({...f.session,run:{runId:'20',runAttempt:'1'}}),{code:'UNAUTHORIZED'});loop.verify(f.session);assert.throws(()=>loop.verify({...f.session,intentDigest:D}),{code:'UNAUTHORIZED'});assert.equal(f.counts().executions,0);}finally{await f.close();}});
