import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {canonicalJson,recordDigest,bytesDigest} from '../../src/contracts/canonical.mjs';
import {sourceManifest} from '../../src/repository/entries.mjs';
import {materialize,inspectMaterialization} from '../../src/candidate/materialize.mjs';
import {ObjectStore} from '../../src/storage/objects.mjs';
import {preparePayload,decodePayload,executionIdentity,physicalAttempt} from '../../src/execution/payload.mjs';
import {ExecutorClient} from '../../src/execution/executor-client.mjs';
const D='sha256:'+'1'.repeat(64),O='sha1:'+'1'.repeat(40);
function inputs(){const bytes=Buffer.from('export const answer = 42;\n'),blobOid='sha1:'+createHash('sha1').update('blob '+bytes.length+'\0').update(bytes).digest('hex');const entry={path:'src/answer.mjs',mode:'100644',blobOid,contentDigest:bytesDigest(bytes),size:bytes.length},source={treeOid:O,manifestDigest:sourceManifest([entry]),entries:[entry]};const definition={profileId:'core',argv:['/usr/local/bin/node','--check','/source/src/answer.mjs'],cwd:'.',parameters:{},timeoutMs:30000,killGraceMs:2000,memoryBytes:268435456,pids:64,cpuMillis:1000,diskBytes:67108864,logBytes:65536,network:'none',imageDigest:D,replaySafe:true};const profile={...definition,digest:recordDigest('dev2.profile.v1',definition)},execution={orderedProfileDigests:[profile.digest],trustedRunnerDigest:D,toolchainDigest:D,environmentClass:'fixture-not-production',dependencyLockDigest:D};return {source,profile,execution,repository:{blob:async id=>{assert.equal(id,blobOid);return bytes;}}};}
test('managed bundle verifies exact Git objects and materializes identical readonly-input bytes',async()=>{const root=await mkdtemp(join(tmpdir(),'dev2-payload-'));try{const objects=new ObjectStore(join(root,'objects'));await objects.init();const input=inputs(),prepared=await preparePayload({...input,objects,resultId:'result'}),bytes=await objects.get(prepared.payloadDigest),expected={resultId:'result',payloadDigest:prepared.payloadDigest,sourceManifest:input.source.manifestDigest,profileDigest:input.profile.digest,executionDigest:executionIdentity(input.execution)};const decoded=decodePayload(bytes,expected),destination=join(root,'attempt','source');await materialize(decoded.repository,decoded.payload.source,destination);assert.equal(await inspectMaterialization(input.source,destination),input.source.manifestDigest);assert.equal(await readFile(join(destination,'src/answer.mjs'),'utf8'),'export const answer = 42;\n');await assert.rejects(decoded.repository.blob(O),{code:'FORBIDDEN'});for(const patch of [{resultId:'other'},{sourceManifest:D},{profileDigest:D},{executionDigest:D},{payloadDigest:D}])assert.throws(()=>decodePayload(bytes,{...expected,...patch}),{code:'INTEGRITY_FAILURE'});
 const mutate=change=>{const body=JSON.parse(Buffer.from(bytes).toString());change(body);const altered=Buffer.from(canonicalJson(body));return ()=>decodePayload(altered,{...expected,payloadDigest:bytesDigest(altered)});};
 assert.throws(mutate(p=>p.blobs[0].data=Buffer.from('tampered').toString('base64')),{code:'INTEGRITY_FAILURE'});assert.throws(mutate(p=>p.blobs.push({...p.blobs[0]})),{code:'INTEGRITY_FAILURE'});assert.throws(mutate(p=>p.profile.argv=['/bin/sh','-c','unapproved']),{code:'INTEGRITY_FAILURE'});assert.throws(mutate(p=>p.source.entries[0].path='../escape'));
 }finally{await rm(root,{recursive:true,force:true});}});
test('physical profile identities are separate while logical attempt remains unchanged',()=>{const attempt={installationId:'i',repositoryId:'r',workId:'w',actionId:'a',attemptId:'logical',attempt:'1',ownerEpoch:'2'},a={input:{attempt,resultId:'result',profileDigest:D}},b={input:{attempt,resultId:'result',profileDigest:'sha256:'+'2'.repeat(64)}};assert.notEqual(physicalAttempt(a).attemptId,physicalAttempt(b).attemptId);assert.equal(attempt.attemptId,'logical');assert.equal(physicalAttempt(a).workId,'w');assert.deepEqual(physicalAttempt(a),physicalAttempt(a));});
test('executor client bounded chunks preserve a stable exact upload and download identity',async()=>{const content=Buffer.alloc(145000,32),objectDigest=bytesDigest(content),requests=[],chunks=new Map(),assignment={assignmentId:'a',leaseId:'lease'};const client=new ExecutorClient({origin:'http://127.0.0.1:1234',allowInsecureFixture:true,sessionId:'s',token:async()=>'oidc-fixture',fetcher:async(url,options)=>{assert.equal(url,'http://127.0.0.1:1234/executor');assert.equal(options.redirect,'error');assert.equal(options.headers.authorization,'Bearer oidc-fixture');const r=JSON.parse(options.body);requests.push(r);let data;
 if(r.op==='object.read'){const bytes=content.subarray(r.offset,r.offset+r.maxBytes);data={digest:objectDigest,size:content.length,offset:r.offset,chunkDigest:bytesDigest(bytes),data:bytes.toString('base64'),complete:r.offset+bytes.length===content.length};}
 else{assert.equal(r.op,'artifact.write');assert.equal(r.digest,objectDigest);const bytes=Buffer.from(r.data,'base64');if(chunks.has(r.offset))assert.deepEqual(bytes,chunks.get(r.offset));else chunks.set(r.offset,bytes);data={digest:objectDigest,received:r.offset+bytes.length,complete:r.offset+bytes.length===content.length};}
 return new Response(canonicalJson({apiVersion:1,ok:true,data}));}});assert.deepEqual(await client.download(assignment,objectDigest),content);assert.equal(await client.upload(assignment,content),objectDigest);assert.equal(await client.upload(assignment,content),objectDigest);assert.equal(chunks.size,3);assert.equal(requests.length,9);assert.deepEqual(Buffer.concat([...chunks.values()]),content);
});
test('executor client rejects redirect origins, wrong sessions and corrupted chunk bytes',async()=>{assert.throws(()=>new ExecutorClient({origin:'https://other.example',sessionId:'s',token:async()=>''}));const client=new ExecutorClient({origin:'https://fixture.workers.dev',sessionId:'s',token:async()=>'token',fetcher:async()=>new Response(canonicalJson({apiVersion:1,ok:true,data:{digest:D,size:1,offset:0,chunkDigest:D,data:'YQ==',complete:true}}))});await assert.rejects(client.call({apiVersion:1,sessionId:'wrong',op:'poll'}),{code:'FORBIDDEN'});await assert.rejects(client.download({assignmentId:'a',leaseId:'l'},D),{code:'INTEGRITY_FAILURE'});});
