import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Ledger} from '../../src/storage/ledger.mjs';
import {ManagedSessions} from '../../src/execution/sessions.mjs';
import {AssignmentTransfer} from '../../src/execution/session-transfer.mjs';
import {ObjectStore} from '../../src/storage/objects.mjs';
import {recordDigest,bytesDigest,canonicalJson} from '../../src/contracts/canonical.mjs';
const D=bytesDigest(Buffer.from('explicit-session-fixture-not-production-seal'));
const O='sha1:'+'1'.repeat(40);
const binding={installationId:'install',repositoryId:'repo',providerRepositoryId:'123',bindingEpoch:'1',provider:'github',remote:'https://github.com/fixture/repo.git',ref:'refs/heads/dev-2',policyDigest:D};
const config={repositoryOwnerId:'456',repositoryFullName:'fixture/repo',approvedCommit:'1'.repeat(40),trustedRunnerDigest:D,sessionTimeoutMs:900000,sealDigest:D};
function setup(limit=8,file=':memory:'){let time=10000;const ledger=new Ledger(file,binding),sessions=new ManagedSessions({ledger,config:{...config,capacity:limit},now:()=>time});return {ledger,sessions,setTime:n=>time=n,close:()=>ledger.close()};}
function provider(s,runId='10',status='in_progress',observedAt=10000){return {repositoryId:'123',repositoryOwnerId:'456',runId,runAttempt:'1',headSha:s.intent.launchCommit,headBranch:s.intent.ref.slice(11),event:'push',workflowPath:'.github/workflows/dev2-executor.yml',status,observedAt};}
function identity(s){const claims={repository_id:'123',repository_owner_id:'456',ref:s.intent.ref,sha:s.intent.launchCommit,workflow_ref:s.intent.workflowRef,workflow_sha:s.intent.launchCommit,run_id:s.run.runId,run_attempt:'1',runner_environment:'github-hosted',event_name:'push'};return {kind:'github-executor',sessionId:s.intent.sessionId,installationId:'install',repositoryId:'123',runId:s.run.runId,runAttempt:'1',launchCommit:s.intent.launchCommit,expiresAt:s.intent.deadline,launchIdentity:recordDigest('dev2.execution-launch.v1',{installationId:'install',sessionId:s.intent.sessionId,...claims})};}
function active(w,name='session',runId='10'){w.sessions.reserve(name);w.sessions.markLaunchSent(name);const s=w.sessions.selectRun(name,provider(w.sessions.open().find(s=>s.intent.sessionId===name),runId));return identity(s);}
function input(w,n='a',payloadDigest=D){const a={installationId:'install',repositoryId:'repo',workId:'work_'+n,actionId:'action_'+n,attemptId:'attempt_'+n,attempt:'1',ownerEpoch:w.ledger.ownerEpoch};w.ledger.transact(tx=>{tx.insertWork({workId:a.workId,repositoryId:'repo',bindingEpoch:'1',principal:'human',baseCommitOid:O,baseTreeOid:O,candidate:{treeOid:O,manifestDigest:D},generation:'1',revision:'0',disposition:'open',currentActionId:null});tx.insertAction({actionId:a.actionId,requestId:'req_'+n,principal:'human',bindingEpoch:'1',intentDigest:D,operation:'validate',workId:a.workId,status:'queued',step:'ready',attempt:'0',ownerEpoch:w.ledger.ownerEpoch,deadline:100000,resultId:null,errorCode:null});assert.equal(tx.reserveAttempt(a,128),true);});return {attempt:a,resultId:'result_'+n,profileDigest:D,sourceManifest:D,payloadDigest,executionDigest:D,deadline:100000};}
function result(a,fields={}){return {assignmentId:a.assignmentId,leaseId:a.leaseId,inputIdentity:a.inputIdentity,sealDigest:D,trustedRunnerDigest:D,startedAt:10000,endedAt:10000,stopped:true,exitCode:0,signal:null,deadlineExceeded:false,inputDigest:D,outputDigest:D,artifacts:[],...fields};}
const equal=(a,b)=>assert.equal(canonicalJson(a),canonicalJson(b));

test('managed launch intent precedes effect; duplicate request and missing provider run never create another launch',()=>{const w=setup(1);try{const s=w.sessions.reserve('s');equal(w.sessions.reserve('s'),s);assert.equal(s.launch,'reserved');w.sessions.markLaunchSent('s');assert.throws(()=>w.sessions.reserve('other'),{code:'CAPACITY_REJECTED'});w.setTime(1000000);assert.throws(()=>w.sessions.closeUnlaunched('s'),{code:'EFFECT_UNCERTAIN'});assert.equal(w.sessions.open().length,1);}finally{w.close();}});
test('duplicate provider run, rerun, wrong repository/workflow and stale observation are rejected',()=>{const w=setup();try{const s=w.sessions.reserve('s');w.sessions.markLaunchSent('s');for(const patch of [{repositoryId:'124'},{repositoryOwnerId:'457'},{runAttempt:'2'},{event:'workflow_dispatch'},{headSha:'2'.repeat(40)},{workflowPath:'.github/workflows/candidate.yml'},{observedAt:10001}])assert.throws(()=>w.sessions.selectRun('s',{...provider(s),...patch}),{code:'UNAUTHORIZED'});const selected=w.sessions.selectRun('s',provider(s));assert.equal(selected.run.runId,'10');assert.throws(()=>w.sessions.selectRun('s',provider(s,'11')),{code:'UNAUTHORIZED'});equal(w.sessions.selectRun('s',provider(s)).run,selected.run);}finally{w.close();}});
for(const limit of [1,8,16,32])test(`managed capacity ${limit} does not alter assignment identity and one cancellation does not globally fence`,()=>{const w=setup(limit);try{const leases=[];for(let n=0;n<limit;n++){const who=active(w,'session_'+n,String(10+n)),i=input(w,String(n));const a=w.sessions.offer(who,i,[{digest:D,size:0}]);w.sessions.acknowledge(who,a.assignmentId,a.leaseId);leases.push({who,a});}assert.equal(new Set(leases.map(x=>x.a.leaseId)).size,limit);w.sessions.cancelAssignment(leases[0].a.assignmentId);if(limit>1){const {who,a}=leases[1];assert.equal(w.sessions.complete(who,result(a)).state,'complete');assert.equal(w.sessions.current(who).cancelRequested,false);}assert.throws(()=>w.sessions.reserve('over'),{code:'CAPACITY_REJECTED'});const s=w.sessions.open().find(s=>s.intent.sessionId==='session_0');w.sessions.providerStopped('session_0',provider(s,'10','completed'));assert.equal(w.sessions.reserve('replacement').state,'reserved');}finally{w.close();}});
test('assignment retry has stable lease, mismatched input is refused, and completion requires acknowledgement',()=>{const w=setup();try{const who=active(w),i=input(w),a=w.sessions.offer(who,i,[{digest:D,size:0}]);equal(w.sessions.offer(who,i,[{digest:D,size:0}]),a);assert.throws(()=>w.sessions.offer(who,{...i,deadline:99999},[{digest:D,size:0}]),{code:'IDEMPOTENCY_MISMATCH'});assert.throws(()=>w.sessions.complete(who,result(a)),{code:'STALE_RESULT'});w.sessions.acknowledge(who,a.assignmentId,a.leaseId);const done=w.sessions.complete(who,result(a));equal(w.sessions.complete(who,result(a)),done);assert.throws(()=>w.sessions.complete(who,result(a,{exitCode:1})),{code:'IDEMPOTENCY_MISMATCH'});}finally{w.close();}});
test('stale owner and unsealed containment cannot offer candidate execution',()=>{const w=setup();try{const who=active(w),i=input(w);const unsealed=new ManagedSessions({ledger:w.ledger,config:{...config,sealDigest:null},now:()=>10000});assert.throws(()=>unsealed.offer(who,i,[{digest:D,size:0}]),{code:'EXECUTION_UNAVAILABLE'});assert.throws(()=>w.sessions.offer(who,{...i,attempt:{...i.attempt,ownerEpoch:'999'}},[{digest:D,size:0}]),{code:'STALE_REVISION'});}finally{w.close();}});
test('deadline and cancellation retain exact receipt but cannot be normalized to success',()=>{const w=setup();try{const who=active(w),a=w.sessions.offer(who,input(w),[{digest:D,size:0}]);w.sessions.acknowledge(who,a.assignmentId,a.leaseId);w.sessions.cancelAssignment(a.assignmentId);w.setTime(100002);const receipt=result(a,{endedAt:100001});const done=w.sessions.complete(who,receipt);assert.equal(done.result.deadlineExceeded,true);assert.equal(done.result.signal,'SIGTERM');equal(w.sessions.complete(who,receipt),done);}finally{w.close();}});
test('native SQLite reopen retains selected run and assignment; old owner cannot mint a replacement',async()=>{const root=await mkdtemp(join(tmpdir(),'dev2-managed-ledger-'));let w;try{const file=join(root,'work.sqlite');w=setup(8,file);const who=active(w),a=w.sessions.offer(who,input(w),[{digest:D,size:0}]);w.sessions.acknowledge(who,a.assignmentId,a.leaseId);const epoch=w.ledger.ownerEpoch;w.close();w=setup(8,file);assert.notEqual(w.ledger.ownerEpoch,epoch);equal(w.sessions.current(who).assignment.input,a.input);equal(w.sessions.current(who).assignment.leaseId,a.leaseId);assert.throws(()=>w.sessions.selectRun('session',provider(w.sessions.open()[0],'11')),{code:'UNAUTHORIZED'});assert.equal(w.sessions.complete(who,result(a)).state,'complete');}finally{w?.close();await rm(root,{recursive:true,force:true});}});
test('object transport binds run, assignment, lease, bounds and digest; artifact chunks survive response loss',async()=>{const root=await mkdtemp(join(tmpdir(),'dev2-managed-objects-')),w=setup();try{const objects=new ObjectStore(join(root,'objects'));await objects.init();const payload=Buffer.from('immutable source payload'),payloadDigest=await objects.put(payload),unrelated=await objects.put(Buffer.from('private unrelated work'));const transfer=new AssignmentTransfer({sessions:w.sessions,objects});const who=active(w),a=w.sessions.offer(who,input(w,'one',payloadDigest),[{digest:payloadDigest,size:payload.length}]);const auth={identity:who,assignmentId:a.assignmentId,leaseId:a.leaseId};const chunk=await transfer.read(auth,{digest:payloadDigest,offset:0,maxBytes:65536});assert.equal(Buffer.from(chunk.data,'base64').toString(),payload.toString());await assert.rejects(transfer.read(auth,{digest:unrelated,offset:0,maxBytes:1}),{code:'FORBIDDEN'});await assert.rejects(transfer.read({...auth,leaseId:'wrong'},{digest:payloadDigest,offset:0,maxBytes:1}),{code:'UNAUTHORIZED'});await assert.rejects(transfer.read(auth,{digest:payloadDigest,offset:0,maxBytes:65537}),{code:'INVALID_ARGUMENT'});w.sessions.acknowledge(who,a.assignmentId,a.leaseId);const artifact=Buffer.alloc(70000,37),artifactDigest=bytesDigest(artifact),first={digest:artifactDigest,size:artifact.length,offset:0,data:artifact.subarray(0,65536).toString('base64')};equal(await transfer.upload(auth,first),{digest:artifactDigest,received:65536,complete:false});equal(await transfer.upload(auth,first),{digest:artifactDigest,received:65536,complete:false});const final={digest:artifactDigest,size:artifact.length,offset:65536,data:artifact.subarray(65536).toString('base64')};assert.equal((await transfer.upload(auth,final)).complete,true);assert.equal((await transfer.upload(auth,final)).complete,true);assert.equal(bytesDigest(await objects.get(artifactDigest)),artifactDigest);assert.equal(w.sessions.complete(who,result(a,{artifacts:[artifactDigest]})).state,'complete');}finally{w.close();await rm(root,{recursive:true,force:true});}});
test('wrong whole artifact digest never publishes ready completion',async()=>{const root=await mkdtemp(join(tmpdir(),'dev2-managed-invalid-')),w=setup();try{const objects=new ObjectStore(root);await objects.init();const transfer=new AssignmentTransfer({sessions:w.sessions,objects}),who=active(w),a=w.sessions.offer(who,input(w),[{digest:D,size:0}]);w.sessions.acknowledge(who,a.assignmentId,a.leaseId);const auth={identity:who,assignmentId:a.assignmentId,leaseId:a.leaseId};await assert.rejects(transfer.upload(auth,{digest:D,size:3,offset:0,data:Buffer.from('bad').toString('base64')}),{code:'INTEGRITY_FAILURE'});assert.throws(()=>w.sessions.complete(who,result(a,{artifacts:[D]})),{code:'INTEGRITY_FAILURE'});}finally{w.close();await rm(root,{recursive:true,force:true});}});
