import test from 'node:test';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
import {productionFixture,D} from './production-fixture.mjs';
import {ManagedReleaseBuilder} from '../../src/release/managed-builder.mjs';
import {canonicalJson} from '../../src/contracts/canonical.mjs';
async function setup(){const f=await productionFixture();f.useProductionSeal();const production=await f.enrolled(),options={production,pool:f.pool,objects:f.objects,installationSealDigest:D(5)},builder=new ManagedReleaseBuilder(options);return {f,builder,options};}
test('resumed action cannot replace a pending first build assignment, and cancellation retains its identity',async()=>{const {f,builder,options}=await setup();try{f.create('pending',builder.profile,true);const input=builder.input('pending',f.integrated,f.previous),dispatch=await f.pool.dispatch(input.result,input.attempt,builder.profile);const auth=f.activate(dispatch.sessionId),a=f.pool.poll(auth).assignment;f.sessions.acknowledge(auth,a.assignmentId,a.leaseId);f.restart();const production=await f.enrolled(),next=new ManagedReleaseBuilder({...options,production,pool:f.pool});f.ledger.transact(tx=>{const action=tx.getAction('pending');tx.adoptAttempt('pending');tx.updateAction({...action,ownerEpoch:f.ledger.ownerEpoch,attempt:'2'});});await assert.rejects(next.build('pending',f.integrated,f.previous),{code:'STALE_REVISION'});assert.equal(f.pool.dispatches(input.attempt).length,1);assert.equal(next.retained('pending').attempt.attemptId,input.attempt.attemptId);await next.cancel('pending');assert.equal(await next.stopped('pending'),true);assert.equal(f.pool.dispatches(input.attempt)[0].assignmentId,dispatch.assignmentId);}finally{await f.close();}});
test('partially uploaded completed artifact cannot recover as a verified build',async()=>{const {f,builder}=await setup();try{const build=await execute(f,builder);const input=builder.retained('stage'),dispatch=f.pool.dispatches(input.attempt)[0];f.ledger.transact(tx=>tx.run("UPDATE managed_artifact SET state='uploading' WHERE assignment_id=? AND digest=?",dispatch.assignmentId,build.refs.edge));assert.equal(await builder.verify(build,f.integrated,f.previous),false);await assert.rejects(builder.build('stage',f.integrated,f.previous),{code:'INTEGRITY_FAILURE'});assert.equal(f.pool.dispatches(input.attempt).length,1);}finally{await f.close();}});
async function execute(f,builder,action='stage',mutate){f.create(action,builder.profile,true);const pending=builder.build(action,f.integrated,f.previous),duplicate=builder.build(action,f.integrated,f.previous);assert.equal(pending,duplicate);await assert.rejects(builder.build(action,f.integrated,{...f.previous,edgeVersionId:'substituted'}),{code:'IDEMPOTENCY_MISMATCH'});const deadline=Date.now()+3000;let dispatch;while(!(dispatch=f.pool.dispatches({attemptId:action})[0])){assert.ok(Date.now()<deadline);await delay(10);}while(!f.ledger.transact(tx=>f.sessions.session(tx,dispatch.sessionId)).run){assert.ok(Date.now()<deadline);await delay(10);}
 // The fixture's activate supplies the exact native launch identity. Use its
 // already selected identity rather than any public/client-supplied assignment.
 const auth=f.activate(dispatch.sessionId);const a=f.pool.poll(auth).assignment;await f.complete(a,builder.profile,mutate);return pending;}
test('finite builder is capability gated and duplicate/response-loss/restart reuse one assignment',async()=>{const {f,builder,options}=await setup();try{assert.throws(()=>new ManagedReleaseBuilder({...options,production:{sealDigest:D(1)}}),{code:'EXECUTION_UNAVAILABLE'});const build=await execute(f,builder);assert.deepEqual(Object.keys(build.refs).sort(),['device','edge','tools']);assert.equal(await builder.verify(build,f.integrated,f.previous),true);const count=f.counts();assert.equal(canonicalJson(await builder.build('stage',f.integrated,f.previous)),canonicalJson(build));assert.deepEqual(f.counts(),count);f.restart();const production=await f.enrolled(),next=new ManagedReleaseBuilder({...options,production,pool:f.pool});f.ledger.transact(tx=>{const action=tx.getAction('stage');tx.updateAction({...action,ownerEpoch:f.ledger.ownerEpoch,attempt:'2'});});assert.equal(canonicalJson(await next.build('stage',f.integrated,f.previous)),canonicalJson(build));assert.deepEqual(f.counts(),count);assert.equal(await next.verify(build,f.integrated,f.previous),true);assert.equal(await builder.verify(build,f.integrated,f.previous),false,'old native owner fenced');}finally{await f.close();}});
test('builder rejects changed manifest/source/previous pair and corrupted artifact',async()=>{const {f,builder}=await setup();try{const build=await execute(f,builder);for(const mutate of [b=>b.manifest.device.artifactDigest=D(0),b=>b.refs.tools=D(0),b=>b.receipt.proof.eligible=false,b=>b.receipt.proof.providerRunId='wrong']){const b=structuredClone(build);mutate(b);assert.equal(await builder.verify(b,f.integrated,f.previous),false);}assert.equal(await builder.verify(build,{...f.integrated,validationId:D(9)},f.previous),false);assert.equal(await builder.verify(build,f.integrated,{...f.previous,edgeVersionId:'different'}),false);const get=f.objects.get.bind(f.objects);f.objects.get=async digest=>digest===build.refs.device?Buffer.from('changed bytes'):get(digest);assert.equal(await builder.verify(build,f.integrated,f.previous),false);}finally{await f.close();}});
test('missing kernel, invalid isolation, timeout and failed execution block finite builds',async()=>{for(const mutate of [o=>o.after=null,o=>o.isolation.networkNone=false,o=>o.command.timedOut=true,o=>o.command.exitCode=1,o=>o.command.discardedBytes=1]){const {f,builder}=await setup();try{await assert.rejects(execute(f,builder,'stage',mutate),{code:'VALIDATION_FAILED'});}finally{await f.close();}}});
test('cancelled/stale release action never dispatches a build',async()=>{const {f,builder}=await setup();try{for(const name of ['cancelled','stale','expired']){f.create(name,builder.profile,true);f.ledger.transact(tx=>{const a=tx.getAction(name);if(name==='cancelled')tx.run('INSERT INTO meta VALUES(?,?)','cancel:'+name,'true');else tx.run('UPDATE action SET record=? WHERE action_id=?',canonicalJson({...a,...(name==='stale'?{ownerEpoch:'999'}:{deadline:1})}),name);});await assert.rejects(builder.build(name,f.integrated,f.previous),{code:'STALE_REVISION'});}assert.equal(f.counts().launches,0);}finally{await f.close();}});
