import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import {Ledger} from '../../src/storage/ledger.mjs';
import {ObjectStore} from '../../src/storage/objects.mjs';
import {ManagedSessions} from '../../src/execution/sessions.mjs';
import {ManagedPool} from '../../src/execution/managed-pool.mjs';
import {sourceManifest} from '../../src/repository/entries.mjs';
import {recordDigest,bytesDigest} from '../../src/contracts/canonical.mjs';
const D='sha256:'+'1'.repeat(64),O='sha1:'+'1'.repeat(40),C='1'.repeat(40);
function who(s){const i=s.intent;return {kind:'github-executor',sessionId:i.sessionId,installationId:i.installationId,repositoryId:i.providerRepositoryId,runId:s.run.runId,runAttempt:'1',launchCommit:i.launchCommit,expiresAt:i.deadline,launchIdentity:recordDigest('dev2.execution-launch.v1',{installationId:i.installationId,sessionId:i.sessionId,repository_id:i.providerRepositoryId,repository_owner_id:i.repositoryOwnerId,ref:i.ref,sha:i.launchCommit,workflow_ref:i.workflowRef,workflow_sha:i.launchCommit,run_id:s.run.runId,run_attempt:'1',runner_environment:'github-hosted',event_name:'push'})};}
async function fixture(capacity=8){const root=await mkdtemp(join(tmpdir(),'dev2-pool-')),binding={installationId:'i',repositoryId:'r',providerRepositoryId:'123',bindingEpoch:'1',provider:'github',remote:'https://github.com/fixture/repo.git',ref:'refs/heads/dev-2',policyDigest:D},ledger=new Ledger(join(root,'state.sqlite'),binding),objects=new ObjectStore(join(root,'objects'));await objects.init();const sessions=new ManagedSessions({ledger,config:{repositoryOwnerId:'456',repositoryFullName:'fixture/repo',approvedCommit:C,trustedRunnerDigest:D,sessionTimeoutMs:900000,capacity,sealDigest:D}});
 const bytes=Buffer.from('export const value=1;\n'),blobOid='sha1:'+createHash('sha1').update('blob '+bytes.length+'\0').update(bytes).digest('hex'),entry={path:'source.mjs',mode:'100644',blobOid,contentDigest:bytesDigest(bytes),size:bytes.length},source={treeOid:O,manifestDigest:sourceManifest([entry]),entries:[entry]};
 const definition={profileId:'core',argv:['/usr/local/bin/node','--check','/source/source.mjs'],cwd:'',parameters:{},timeoutMs:1000,killGraceMs:1000,memoryBytes:67108864,pids:48,cpuMillis:1000,diskBytes:8388608,logBytes:65536,network:'none',imageDigest:D,replaySafe:true},profile={...definition,digest:recordDigest('dev2.profile.v1',definition)},execution={orderedProfileDigests:[profile.digest],trustedRunnerDigest:D,toolchainDigest:D,environmentClass:'fixture',dependencyLockDigest:D};
 let sequence=10;const launched=[],active=new Map(),provider={launch:async sid=>{let s=sessions.ledger.transact(tx=>sessions.session(tx,sid));if(s.run)return {state:'present',session:s};sessions.markLaunchSent(sid);s=sessions.selectRun(sid,{repositoryId:'123',repositoryOwnerId:'456',runId:String(sequence++),runAttempt:'1',headSha:C,headBranch:s.intent.ref.slice(11),event:'push',workflowPath:'.github/workflows/dev2-executor.yml',status:'in_progress',observedAt:Date.now()});launched.push(sid);active.set(sid,who(s));return {state:'present',session:s};},refresh:async sid=>sessions.ledger.transact(tx=>sessions.session(tx,sid)),cancel:async sid=>{let s=sessions.cancelSession(sid);if(s.launch==='reserved')return sessions.closeUnlaunched(sid);if(s.run)return sessions.providerStopped(sid,{...s.run,status:'completed',observedAt:Date.now()});return s;}};
 const repository={blob:async id=>{assert.equal(id,blobOid);return bytes;},readCommit:async()=>({commitOid:O,source,parents:[]})},pool=new ManagedPool({sessions,provider,repository,objects,pollMs:10});
 const create=n=>{const attempt={installationId:'i',repositoryId:'r',workId:'work_'+n,actionId:'action_'+n,attemptId:'attempt_'+n,attempt:'1',ownerEpoch:ledger.ownerEpoch};ledger.transact(tx=>{tx.insertWork({workId:attempt.workId,repositoryId:'r',bindingEpoch:'1',principal:'human',baseCommitOid:O,baseTreeOid:O,candidate:{treeOid:O,manifestDigest:source.manifestDigest},generation:'1',revision:'0',disposition:'open',currentActionId:attempt.actionId});tx.insertAction({actionId:attempt.actionId,requestId:'request_'+n,principal:'human',bindingEpoch:'1',intentDigest:D,operation:'validate',workId:attempt.workId,status:'running',step:'executing',attempt:'0',ownerEpoch:ledger.ownerEpoch,deadline:Date.now()+600000,resultId:'result_'+n,errorCode:null});assert.equal(tx.reserveAttempt(attempt,capacity),true);});const result={resultId:'result_'+n,repositoryId:'r',bindingEpoch:'1',workId:attempt.workId,candidateGeneration:'1',candidateBaseOid:O,preparedParentOid:O,resultTreeOid:O,resultTreeSha256:source.manifestDigest,commitOid:O,policyDigest:D,execution,changeManifestDigest:D,recordDigest:D};return {attempt,result};};
 const acknowledge=sid=>{const identity=active.get(sid),current=pool.poll(identity),a=current.assignment;assert.ok(a);sessions.acknowledge(identity,a.assignmentId,a.leaseId);return a;};
 const complete=(sid,a,exitCode=0)=>sessions.complete(active.get(sid),{assignmentId:a.assignmentId,leaseId:a.leaseId,inputIdentity:a.inputIdentity,sealDigest:D,trustedRunnerDigest:D,startedAt:Date.now(),endedAt:Date.now(),stopped:true,exitCode,signal:null,deadlineExceeded:false,inputDigest:source.manifestDigest,outputDigest:source.manifestDigest,artifacts:[]});
 return {root,ledger,sessions,pool,objects,profile,launched,active,create,acknowledge,complete,close:async()=>{ledger.close();await rm(root,{recursive:true,force:true});}};
}
async function until(check){const deadline=Date.now()+3000;while(!check()){assert.ok(Date.now()<deadline,'fixture progress deadline');await delay(10);}}
test('idle retirement is native-ordered and duplicate retirement cannot reopen a resource',async()=>{const f=await fixture(2);try{const a=f.create('retire_a'),first=f.pool.run(a.result,a.attempt,f.profile);await until(()=>f.launched.length===1);const sid=f.launched[0],assigned=f.acknowledge(sid);f.complete(sid,assigned);await first;f.ledger.transact(tx=>tx.releaseAttempt(a.attempt.attemptId,f.ledger.ownerEpoch));const identity=f.active.get(sid);assert.equal(f.pool.retire(identity).cancelRequested,true);assert.equal(f.pool.retire(identity).cancelRequested,true);const b=f.create('retire_b'),second=f.pool.run(b.result,b.attempt,f.profile);await until(()=>f.launched.length===2);const next=f.launched[1];assert.notEqual(next,sid);f.complete(next,f.acknowledge(next));assert.equal((await second).exitCode,0);assert.equal(f.sessions.ledger.transact(tx=>f.sessions.session(tx,sid)).state,'closing');}finally{await f.close();}});
test('a dispatch racing idle retirement receives its existing assignment instead of an idle exit',async()=>{const f=await fixture(1);try{const a=f.create('race_a'),first=f.pool.run(a.result,a.attempt,f.profile);await until(()=>f.launched.length===1);const sid=f.launched[0];f.complete(sid,f.acknowledge(sid));await first;f.ledger.transact(tx=>tx.releaseAttempt(a.attempt.attemptId,f.ledger.ownerEpoch));const b=f.create('race_b'),second=f.pool.run(b.result,b.attempt,f.profile);await until(()=>f.pool.dispatches(b.attempt).length===1);const current=f.pool.retire(f.active.get(sid));assert.equal(current.cancelRequested,false);assert.equal(current.assignment.input.attempt.workId,b.attempt.workId);assert.equal(f.pool.retire(f.active.get(sid)).assignment.assignmentId,current.assignment.assignmentId);f.complete(sid,f.acknowledge(sid));assert.equal((await second).exitCode,0);assert.equal(f.launched.length,1);}finally{await f.close();}});
test('proved terminal never-offered session is replaced without changing input or work attempt',async()=>{const f=await fixture(1);try{const w=f.create('replace'),run=f.pool.run(w.result,w.attempt,f.profile);await until(()=>f.launched.length===1);const old=f.pool.dispatches(w.attempt)[0],s=f.sessions.ledger.transact(tx=>f.sessions.session(tx,old.sessionId));assert.equal(f.pool.assignment(old.assignmentId),null);f.sessions.providerStopped(old.sessionId,{...s.run,status:'completed',observedAt:Date.now()});await until(()=>f.launched.length===2);const next=f.pool.dispatches(w.attempt)[0];assert.equal(next.assignmentId,old.assignmentId);assert.deepEqual(next.input,old.input);assert.deepEqual(next.priorSessionIds,[old.sessionId]);assert.notEqual(next.sessionId,old.sessionId);f.complete(next.sessionId,f.acknowledge(next.sessionId));assert.equal((await run).exitCode,0);assert.equal(f.pool.dispatches(w.attempt).length,1);}finally{await f.close();}});
test('uncertain or previously offered execution never receives a replacement resource',async()=>{const f=await fixture(1);try{const w=f.create('uncertain'),run=f.pool.run(w.result,w.attempt,f.profile),failed=assert.rejects(run,{code:'EXECUTION_UNAVAILABLE'});await until(()=>f.launched.length===1);const d=f.pool.dispatches(w.attempt)[0];assert.throws(()=>f.pool.replaceUnassigned(d,w.attempt,f.profile),{code:'EXECUTION_UNAVAILABLE'});f.acknowledge(d.sessionId);const s=f.sessions.ledger.transact(tx=>f.sessions.session(tx,d.sessionId));f.sessions.providerStopped(d.sessionId,{...s.run,status:'completed',observedAt:Date.now()});assert.throws(()=>f.pool.replaceUnassigned(d,w.attempt,f.profile),{code:'EXECUTION_UNAVAILABLE'});await failed;assert.equal(f.launched.length,1);}finally{await f.close();}});
test('durable cancellation intent forbids terminal never-offered resource replacement',async()=>{const f=await fixture(1);try{const w=f.create('cancel_replace'),run=f.pool.run(w.result,w.attempt,f.profile),failed=assert.rejects(run,{code:'EXECUTION_UNAVAILABLE'});await until(()=>f.launched.length===1);const d=f.pool.dispatches(w.attempt)[0],s=f.sessions.ledger.transact(tx=>f.sessions.session(tx,d.sessionId));assert.equal(f.pool.assignment(d.assignmentId),null);f.ledger.transact(tx=>tx.run('INSERT INTO meta(key,value) VALUES(?,?)','cancel:'+w.attempt.actionId,'true'));f.sessions.providerStopped(d.sessionId,{...s.run,status:'completed',observedAt:Date.now()});assert.throws(()=>f.pool.replaceUnassigned(d,w.attempt,f.profile),{code:'EXECUTION_UNAVAILABLE'});await failed;const retained=f.pool.dispatches(w.attempt)[0];assert.equal(f.launched.length,1);assert.equal(f.ledger.transact(tx=>Number(tx.get('SELECT count(*) AS n FROM managed_session').n)),1);assert.equal(retained.assignmentId,d.assignmentId);assert.equal(retained.sessionId,d.sessionId);assert.deepEqual(retained.input,d.input);assert.deepEqual({...retained.input.attempt},w.attempt);}finally{await f.close();}});
test('resource replacement cannot extend the original assignment deadline',async()=>{const f=await fixture(1);try{const w=f.create('deadline'),run=f.pool.run(w.result,w.attempt,f.profile),failed=assert.rejects(run,{code:'EXECUTION_UNAVAILABLE'});await until(()=>f.launched.length===1);const d=f.pool.dispatches(w.attempt)[0],s=f.sessions.ledger.transact(tx=>f.sessions.session(tx,d.sessionId));f.pool.now=()=>d.input.deadline-500;f.sessions.providerStopped(d.sessionId,{...s.run,status:'completed',observedAt:Date.now()});assert.throws(()=>f.pool.replaceUnassigned(d,w.attempt,f.profile),{code:'EXECUTION_UNAVAILABLE'});await failed;assert.equal(f.launched.length,1);assert.equal(f.pool.dispatches(w.attempt)[0].input.deadline,d.input.deadline);}finally{await f.close();}});
test('eight native durable dispatches overlap with isolated work identities; one failure does not block the others',async()=>{const f=await fixture();try{const works=Array.from({length:8},(_,n)=>f.create(n)),runs=works.map(w=>f.pool.run(w.result,w.attempt,f.profile));await until(()=>f.launched.length===8);const assignments=f.launched.map(sid=>f.acknowledge(sid));assert.equal(new Set(assignments.map(a=>a.input.attempt.workId)).size,8);assert.equal(new Set(assignments.map(a=>a.leaseId)).size,8);assert.equal(new Set(assignments.map(a=>a.input.resultId)).size,8);f.launched.forEach((sid,n)=>f.complete(sid,assignments[n],assignments[n].input.attempt.workId===works[0].attempt.workId?1:0));const results=await Promise.all(runs);assert.equal(results.filter(r=>r.exitCode===0).length,7);assert.equal(results.filter(r=>r.exitCode===1).length,1);assert.equal((await f.pool.run(works[1].result,works[1].attempt,f.profile)).exitCode,0);assert.equal(f.launched.length,8);assert.equal(await f.pool.stopped(works[0].attempt),true);}finally{await f.close();}});
test('warm session reuse changes assignment lease but not the work attempt and does not relaunch provider',async()=>{const f=await fixture(1);try{const a=f.create('a'),first=f.pool.run(a.result,a.attempt,f.profile);await until(()=>f.launched.length===1);const sid=f.launched[0],assigned=f.acknowledge(sid);f.complete(sid,assigned);await first;f.ledger.transact(tx=>tx.releaseAttempt(a.attempt.attemptId,f.ledger.ownerEpoch));const b=f.create('b'),second=f.pool.run(b.result,b.attempt,f.profile);await until(()=>f.pool.dispatches(b.attempt).length===1);const next=f.acknowledge(sid);assert.notEqual(next.leaseId,assigned.leaseId);assert.equal(next.sessionId,assigned.sessionId);f.complete(sid,next);await second;assert.equal(f.launched.length,1);}finally{await f.close();}});
test('cancelled physical assignment is stopped before held work can recover; unrelated session still succeeds',async()=>{const f=await fixture(2);try{const a=f.create('a'),b=f.create('b'),first=f.pool.run(a.result,a.attempt,f.profile),second=f.pool.run(b.result,b.attempt,f.profile);const failed=assert.rejects(first,{code:'EXECUTION_UNAVAILABLE'});await until(()=>f.launched.length===2);const assigned=f.launched.map(sid=>f.acknowledge(sid)),da=f.pool.dispatches(a.attempt)[0],db=f.pool.dispatches(b.attempt)[0];assert.equal(await f.pool.stopped(a.attempt),false);assert.equal(await f.pool.cancel(a.attempt),true);const other=assigned.find(v=>v.sessionId===db.sessionId);f.complete(db.sessionId,other);await failed;assert.equal((await second).exitCode,0);assert.notEqual(da.sessionId,db.sessionId);}finally{await f.close();}});
