import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Ledger} from '../../src/storage/ledger.mjs';
import {ManagedSessions} from '../../src/execution/sessions.mjs';
import {ManagedTargets,managedTarget} from '../../src/execution/managed-targets.mjs';
import {recordDigest} from '../../src/contracts/canonical.mjs';

const D='sha256:'+'1'.repeat(64),C='1'.repeat(40);
function executor(session){const i=session.intent;return {kind:'github-executor',sessionId:i.sessionId,installationId:i.installationId,repositoryId:i.providerRepositoryId,runId:session.run.runId,runAttempt:'1',launchCommit:i.launchCommit,expiresAt:i.deadline,launchIdentity:recordDigest('dev2.execution-launch.v1',{installationId:i.installationId,sessionId:i.sessionId,repository_id:i.providerRepositoryId,repository_owner_id:i.repositoryOwnerId,ref:i.ref,sha:i.launchCommit,workflow_ref:i.workflowRef,workflow_sha:i.launchCommit,run_id:session.run.runId,run_attempt:'1',runner_environment:'github-hosted',event_name:'push'})};}
async function fixture(){
 const root=await mkdtemp(join(tmpdir(),'tdev-managed-target-')),controller={installationId:'installation',repositoryId:'controller',providerRepositoryId:'123',bindingEpoch:'1',provider:'github',remote:'https://github.com/fixture/controller.git',ref:'refs/heads/dev-2',policyDigest:D},target={installationId:'installation',repositoryId:'target',providerRepositoryId:'789',bindingEpoch:'7',provider:'github',remote:'https://github.com/fixture/target.git',ref:'refs/heads/target',policyDigest:D};
 const controllerLedger=new Ledger(join(root,'controller.sqlite'),controller),targetLedger=new Ledger(join(root,'target.sqlite'),target),targets=new ManagedTargets(controller,controllerLedger).register(target,targetLedger),sessions=new ManagedSessions({ledger:controllerLedger,targets,config:{repositoryOwnerId:'456',repositoryFullName:'fixture/controller',approvedCommit:C,trustedRunnerDigest:D,workflowPath:'.github/workflows/dev2-executor.yml',sessionTimeoutMs:900000,capacity:8,sealDigest:D}});
 let run=10;
 const active=()=>{let s=sessions.reserve('session_'+run);sessions.markLaunchSent(s.intent.sessionId);s=sessions.selectRun(s.intent.sessionId,{repositoryId:controller.providerRepositoryId,repositoryOwnerId:'456',runId:String(run++),runAttempt:'1',headSha:C,headBranch:s.intent.ref.slice(11),event:'push',workflowPath:'.github/workflows/dev2-executor.yml',status:'in_progress',observedAt:Date.now()});return {session:s,identity:executor(s)};};
 const hold=(ledger,binding,name)=>{const attempt={installationId:binding.installationId,repositoryId:binding.repositoryId,workId:'work_'+name,actionId:'action_'+name,attemptId:'attempt_'+name,attempt:'1',ownerEpoch:ledger.ownerEpoch};ledger.transact(tx=>{tx.insertWork({workId:attempt.workId,repositoryId:binding.repositoryId,bindingEpoch:binding.bindingEpoch,principal:'human',baseCommitOid:'sha1:'+'1'.repeat(40),baseTreeOid:'sha1:'+'2'.repeat(40),candidate:{treeOid:'sha1:'+'2'.repeat(40),manifestDigest:D},generation:'0',revision:'0',disposition:'open',currentActionId:attempt.actionId});tx.insertAction({actionId:attempt.actionId,requestId:'request_'+name,principal:'human',bindingEpoch:binding.bindingEpoch,intentDigest:D,operation:'validate',workId:attempt.workId,status:'running',step:'executing',attempt:'0',ownerEpoch:ledger.ownerEpoch,deadline:Date.now()+600000,resultId:'result_'+name,errorCode:null});assert.equal(tx.reserveAttempt(attempt,8),true);});return attempt;};
 const input=(attempt,binding,name,withTarget=true)=>({attempt,resultId:'result_'+name,profileDigest:D,sourceManifest:D,payloadDigest:D,executionDigest:D,deadline:Date.now()+60000,...(withTarget?{target:managedTarget(binding)}:{})});
 return {root,controller,target,controllerLedger,targetLedger,targets,sessions,active,hold,input,close:async()=>{controllerLedger.close();targetLedger.close();await rm(root,{recursive:true,force:true});}};
}

test('controller session offers an exact target-owned assignment without cloning managed ownership',async()=>{const f=await fixture();try{const attempt=f.hold(f.targetLedger,f.target,'positive'),{session,identity}=f.active(),input=f.input(attempt,f.target,'positive');const assigned=f.sessions.offer(identity,input,[{digest:D,size:0}]);assert.equal(session.intent.repositoryId,f.controller.repositoryId);assert.equal(assigned.input.target.repositoryId,f.target.repositoryId);assert.equal(assigned.input.target.bindingEpoch,f.target.bindingEpoch);assert.equal(assigned.input.target.ref,f.target.ref);const running=f.sessions.acknowledge(identity,assigned.assignmentId,assigned.leaseId);assert.equal(running.state,'running');const receipt={assignmentId:assigned.assignmentId,leaseId:assigned.leaseId,inputIdentity:assigned.inputIdentity,sealDigest:D,trustedRunnerDigest:D,startedAt:Date.now(),endedAt:Date.now(),stopped:true,exitCode:0,signal:null,deadlineExceeded:false,inputDigest:D,outputDigest:D,artifacts:[]},completed=f.sessions.complete(identity,receipt);assert.equal(completed.state,'complete');f.targetLedger.transact(tx=>tx.releaseAttempt(attempt.attemptId,f.targetLedger.ownerEpoch));assert.equal(recordDigest('dev2.test.managed-replay.v1',f.sessions.complete(identity,receipt)),recordDigest('dev2.test.managed-replay.v1',completed));assert.equal(f.targetLedger.transact(tx=>tx.get("SELECT name FROM sqlite_master WHERE type='table' AND name='managed_session'")),undefined);}finally{await f.close();}});

test('target tuple changes and stale target owners are rejected before lease acceptance',async()=>{const f=await fixture();try{const wrongAttempt=f.hold(f.targetLedger,f.target,'wrong'),first=f.active(),wrong={...f.input(wrongAttempt,f.target,'wrong'),target:{...managedTarget(f.target),ref:'refs/heads/wrong'}};assert.throws(()=>f.sessions.offer(first.identity,wrong,[{digest:D,size:0}]),{code:'FORBIDDEN'});const attempt=f.hold(f.targetLedger,f.target,'stale'),second=f.active(),input=f.input(attempt,f.target,'stale'),assigned=f.sessions.offer(second.identity,input,[{digest:D,size:0}]);f.targetLedger.transact(tx=>tx.releaseAttempt(attempt.attemptId,f.targetLedger.ownerEpoch));assert.throws(()=>f.sessions.acknowledge(second.identity,assigned.assignmentId,assigned.leaseId),{code:'STALE_REVISION'});const retained=f.controllerLedger.transact(tx=>f.sessions.assignment(tx,assigned.assignmentId));assert.equal(retained.state,'offered');}finally{await f.close();}});

test('retained target ownership is rechecked again before accepting an execution result',async()=>{const f=await fixture();try{const attempt=f.hold(f.targetLedger,f.target,'result'),{identity}=f.active(),input=f.input(attempt,f.target,'result'),assigned=f.sessions.offer(identity,input,[{digest:D,size:0}]);f.sessions.acknowledge(identity,assigned.assignmentId,assigned.leaseId);f.targetLedger.transact(tx=>tx.releaseAttempt(attempt.attemptId,f.targetLedger.ownerEpoch));assert.throws(()=>f.sessions.complete(identity,{assignmentId:assigned.assignmentId,leaseId:assigned.leaseId,inputIdentity:assigned.inputIdentity,sealDigest:D,trustedRunnerDigest:D,startedAt:Date.now(),endedAt:Date.now(),stopped:true,exitCode:0,signal:null,deadlineExceeded:false,inputDigest:D,outputDigest:D,artifacts:[]}),{code:'STALE_REVISION'});const retained=f.controllerLedger.transact(tx=>f.sessions.assignment(tx,assigned.assignmentId));assert.equal(retained.state,'running');}finally{await f.close();}});

test('legacy target-less assignment compatibility is controller-only',async()=>{const f=await fixture();try{const controllerAttempt=f.hold(f.controllerLedger,f.controller,'legacy'),first=f.active();assert.equal(f.sessions.offer(first.identity,f.input(controllerAttempt,f.controller,'legacy',false),[{digest:D,size:0}]).input.target,undefined);const targetAttempt=f.hold(f.targetLedger,f.target,'legacy_target'),second=f.active();assert.throws(()=>f.sessions.offer(second.identity,f.input(targetAttempt,f.target,'legacy_target',false),[{digest:D,size:0}]),{code:'FORBIDDEN'});}finally{await f.close();}});

test('active policy projection advances managed target views without rewriting durable binding rows',async()=>{const f=await fixture();try{const next='sha256:'+'2'.repeat(64),controllerRow=JSON.parse(f.controllerLedger.transact(tx=>tx.get('SELECT record FROM binding').record)),targetRow=JSON.parse(f.targetLedger.transact(tx=>tx.get('SELECT record FROM binding').record));assert.equal(f.targets.projectPolicyDigest(next),next);for(const view of [f.targets.controllerBinding,f.targets.owner(f.controller.repositoryId).binding,f.targets.owner(f.target.repositoryId).binding,f.controllerLedger.binding,f.targetLedger.binding])assert.equal(view.policyDigest,next);assert.equal(controllerRow.policyDigest,D);assert.equal(targetRow.policyDigest,D);assert.equal(JSON.parse(f.controllerLedger.transact(tx=>tx.get('SELECT record FROM binding').record)).policyDigest,D);assert.equal(JSON.parse(f.targetLedger.transact(tx=>tx.get('SELECT record FROM binding').record)).policyDigest,D);}finally{await f.close();}});
