import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
for(const mode of ['unenrolled','qualified','production'])test('native main composition: '+mode,()=>{const result=spawnSync(process.execPath,['--experimental-test-module-mocks',fileURLToPath(new URL('./native-main-fixture.mjs',import.meta.url)),mode],{encoding:'utf8',timeout:30000,maxBuffer:1048576});assert.equal(result.status,0,result.stdout+result.stderr);});

test('native main rejects a primary sender missing the current tdev token locator',()=>{const result=spawnSync(process.execPath,['--experimental-test-module-mocks',fileURLToPath(new URL('./native-main-fixture.mjs',import.meta.url)),'missing-sender-token'],{encoding:'utf8',timeout:30000,maxBuffer:1048576});assert.notEqual(result.status,0,result.stdout+result.stderr);});
test('native main rejects a secondary sender missing the current tdev token locator',()=>{const result=spawnSync(process.execPath,['--experimental-test-module-mocks',fileURLToPath(new URL('./native-main-fixture.mjs',import.meta.url)),'missing-secondary-sender-token'],{encoding:'utf8',timeout:30000,maxBuffer:1048576});assert.notEqual(result.status,0,result.stdout+result.stderr);});
test('native main retains closed startup failure telemetry on stdout',()=>{const main=fileURLToPath(new URL('../../tools/device-main.mjs',import.meta.url)),result=spawnSync(process.execPath,[main,'--config','/definitely/missing/tdev-native-config.json'],{encoding:'utf8',timeout:30000,maxBuffer:1048576});assert.notEqual(result.status,0,result.stdout+result.stderr);assert.equal(result.stderr,'');const lines=result.stdout.trim().split('\n').filter(Boolean);assert.equal(lines.length,1);const event=JSON.parse(lines[0]);assert.deepEqual(Object.keys(event).sort(),['code','event','message']);assert.equal(event.event,'startup_failed');assert.equal(typeof event.code,'string');assert.equal(typeof event.message,'string');assert.ok(event.message.length>0&&event.message.length<=512);});
