import test from 'node:test';
import assert from 'node:assert/strict';
import {verifyProductionQualification} from '../../src/execution/production-qualification.mjs';
import {releaseBuildProfile} from '../../src/release/build-profile.mjs';
import {canonicalJson,bytesDigest,recordDigest} from '../../src/contracts/canonical.mjs';
const D='sha256:'+'1'.repeat(64),E='sha256:'+'2'.repeat(64),S='3'.repeat(40),O='sha1:'+'4'.repeat(40);
function fixture(){const definitions=['core','integration'].map(profileId=>({profileId,argv:['/usr/local/bin/node','/controller/tools/validate.mjs',profileId],cwd:'',parameters:{},timeoutMs:300000,killGraceMs:2000,memoryBytes:1073741824,pids:256,cpuMillis:2000,diskBytes:268435456,logBytes:1048576,network:'none',imageDigest:D,replaySafe:true})),required=definitions.map(p=>({...p,digest:recordDigest('dev2.profile.v1',p)})),profiles=[...required,releaseBuildProfile(D)],identities={trustedRunnerDigest:D,controllerDigest:D,toolchainDigest:D,dependencyLockDigest:D,workflowDigest:D,imageDigest:D,seccompDigest:D},source={treeOid:O,manifestDigest:D,entries:[]},definition={identities,policy:{required:()=>required}},qualificationIdentity=recordDigest('dev2.production-qualification-only.v1',{sourceCommit:S,trustedRunnerDigest:D,runId:'123'}),report={schemaVersion:1,kind:'real-production-adapter-qualification',sourceCommit:S,sourceTree:O,sourceManifest:D,runId:'123',runAttempt:'1',qualificationIdentity,identities,engineDigest:D,dependencyArtifactDigest:D,profiles:[],negative:{},status:'passed',productionSeal:false,productionValidation:false,nativeAssignmentVerified:false};
 function evidence(p,name){const container='dev2-'+name,assignmentId='assignment-'+name,inputIdentity=recordDigest('dev2.fixture-input.v1',{name}),before={container,pid:1001,cgroup:'/fixture/'+name,observedAt:1010,memoryEvents:{oom:0,oom_kill:0},limits:{memoryBytes:p.memoryBytes,pids:p.pids,cpuQuota:200000,cpuPeriod:100000}},outer={schemaVersion:1,kind:'dev2-production-execution',assignmentId,leaseId:'lease-'+name,inputIdentity,sessionId:'session',runId:'123',sealDigest:qualificationIdentity,trustedRunnerDigest:D,profileDigest:p.digest,container,startedAt:1000,endedAt:1030,command:{argvDigest:recordDigest('dev2.executed-argv.v1',p.argv),exitCode:0,signal:null,timedOut:false,spawnFailed:false,discardedBytes:0},before,after:{...structuredClone(before),observedAt:1020},isolation:{rootReadOnly:true,sourceReadOnly:true,controllerReadOnly:true,dependenciesReadOnly:true,noNewPrivileges:true,noCapabilities:true,seccomp:true,nonRoot:true,privateNamespaces:true,networkNone:true,finiteStorage:true,cleanEnvironment:true,engineDigest:D,seccompDigest:D,imageDigest:D,controllerDigest:D,dependencyArtifactDigest:D},stopped:true,inputDigest:D,outputDigest:D,outputs:(p.profileId==='release-build'?['log','device.cjs','worker.mjs','tools.json']:['log']).map(n=>({name:n,digest:recordDigest('dev2.fixture-output.v1',{name,n}),size:1}))},result={assignmentId,leaseId:outer.leaseId,inputIdentity,sealDigest:qualificationIdentity,trustedRunnerDigest:D,startedAt:1000,endedAt:1030,stopped:true,exitCode:0,signal:null,deadlineExceeded:false,inputDigest:D,outputDigest:D,artifacts:[]},value={result,outer,outerDigest:D};refresh(value);return value;}
 report.profiles=profiles.map(p=>{const e=evidence(p,p.profileId);return {...e,profileId:p.profileId,profileDigest:p.digest,assignmentId:e.outer.assignmentId,inputIdentity:e.outer.inputIdentity,launches:1,executes:1,completionDeliveries:2,responseLossExact:true};});
 report.negative.containment={...evidence(required[0],'containment'),checks:{nonRoot:true,noNewPrivileges:true,zeroCapabilities:true,seccomp:true,readonlySource:true,readonlyRoot:true,noHostPath:true,noCredentials:true,boundedMemory:true,boundedPids:true,boundedCpu:true,boundedDisk:true,noNetwork:true}};
 report.negative.oom=evidence(required[0],'oom');report.negative.oom.outer.after.memoryEvents.oom_kill=1;report.negative.oom.result.exitCode=1;refresh(report.negative.oom);
 report.negative.deadline=evidence(required[0],'deadline');report.negative.deadline.result.exitCode=null;report.negative.deadline.result.signal='SIGTERM';report.negative.deadline.result.deadlineExceeded=true;refresh(report.negative.deadline);
 report.negative.cancellation=evidence(required[0],'cancellation');report.negative.cancellation.result.exitCode=null;report.negative.cancellation.result.signal='SIGTERM';refresh(report.negative.cancellation);
 return {report,expected:{sourceCommit:S,source,definition,providerRunId:'123'}};
}
function refresh(e){e.outerDigest=bytesDigest(Buffer.from(canonicalJson(e.outer)));e.result.artifacts=e.result.signal===null&&!e.result.deadlineExceeded?[...e.outer.outputs.map(o=>o.digest),e.outerDigest]:[];}
function verify(f){return verifyProductionQualification(canonicalJson(f.report),f.expected);}
test('qualified adapter report joins exact source/provider/engine, actual profile outcomes and independent kernel/stop falsifiers',()=>{const f=fixture(),r=verify(f);assert.equal(r.engineDigest,D);assert.equal(r.dependencyArtifactDigest,D);assert.equal(r.report.productionSeal,false);assert.equal(r.report.productionValidation,false);assert.equal(r.report.nativeAssignmentVerified,false);assert.equal(r.report.profiles.length,3);});
test('qualification cannot relabel itself as production validation, native assignment or installed seal',()=>{for(const field of ['productionSeal','productionValidation','nativeAssignmentVerified']){const f=fixture();f.report[field]=true;assert.throws(()=>verify(f),{code:'INTEGRITY_FAILURE'});}for(const [field,value] of [['sourceCommit','5'.repeat(40)],['sourceTree','sha1:'+'6'.repeat(40)],['runId','124'],['runAttempt','2'],['status','failed'],['engineDigest',E],['dependencyArtifactDigest',E]]){const f=fixture();f.report[field]=value;assert.throws(()=>verify(f),{code:'INTEGRITY_FAILURE'});}});
test('same-adapter profile evidence rejects absent kernel, changed cgroup, OOM, privilege or truncated output despite child exit zero',()=>{for(const mutate of [x=>x.after=null,x=>x.after.cgroup='/another',x=>x.after.memoryEvents.oom_kill=1,x=>x.isolation.networkNone=false,x=>x.isolation.nonRoot=false,x=>x.command.discardedBytes=1,x=>x.isolation.engineDigest=E]){const f=fixture(),p=f.report.profiles[0];mutate(p.outer);refresh(p);assert.throws(()=>verify(f),{code:'INTEGRITY_FAILURE'});}});
test('one receipt cannot replace another profile/build output or cover repeated physical execution',()=>{for(const mutate of [f=>f.report.profiles.reverse(),f=>f.report.profiles[1].assignmentId=f.report.profiles[0].assignmentId,f=>f.report.profiles[0].executes=2,f=>f.report.profiles[0].launches=2,f=>f.report.profiles[0].responseLossExact=false,f=>f.report.profiles[2].outer.outputs.pop()]){const f=fixture();mutate(f);for(const p of f.report.profiles)refresh(p);assert.throws(()=>verify(f),{code:'INTEGRITY_FAILURE'});}});
test('an exit137 proxy, missing kernel OOM increment or missing stop/cancel falsifier cannot qualify the adapter',()=>{for(const mutate of [f=>f.report.negative.oom.outer.after.memoryEvents.oom_kill=0,f=>f.report.negative.oom.outer.command.exitCode=137,f=>f.report.negative.deadline.result.deadlineExceeded=false,f=>f.report.negative.cancellation.result.signal=null,f=>f.report.negative.containment.checks.noNetwork=false,f=>f.report.negative.containment.result.stopped=false]){const f=fixture();mutate(f);for(const e of Object.values(f.report.negative))refresh(e);assert.throws(()=>verify(f),{code:'INTEGRITY_FAILURE'});}});
test('qualification report is a closed data format, not a place for candidate-supplied trust extensions',()=>{const f=fixture();f.report.extraTrust=true;assert.throws(()=>verify(f),{code:'INTEGRITY_FAILURE'});const g=fixture();g.report.negative.containment.checks.fakeSeal=true;assert.throws(()=>verify(g),{code:'INTEGRITY_FAILURE'});});
