import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,chmod,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {ProductionRunner} from '../../src/execution/production-runner.mjs';
import {nonRootMappedUser} from '../../src/execution/production-sandbox.mjs';
import {decodeOuterReceipt} from '../../src/execution/outer-receipt.mjs';
import {ObjectStore} from '../../src/storage/objects.mjs';
import {preparePayload,executionIdentity,physicalAttempt} from '../../src/execution/payload.mjs';
import {attemptName} from '../../src/execution/podman.mjs';
import {materialize} from '../../src/candidate/materialize.mjs';
import {sourceManifest} from '../../src/repository/entries.mjs';
import {bytesDigest,recordDigest,canonicalJson} from '../../src/contracts/canonical.mjs';
import {encodeBuildOutput} from '../../src/release/build-output.mjs';
import {Dev2Error} from '../../src/contracts/errors.mjs';
const D='sha256:'+'1'.repeat(64);
async function fixture(build=false){const root=await mkdtemp(join(tmpdir(),'dev2-production-runner-')),objects=new ObjectStore(join(root,'objects'));await objects.init();const bytes=Buffer.from('export const value = 1;\n'),blobOid='sha1:'+createHash('sha1').update('blob '+bytes.length+'\0').update(bytes).digest('hex'),entry={path:'source.mjs',mode:'100644',blobOid,contentDigest:bytesDigest(bytes),size:bytes.length},source={treeOid:'sha1:'+'1'.repeat(40),entries:[entry],manifestDigest:sourceManifest([entry])};
 const definition={profileId:build?'release-build':'core',argv:['/usr/local/bin/node','--check','/source/source.mjs'],cwd:'',parameters:{},timeoutMs:10000,killGraceMs:1000,memoryBytes:67108864,pids:48,cpuMillis:1000,diskBytes:8388608,logBytes:65536,network:'none',imageDigest:D,replaySafe:true},profile={...definition,digest:recordDigest('dev2.profile.v1',definition)},execution={orderedProfileDigests:[profile.digest],trustedRunnerDigest:D,toolchainDigest:D,environmentClass:'fixture',dependencyLockDigest:D};const payload=await preparePayload({source,profile,execution,resultId:'result',repository:{blob:async()=>bytes},objects}),attempt={installationId:'i',repositoryId:'r',workId:'w',actionId:'a',attemptId:'attempt',attempt:'1',ownerEpoch:'1'},input={attempt,resultId:'result',profileDigest:profile.digest,sourceManifest:source.manifestDigest,payloadDigest:payload.payloadDigest,executionDigest:executionIdentity(execution),deadline:90000},assignment={assignmentId:recordDigest('dev2.managed-assignment.v1',{attempt,profileDigest:profile.digest}).slice(7),sessionId:'s',runId:'19',leaseId:'lease',input,inputIdentity:recordDigest('dev2.managed-assignment-input.v1',input),sealDigest:D,revision:'0',state:'offered',cancelRequested:false,result:null};
 let time=10000,state='absent',launches=0,executes=0,stops=0,completions=0,lose=false,loseUpload=false,mode='normal',sample=0,finishCommand=null;const uploaded=new Map(),accepted=[],events=[];
 const observation=()=>({state,attempt,exitCode:state==='exited'?137:null,signal:null,artifacts:[]}),isolation={rootReadOnly:true,sourceReadOnly:true,controllerReadOnly:true,dependenciesReadOnly:true,noNewPrivileges:true,noCapabilities:true,seccomp:true,nonRoot:true,privateNamespaces:true,networkNone:true,finiteStorage:true,cleanEnvironment:true,engineDigest:D,seccompDigest:D,imageDigest:D,controllerDigest:D,dependencyArtifactDigest:D};
 const files={'device.cjs':Buffer.from('device'), 'worker.mjs':Buffer.from('edge'), 'tools.json':Buffer.from(JSON.stringify(['dev_context','dev_read','dev_work','dev_observe'].map(name=>({name,annotations:{readOnlyHint:true,destructiveHint:false}}))))};
 const sandbox={inspect:async()=>observation(),launch:async()=>{events.push('launch');launches++;state='running';return observation();},cancel:async()=>{events.push('stop');stops++;state='exited';finishCommand?.();return observation();},kernelEvidence:async()=>{events.push('kernel');sample++;if(mode==='missing-kernel')return null;return {container:attemptName(physicalAttempt(assignment)),pid:3456,cgroup:'/test/exact',observedAt:time,memoryEvents:{oom:0,oom_kill:mode==='oom'&&sample>1?1:0},limits:{memoryBytes:profile.memoryBytes,pids:profile.pids,cpuQuota:100000,cpuPeriod:100000}};},isolationEvidence:async()=>({...isolation,networkNone:mode!=='bad-network'}),executeProfile:async()=>{events.push('exec');executes++;time+=100;if(mode==='mutate'){const path=join(root,'source','source.mjs');await chmod(path,0o600);await writeFile(path,'tampered');}if(mode==='deadline')await new Promise(resolve=>{finishCommand=resolve;});return {exitCode:0,signal:null,timedOut:false,spawnFailed:false,discardedBytes:mode==='truncated'?1:0,stdout:build?(mode==='bad-build'?Buffer.from('{}'):encodeBuildOutput(D,files)):Buffer.from('actual output'),stderr:Buffer.alloc(0)};}};
 const client={sessionId:'s',download:async()=>objects.get(payload.payloadDigest),acknowledge:async()=>({...assignment,state:'running'}),poll:async()=>({assignment,cancelRequested:mode==='cancel'}),upload:async(_a,bytes)=>{assert.equal(state,'exited');const d=bytesDigest(bytes);uploaded.set(d,Buffer.from(bytes));if(loseUpload){loseUpload=false;throw new Dev2Error('EXECUTION_UNAVAILABLE','reply lost after object upload');}return d;},complete:async result=>{assert.equal(state,'exited');completions++;accepted.push(canonicalJson(result));if(lose){lose=false;throw new Dev2Error('EXECUTION_UNAVAILABLE','reply lost after native completion');}return {...assignment,state:'complete',result};}};
 // Advancing an artificial clock in a microtask-only loop starves real filesystem
 // completion and fabricates a deadline failure. Yield to I/O; only the explicit
 // deadline scenario advances time while its controlled command remains pending.
 const options={client,stateDirectory:join(root,'journal'),runId:'19',sealDigest:D,trustedRunnerDigest:D,now:()=>time,sleep:async()=>{if(mode==='deadline')time+=profile.timeoutMs;await new Promise(resolve=>setImmediate(resolve));},createSandbox:async(_a,decoded)=>{const sourceRoot=join(root,'source');try{await materialize(decoded.repository,decoded.payload.source,sourceRoot);}catch(e){if(e.code!=='ENTRY_CONFLICT')throw e;}return {sandbox,sourceRoot};}};
 return {root,assignment,profile,runner:new ProductionRunner(options),newRunner:()=>new ProductionRunner(options),setMode:v=>mode=v,setState:v=>state=v,setLose:()=>lose=true,setLoseUpload:()=>loseUpload=true,counts:()=>({launches,executes,stops,completions}),events,uploaded,accepted,close:()=>rm(root,{recursive:true,force:true})};
}
test('production outer controller samples actual command and proves complete container stop before returning objects',async()=>{const f=await fixture();try{const result=await f.runner.execute(f.assignment),outer=decodeOuterReceipt(f.uploaded.get(result.artifacts.at(-1)));assert.equal(result.exitCode,0);assert.equal(outer.command.exitCode,0);assert.equal(outer.stopped,true);assert.deepEqual(f.counts(),{launches:1,executes:1,stops:1,completions:1});assert.deepEqual(f.events,['launch','kernel','exec','kernel','stop']);assert.equal(outer.outputs[0].digest,result.artifacts[0]);assert.equal(outer.inputIdentity,f.assignment.inputIdentity);}finally{await f.close();}});
test('production response loss reuses identical receipt and physical execution; uploaded object response loss does not run again',async()=>{for(const upload of [false,true]){const f=await fixture();try{if(upload)f.setLoseUpload();else f.setLose();await assert.rejects(f.runner.execute(f.assignment),{code:'EXECUTION_UNAVAILABLE'});const result=await f.newRunner().execute(f.assignment);assert.equal(result.exitCode,0);assert.equal(f.counts().launches,1);assert.equal(f.counts().executes,1);if(!upload)assert.equal(f.accepted[0],f.accepted[1]);assert.equal((await f.newRunner().execute(f.assignment)).exitCode,0);}finally{await f.close();}}});
test('interrupted command with unknown outcome stops its existing container and never runs the command again',async()=>{const f=await fixture();try{await f.runner.read(f.assignment);await f.runner.write({schemaVersion:1,assignmentId:f.assignment.assignmentId,inputIdentity:f.assignment.inputIdentity,leaseId:f.assignment.leaseId,phase:'executing',startedAt:10000,before:null,after:null,isolation:null,command:null,objects:[],outer:null,result:null});f.setState('running');const result=await f.newRunner().execute(f.assignment);assert.equal(result.exitCode,null);assert.equal(result.signal,'SIGKILL');assert.equal(f.counts().launches,0);assert.equal(f.counts().executes,0);assert.equal(f.counts().stops,1);}finally{await f.close();}});
test('zero child exit does not conceal OOM, missing kernel evidence, failed isolation, output truncation or source corruption',async()=>{for(const mode of ['oom','missing-kernel','bad-network','truncated','mutate','cancel']){const f=await fixture();try{f.setMode(mode);const result=await f.runner.execute(f.assignment);assert.notEqual(result.exitCode,0,mode);assert.ok(f.counts().stops>=1);if(['missing-kernel','bad-network'].includes(mode))assert.equal(f.counts().executes,0);if(mode==='mutate')assert.notEqual(result.outputDigest,result.inputDigest);}finally{await f.close();}}});
test('an actual modeled deadline stops the same container, rejects a later zero exit and cannot upload successful artifacts',async()=>{const f=await fixture();try{f.setMode('deadline');const result=await f.runner.execute(f.assignment);assert.notEqual(result.exitCode,0);assert.equal(result.deadlineExceeded,true);assert.equal(result.signal,'SIGTERM');assert.deepEqual(result.artifacts,[]);assert.equal(f.counts().launches,1);assert.equal(f.counts().executes,1);assert.equal(f.counts().stops,1);const replay=await f.newRunner().execute(f.assignment);assert.equal(canonicalJson(replay),canonicalJson(result));assert.equal(f.counts().executes,1);}finally{await f.close();}});
test('finite build protocol is joined as exact named artifact bytes, not promoted from stdout claims',async()=>{const f=await fixture(true);try{const result=await f.runner.execute(f.assignment),outer=decodeOuterReceipt(f.uploaded.get(result.artifacts.at(-1)));assert.equal(result.exitCode,0);assert.deepEqual(outer.outputs.map(o=>o.name),['log','device.cjs','worker.mjs','tools.json']);for(const o of outer.outputs){const b=f.uploaded.get(o.digest);assert.equal(b.length,o.size);assert.equal(bytesDigest(b),o.digest);}assert.equal(result.artifacts.length,5);}finally{await f.close();}const g=await fixture(true);try{g.setMode('bad-build');assert.notEqual((await g.runner.execute(g.assignment)).exitCode,0);}finally{await g.close();}});
test('positive host uid alone cannot claim non-root inside a user namespace',()=>{assert.equal(nonRootMappedUser('1001 1001 1001 1001','0 100000 1001\n1001 1001 1\n1002 101001 64535'),true);assert.equal(nonRootMappedUser('1001 1001 1001 1001','0 1001 1'),false);assert.equal(nonRootMappedUser('1001 1001 1001 1001','1001 2000 1'),false);assert.equal(nonRootMappedUser('0 0 0 0','0 0 65536'),false);});
