import test from 'node:test';
import assert from 'node:assert/strict';
import {RequiredValidation} from '../../src/validation/receipts.mjs';
import {productionBinding,productionBindingEligible} from '../../src/validation/production-binding.mjs';
import {recordDigest} from '../../src/contracts/canonical.mjs';
const D='sha256:'+'1'.repeat(64),E='sha256:'+'2'.repeat(64),O='sha1:'+'3'.repeat(40);
function fixture(){const profiles=['core','integration'].map((profileId,i)=>({profileId,digest:i?E:D,argv:['node','check'],cwd:'',parameters:{},timeoutMs:10000,killGraceMs:1000,memoryBytes:67108864,pids:64,cpuMillis:1000,diskBytes:8388608,logBytes:65536,network:'none',imageDigest:D,replaySafe:true})),execution={orderedProfileDigests:[D,E],trustedRunnerDigest:D,toolchainDigest:D,dependencyLockDigest:D,environmentClass:'fixture'},result={resultId:'result',repositoryId:'repo',bindingEpoch:'1',workId:'work',generation:'9',baseCommitOid:O,baseTreeOid:O,candidateTreeOid:O,expectedHead:O,commitOid:O,resultTreeOid:O,resultTreeSha256:D,policyDigest:D,metadata:{author:'a',committer:'c',timestamp:1,message:'change'},execution},attempt={installationId:'installation',repositoryId:'repo',workId:'work',actionId:'action',attemptId:'attempt',attempt:'1',ownerEpoch:'6'},proof=p=>({schemaVersion:1,contextDigest:recordDigest('dev2.fixture-context.v1',{result,attempt,profile:p.digest}),outerReceiptDigest:recordDigest('dev2.fixture-outer.v1',{profile:p.digest}),assignmentId:'assignment-'+p.profileId,inputIdentity:D,sessionId:'session',providerRunId:'123',providerRunAttempt:'1',profileDigest:p.digest,sealDigest:D,eligible:true}),run=async(r,a,p)=>({startedAt:1,endedAt:2,exitCode:0,signal:null,deadlineExceeded:false,inputDigest:r.resultTreeSha256,outputDigest:r.resultTreeSha256,productionProof:proof(p)}),options={key:Buffer.alloc(32,7),profiles,execution,run,now:()=>3};return {result,attempt,profiles,proof,options,production:new RequiredValidation({...options,productionEnrollment:D}),legacy:new RequiredValidation(options)};}
test('production required receipt MAC binds full immutable result, attempt, private enrollment and each exact outer receipt',async()=>{const f=fixture(),r=await f.production.validate(f.result,f.attempt);assert.equal(await f.production.eligible(f.result,r,D,'7'),true);assert.equal(await f.legacy.eligible(f.result,r,D,'7'),false);assert.equal(productionBindingEligible(f.result,f.attempt,D,r.productionJson),true);for(const key of ['generation','workId','metadata']){const changed=structuredClone(f.result);changed[key]=key==='metadata'?{...changed.metadata,message:'different'}:'different';assert.equal(await f.production.eligible(changed,r,D,'7'),false);}const changed={...r,attempt:{...r.attempt,installationId:'another'}};assert.equal(await f.production.eligible(f.result,changed,D,'7'),false);assert.equal(await new RequiredValidation({...f.options,productionEnrollment:E}).eligible(f.result,r,D,'7'),false);});
test('historical qualified PASS cannot be relabeled, appended, stripped or reused as production',async()=>{const f=fixture(),old=await f.legacy.validate(f.result,f.attempt),current=await f.production.validate(f.result,f.attempt);assert.equal(await f.legacy.eligible(f.result,old,D,'6'),true);assert.equal(await f.production.eligible(f.result,old,D,'6'),false);assert.equal(await f.production.eligible(f.result,{...old,productionJson:current.productionJson},D,'6'),false);const {productionJson,...stripped}=current;assert.equal(await f.legacy.eligible(f.result,stripped,D,'6'),false);const tampered=JSON.parse(current.productionJson);tampered.proofs[0].providerRunId='124';assert.equal(await f.production.eligible(f.result,{...current,productionJson:JSON.stringify(tampered)},D,'6'),false);});
test('missing or wrong native outer evidence rejects production, and a joined negative execution never becomes PASS',async()=>{const f=fixture(),missing=new RequiredValidation({...f.options,productionEnrollment:D,run:async(r,a,p)=>{const {productionProof,...run}=await f.options.run(r,a,p);return run;}});await assert.rejects(missing.validate(f.result,f.attempt),{code:'VALIDATION_FAILED'});const negative=new RequiredValidation({...f.options,productionEnrollment:D,run:async(r,a,p)=>{const run=await f.options.run(r,a,p);run.productionProof.eligible=false;return run;}}),receipt=await negative.validate(f.result,f.attempt);assert.equal(receipt.exitCode,1);assert.equal(await negative.eligible(f.result,receipt,D,'6'),false);});
test('binding rejects duplicate physical receipt identity and mismatched profile/enrollment order',()=>{const f=fixture(),proofs=f.profiles.map(f.proof);assert.throws(()=>productionBinding(f.result,f.attempt,D,[proofs[0],{...proofs[1],assignmentId:proofs[0].assignmentId}]),{code:'INTEGRITY_FAILURE'});assert.throws(()=>productionBinding(f.result,f.attempt,D,proofs.toReversed()),{code:'INTEGRITY_FAILURE'});assert.throws(()=>productionBinding(f.result,f.attempt,E,proofs),{code:'INTEGRITY_FAILURE'});});
