// Deterministic test-only provider/kernel evidence. Never an installed enrollment.
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Ledger} from '../../src/storage/ledger.mjs';
import {ObjectStore} from '../../src/storage/objects.mjs';
import {ManagedSessions} from '../../src/execution/sessions.mjs';
import {AssignmentTransfer} from '../../src/execution/session-transfer.mjs';
import {ManagedPool} from '../../src/execution/managed-pool.mjs';
import {ProductionReceipts} from '../../src/execution/outer-receipt.mjs';
import {canonicalJson,recordDigest,bytesDigest} from '../../src/contracts/canonical.mjs';
import {sourceManifest} from '../../src/repository/entries.mjs';
import {managedPolicy} from '../../src/validation/managed-policy.mjs';
import {releaseBuildProfile,releaseBuildExecution} from '../../src/release/build-profile.mjs';
import {productionIntentDigest,verifyProductionEnrollment} from '../../src/runtime/production-enrollment.mjs';
import {executionIdentity,physicalAttempt} from '../../src/execution/payload.mjs';
import {attemptName} from '../../src/execution/podman.mjs';
import {SCHEMA_DIGEST,TOOL_DESCRIPTORS} from '../../src/mcp/outputs.mjs';
export const D=n=>'sha256:'+String(n).repeat(64),O=n=>'sha1:'+String(n).repeat(40);
export async function productionFixture(){
 const root=await mkdtemp(join(tmpdir(),'dev2-production-fixture-')),binding={installationId:'installation',repositoryId:'repository',provider:'github',providerRepositoryId:'123',remote:'https://github.com/owner/repo.git',ref:'refs/heads/dev-2',bindingEpoch:'1',policyDigest:D(4)};
 let ledger=new Ledger(join(root,'work.sqlite'),binding);const objects=new ObjectStore(join(root,'objects'));await objects.init();
 const identities={trustedRunnerDigest:D(1),controllerDigest:D(2),toolchainDigest:D(3),dependencyLockDigest:D(4),workflowDigest:D(5),imageDigest:D(6),seccompDigest:D(7)},policy=managedPolicy(identities),definition={identities,policy,config:{executionShape:'production-outer-v1',origin:'https://tdev.humtr.workers.dev',sessionLifetimeMs:900000},controller:{}},source={treeOid:O(2),manifestDigest:sourceManifest([]),entries:[]},runtime={sourceCommitOid:O(1),sourceTreeOid:O(2),bundleDigest:D(8),schemaDigest:SCHEMA_DIGEST};
 const intent={schemaVersion:1,kind:'dev2.production-commissioning',commissioningId:'fixture-commission',installationId:binding.installationId,repositoryId:binding.repositoryId,bindingEpoch:'1',providerRepositoryId:'123',repositoryOwnerId:'456',repositoryFullName:'owner/repo',approvedCommitOid:O(1),approvedSourceTreeOid:source.treeOid,approvedSourceManifestDigest:source.manifestDigest,identities,engineDigest:D(8),dependencyArtifactDigest:D(9),qualificationSealDigest:D(0),runtime};
 ledger.transact(tx=>tx.run('INSERT INTO meta VALUES(?,?)','production.commissioning:'+intent.commissioningId,canonicalJson(intent)));
 const config={repositoryOwnerId:'456',repositoryFullName:'owner/repo',approvedCommit:'1'.repeat(40),trustedRunnerDigest:identities.trustedRunnerDigest,sessionTimeoutMs:900000,capacity:8,sealDigest:productionIntentDigest(intent)};
 let sessions,transfer,pool,provider;let launches=0,executions=0;const active=new Map();
 const repository={readCommit:async(b,commit)=>({commitOid:commit,parents:[O(0)],source}),blob:async()=>{throw Error('unexpected blob');}};
 function ports(){sessions=new ManagedSessions({ledger,config});transfer=new AssignmentTransfer({sessions,objects});provider={launch:async sid=>{launches++;activate(sid);},refresh:async sid=>ledger.transact(tx=>sessions.session(tx,sid)),cancel:async sid=>{const s=ledger.transact(tx=>sessions.session(tx,sid));sessions.cancelSession(sid);sessions.providerStopped(sid,{...s.run,status:'completed',observedAt:Date.now()});}};pool=new ManagedPool({sessions,provider,repository,objects,pollMs:10});}
function activate(sid){if(active.has(sid))return active.get(sid);let s=ledger.transact(tx=>sessions.session(tx,sid));sessions.markLaunchSent(sid);const i=s.intent,runId=String(1000+active.size),run={repositoryId:'123',repositoryOwnerId:'456',runId,runAttempt:'1',headSha:i.launchCommit,headBranch:i.ref.slice(11),event:'push',workflowPath:'.github/workflows/dev2-executor.yml',status:'in_progress',observedAt:Date.now()};sessions.selectRun(sid,run);const identity={kind:'github-executor',installationId:i.installationId,repositoryId:'123',sessionId:sid,runId,runAttempt:'1',launchCommit:i.launchCommit,expiresAt:i.deadline,launchIdentity:recordDigest('dev2.execution-launch.v1',{installationId:i.installationId,sessionId:sid,repository_id:'123',repository_owner_id:'456',ref:i.ref,sha:i.launchCommit,workflow_ref:i.workflowRef,workflow_sha:i.launchCommit,run_id:runId,run_attempt:'1',runner_environment:'github-hosted',event_name:'push'})};active.set(sid,identity);return identity;}
 ports();
 function create(name,profile,special=false){const attempt={installationId:binding.installationId,repositoryId:binding.repositoryId,workId:name,actionId:name,attemptId:name,attempt:'1',ownerEpoch:ledger.ownerEpoch},result={resultId:name,repositoryId:binding.repositoryId,bindingEpoch:'1',workId:name,generation:'0',baseCommitOid:O(1),baseTreeOid:source.treeOid,candidateTreeOid:source.treeOid,expectedHead:O(0),commitOid:O(1),resultTreeOid:source.treeOid,resultTreeSha256:source.manifestDigest,policyDigest:policy.policy.digest,metadata:{author:'fixture',committer:'fixture',timestamp:1,message:'fixture'},execution:profile.profileId==='release-build'?releaseBuildExecution(policy.policy.execution,identities.imageDigest):policy.policy.execution};
ledger.transact(tx=>{if(!special)tx.insertWork({workId:name,repositoryId:binding.repositoryId,bindingEpoch:'1',principal:'human',baseCommitOid:O(1),baseTreeOid:source.treeOid,candidate:{treeOid:source.treeOid,manifestDigest:source.manifestDigest},generation:'0',revision:'0',disposition:'open',currentActionId:name});tx.insertAction({actionId:name,requestId:name,principal:'human',bindingEpoch:'1',intentDigest:D(0),operation:special?'release.stage':'validate',workId:special?null:name,status:'running',step:'fixture',attempt:'0',ownerEpoch:ledger.ownerEpoch,deadline:Date.now()+800000,resultId:null,errorCode:null});tx.reserveAttempt(attempt,8);tx.updateAction({...tx.getAction(name),attempt:'1'});if(!special)tx.putPrepared(result);});return {attempt,result};
 }
 async function complete(a,profile,mutate=()=>{}){executions++;const identity=active.get(a.sessionId);sessions.acknowledge(identity,a.assignmentId,a.leaseId);const start=Date.now(),container=attemptName(physicalAttempt(a)),kernel={container,pid:1234,cgroup:'/fixture/test',observedAt:start,memoryEvents:{oom:0,oom_kill:0},limits:{memoryBytes:profile.memoryBytes,pids:profile.pids,cpuQuota:profile.cpuMillis*100,cpuPeriod:100000}},files=profile.profileId==='release-build'?{'device.cjs':Buffer.from('fixture device bytes'),'worker.mjs':Buffer.from('fixture edge bytes'),'tools.json':Buffer.from(canonicalJson(TOOL_DESCRIPTORS))}:{};
  const outputs=Object.entries(files).map(([name,bytes])=>({name,digest:bytesDigest(bytes),size:bytes.length}));
  const outer={schemaVersion:1,kind:'dev2-production-execution',assignmentId:a.assignmentId,leaseId:a.leaseId,inputIdentity:a.inputIdentity,sessionId:a.sessionId,runId:a.runId,sealDigest:a.sealDigest,trustedRunnerDigest:identities.trustedRunnerDigest,profileDigest:profile.digest,container,startedAt:start,endedAt:start+1,command:{argvDigest:recordDigest('dev2.executed-argv.v1',profile.argv),exitCode:0,signal:null,timedOut:false,spawnFailed:false,discardedBytes:0},before:kernel,after:{...structuredClone(kernel),observedAt:start+1},isolation:{rootReadOnly:true,sourceReadOnly:true,controllerReadOnly:true,dependenciesReadOnly:true,noNewPrivileges:true,noCapabilities:true,seccomp:true,nonRoot:true,privateNamespaces:true,networkNone:true,finiteStorage:true,cleanEnvironment:true,engineDigest:intent.engineDigest,seccompDigest:identities.seccompDigest,imageDigest:identities.imageDigest,controllerDigest:identities.controllerDigest,dependencyArtifactDigest:intent.dependencyArtifactDigest},stopped:true,inputDigest:a.input.sourceManifest,outputDigest:a.input.sourceManifest,outputs};mutate(outer);
  const outerBytes=Buffer.from(canonicalJson(outer)),outerDigest=bytesDigest(outerBytes);for(const bytes of [...Object.values(files),outerBytes])await transfer.upload({identity,assignmentId:a.assignmentId,leaseId:a.leaseId},{digest:bytesDigest(bytes),size:bytes.length,offset:0,data:bytes.toString('base64')});
  const execution={assignmentId:a.assignmentId,leaseId:a.leaseId,inputIdentity:a.inputIdentity,sealDigest:a.sealDigest,trustedRunnerDigest:identities.trustedRunnerDigest,startedAt:start,endedAt:start+1,stopped:true,exitCode:0,signal:null,deadlineExceeded:false,inputDigest:outer.inputDigest,outputDigest:outer.outputDigest,artifacts:[...outputs.map(o=>o.digest),outerDigest]};sessions.complete(identity,execution);return {outer,execution};
 }
 const receiptPort=()=>new ProductionReceipts({sessions,objects,seccompDigest:identities.seccompDigest,controllerDigest:identities.controllerDigest,engineDigest:intent.engineDigest,dependencyArtifactDigest:intent.dependencyArtifactDigest});
 const proofs=[];
 for(const profile of [...policy.required(),releaseBuildProfile(identities.imageDigest)]){const f=create('probe-'+profile.profileId,profile),sid='probe-session-'+profile.profileId;sessions.reserve(sid);const identity=activate(sid),payload=Buffer.from('test-only payload'),payloadDigest=await objects.put(payload),input={attempt:f.attempt,resultId:f.result.resultId,profileDigest:profile.digest,sourceManifest:source.manifestDigest,payloadDigest,executionDigest:executionIdentity(f.result.execution),deadline:Date.now()+600000};const a=sessions.offer(identity,input,[{digest:payloadDigest,size:payload.length}]);const {execution}=await complete(a,profile),{proof}=await receiptPort().verify(f.result,f.attempt,profile,execution);proofs.push({resultId:f.result.resultId,assignmentId:a.assignmentId,sessionId:a.sessionId,runId:a.runId,runAttempt:'1',leaseId:a.leaseId,profileDigest:profile.digest,contextDigest:proof.contextDigest,outerReceiptDigest:proof.outerReceiptDigest});ledger.transact(tx=>tx.releaseAttempt(f.attempt.attemptId));}
 const body={schemaVersion:1,kind:'dev2.production-enrollment',intent,proofs},enrollment={...body,sealDigest:recordDigest('dev2.production-enrollment.v1',body)};
 const expected=()=>({binding,definition,source,runtime,qualificationSealDigest:intent.qualificationSealDigest,sessions,objects});
 async function enrolled(){return verifyProductionEnrollment(enrollment,expected());}
 const result=ledger.transact(tx=>tx.getPrepared('probe-core')),integrated={repositoryId:binding.repositoryId,bindingEpoch:'1',commitOid:O(1),source,policyDigest:policy.policy.digest,validationId:D(1),result,receipt:{fixture:true},effect:{fixture:true}},previous={releaseId:D(0),schemaDigest:SCHEMA_DIGEST,sourceCommitOid:O(0),deviceReleaseId:D(0),deviceArtifactDigest:D(0),deviceSourceCommitOid:O(0),edgeVersionId:'fixture-edge',edgeArtifactDigest:D(0),edgeSourceCommitOid:O(0),protocol:{min:1,max:1},ledger:{min:1,max:1}};
 return {root,binding,definition,source,runtime,intent,enrollment,expected,enrolled,integrated,previous,objects,create,complete,activate,receiptPort,get ledger(){return ledger;},get sessions(){return sessions;},get pool(){return pool;},counts:()=>({launches,executions}),useProductionSeal(){config.sealDigest=enrollment.sealDigest;ports();},restart(){ledger.close();ledger=new Ledger(join(root,'work.sqlite'),binding);ports();},async close(){ledger.close();await rm(root,{recursive:true,force:true});}};
}
