import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {ActivationJournal} from '../../src/release/journal.mjs';
import {ActivationController} from '../../src/release/activation.mjs';
import {DeviceActivationPort} from '../../src/release/device-port.mjs';
import {Dev2Error} from '../../src/contracts/errors.mjs';
const D=n=>'sha256:'+String(n).repeat(64),O=n=>'sha1:'+String(n).repeat(40);
const pair=n=>({releaseId:D(n),schemaDigest:D(1),sourceCommitOid:O(n),deviceReleaseId:D(n),deviceArtifactDigest:D(n),deviceSourceCommitOid:O(n),edgeVersionId:'edge'+n,edgeArtifactDigest:D(n),edgeSourceCommitOid:O(n),protocol:{min:1,max:1},ledger:{min:1,max:1}});
const pointer=p=>({schemaVersion:1,installationId:'i',repositoryId:'r',bindingEpoch:'1',deviceReleaseId:p.deviceReleaseId,artifactDigest:p.deviceArtifactDigest,sourceCommitOid:p.deviceSourceCommitOid,schemaDigest:p.schemaDigest,nativeConfigDigest:D(9)});
async function fixture({loseSwitch=false,unknownStop=false,unhealthyNew=false,edgeOnly=false}={}){const root=await mkdtemp(join(tmpdir(),'dev2-device-port-fixture-')),file=join(root,'helper.sqlite');let journal=new ActivationJournal(file,'i'),now=1000,current=pointer(pair(1)),edge=pair(1),started=true,accepting=true,drainId=null,epoch=1,physicalSwitches=0,healthFailures=0;const sends=[],service=new Map();
 const previous=pair(1),target=edgeOnly?{...pair(2),deviceReleaseId:previous.deviceReleaseId,deviceArtifactDigest:previous.deviceArtifactDigest,deviceSourceCommitOid:previous.deviceSourceCommitOid}:pair(2),intent={activationId:'activation',actionId:'action',installationId:'i',repositoryId:'r',bindingEpoch:'1',principalId:'human',createdAt:now,deadline:now+120000,previous,target};journal.begin(intent);
 const status=()=>({schemaVersion:1,installationId:'i',repositoryId:'r',bindingEpoch:'1',deviceReleaseId:current.deviceReleaseId,sourceCommitOid:current.sourceCommitOid,bundleDigest:current.artifactDigest,schemaDigest:D(1),ownerEpoch:String(epoch),connected:started,accepting,drainActivationId:drainId,drained:!accepting,edge:{versionId:edge.edgeVersionId,sourceCommitOid:edge.edgeSourceCommitOid,bundleDigest:edge.edgeArtifactDigest,schemaDigest:edge.schemaDigest}});
 const dependencies={installationId:'i',repositoryId:'r',bindingEpoch:'1',now:()=>now,healthTimeoutMs:1000,pointer:async()=>current,pointerFor:async p=>pointer(p),edge:{active:async()=>({versionId:edge.edgeVersionId})},native:{status:async()=>{if(!started)throw new Dev2Error('EXECUTION_UNAVAILABLE');const s=status();if(unhealthyNew&&current.deviceReleaseId===target.deviceReleaseId&&accepting){healthFailures++;now+=1100;s.connected=false;}return s;},drain:async e=>{drainId=e.activationId;accepting=false;return status();}},runit:{invoke:async(e,mode)=>{
   if(mode==='run'&&!service.has(e.effectId)){sends.push({id:e.effectId,step:e.step,direction:e.direction});service.set(e.effectId,e.step);if(e.step==='device.stop')started=false;else{started=true;accepting=true;drainId=null;epoch++;}}
   if(e.step==='device.stop'&&unknownStop)return {effectId:e.effectId,inputDigest:e.inputDigest,step:e.step,state:'uncertain',delivery:'unknown',senderStopped:true,service:{pid:0,wanted:'u',state:0}};
   return {effectId:e.effectId,inputDigest:e.inputDigest,step:e.step,state:'done',delivery:'sent',senderStopped:true,service:{pid:started?123:0,wanted:started?'u':'d',state:started?1:0}};
  }},writerFence:{invoke:async(e,expected,desired,mode)=>{assert.equal(started,false);assert.ok(current.deviceReleaseId===expected.deviceReleaseId||current.deviceReleaseId===desired.deviceReleaseId);if(mode==='switch'&&current.deviceReleaseId!==desired.deviceReleaseId){physicalSwitches++;current=desired;if(loseSwitch){loseSwitch=false;throw new Dev2Error('EXECUTION_UNAVAILABLE','lost after pointer switch');}}return {state:mode==='switch'?'switched':'stopped',writerStopped:true,effectId:e.effectId,inputDigest:e.inputDigest,ownerEpoch:String(epoch),senderCount:2,pointer:current};}}};
 let port,controller;
 const compose=()=>{port=new DeviceActivationPort({...dependencies,journal});controller=new ActivationController({journal,now:()=>now,port:{reconcile:async e=>{if(e.step!=='edge.activate')return port.reconcile(e);port.assert(e);return {effectId:e.effectId,inputDigest:e.inputDigest,kind:edge.edgeVersionId===e.target.edgeVersionId?'applied':'not_applied',senderStopped:true,observedAt:now,output:edge.edgeVersionId===e.target.edgeVersionId?{edgeVersionId:edge.edgeVersionId}:{}};},execute:async e=>{if(e.step!=='edge.activate')return port.execute(e);edge=e.target;return {effectId:e.effectId,inputDigest:e.inputDigest,kind:'applied',senderStopped:true,observedAt:now,output:{edgeVersionId:edge.edgeVersionId}};}}});};compose();
 return {intent,drive:()=>controller.drive('activation'),counts:()=>({physicalSwitches,sends,healthFailures}),resolveStop:()=>{unknownStop=false;},restart:()=>{journal.close();journal=new ActivationJournal(file,'i');compose();},close:async()=>{journal.close();await rm(root,{recursive:true,force:true});},current:()=>({pointer:current,edge,native:status()})};}
test('deterministic helper/native join requires all exact device and edge observations before active',async()=>{const f=await fixture();try{const result=await f.drive();assert.equal(result.phase,'active');assert.deepEqual(result.observedPair,f.intent.target);assert.equal(f.counts().physicalSwitches,1);assert.deepEqual(f.counts().sends.map(x=>x.step),['device.stop','device.start']);const again=await f.drive();assert.deepEqual(JSON.parse(JSON.stringify(again)),JSON.parse(JSON.stringify(result)));assert.equal(f.counts().physicalSwitches,1);}finally{await f.close();}});
test('lost pointer response and helper restart reconcile the original effect without a second switch',async()=>{const f=await fixture({loseSwitch:true});try{const first=await f.drive();assert.equal(first.phase,'blocked');assert.equal(first.pending.effect.step,'device.switch');const effect=first.pending.effect;assert.equal(f.counts().physicalSwitches,1);f.restart();const recovered=await f.drive();assert.equal(recovered.phase,'active');assert.equal(f.counts().physicalSwitches,1);assert.ok(recovered.receipts.some(r=>r.effectId===effect.effectId&&r.inputDigest===effect.inputDigest));}finally{await f.close();}});
test('uncertain runit send never permits a pointer switch or opposite rollback send',async()=>{const f=await fixture({unknownStop:true});try{const first=await f.drive();assert.equal(first.phase,'blocked');assert.equal(first.pending.effect.step,'device.stop');assert.equal(f.counts().physicalSwitches,0);const again=await f.drive();assert.equal(again.pending.effect.effectId,first.pending.effect.effectId);assert.equal(f.counts().sends.length,1);f.resolveStop();assert.equal((await f.drive()).phase,'active');assert.equal(f.counts().physicalSwitches,1);}finally{await f.close();}});
test('failed paired health restores the exact prior device and edge pair under the same activation',async()=>{const f=await fixture({unhealthyNew:true});try{const result=await f.drive();assert.equal(result.phase,'rolled_back');assert.equal(result.intent.activationId,'activation');assert.deepEqual(result.observedPair,f.intent.previous);assert.equal(f.counts().physicalSwitches,2);assert.ok(f.counts().healthFailures>0);assert.equal(f.current().pointer.deviceReleaseId,f.intent.previous.deviceReleaseId);assert.equal(f.current().edge.edgeVersionId,f.intent.previous.edgeVersionId);}finally{await f.close();}});
test('edge-only release performs no device stop, switch or restart',async()=>{const f=await fixture({edgeOnly:true});try{assert.equal((await f.drive()).phase,'active');assert.equal(f.counts().physicalSwitches,0);assert.deepEqual(f.counts().sends,[]);}finally{await f.close();}});
