import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm,realpath} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn,spawnSync} from 'node:child_process';
import {bytesDigest,canonicalJson} from '../../src/contracts/canonical.mjs';
const D='sha256:'+'1'.repeat(64),O='sha1:'+'1'.repeat(40),launcher=resolve('tools/release-device-launcher.py');
async function fixture(){const root=await mkdtemp(join(tmpdir(),'dev2-fixed-launcher-')),artifactDirectory=join(root,'artifacts'),nativeConfigDirectory=join(root,'configs');await mkdir(join(artifactDirectory,D.slice(7)),{recursive:true,mode:0o700});await mkdir(nativeConfigDirectory,{mode:0o700});const bytes=Buffer.from('console.log(JSON.stringify({args:process.argv.slice(2),leak:process.env.UNTRUSTED_EXTRA??null}));setTimeout(()=>{},30000);'),bundle=join(artifactDirectory,D.slice(7),'device.cjs'),runtime={bundleDigest:bytesDigest(bytes),schemaDigest:D,sourceCommitOid:O},native=Buffer.from(canonicalJson({runtime})),nativeFile=join(nativeConfigDirectory,D.slice(7)+'.json');await writeFile(bundle,bytes,{mode:0o600});await writeFile(nativeFile,native,{mode:0o600});const pointer={schemaVersion:1,installationId:'i',repositoryId:'r',bindingEpoch:'1',deviceReleaseId:D,artifactDigest:runtime.bundleDigest,sourceCommitOid:O,schemaDigest:D,nativeConfigDigest:bytesDigest(native)},pointerFile=join(root,'pointer.json');await writeFile(pointerFile,canonicalJson(pointer),{mode:0o600});const nodeExecutable=await realpath(process.execPath),config={schemaVersion:1,installationId:'i',repositoryId:'r',bindingEpoch:'1',pointerFile,launcherLockFile:join(root,'launcher.lock'),artifactDirectory,nativeConfigDirectory,nodeExecutable,nodeDigest:bytesDigest(await readFile(nodeExecutable)),schemaDigest:D,environment:{HOME:root,PATH:'/usr/bin:/bin',TMPDIR:root}},filename=join(root,'launcher.json');await writeFile(filename,canonicalJson(config),{mode:0o600});return {root,config,filename,bundle,nativeFile,close:()=>rm(root,{recursive:true,force:true})};}
const exclusive=path=>spawnSync('python3',['-c','import os,sys,fcntl; f=os.open(sys.argv[1],os.O_RDWR|os.O_CREAT,0o600); fcntl.flock(f,fcntl.LOCK_EX|fcntl.LOCK_NB)',path],{encoding:'utf8',timeout:10000});
async function exit(child){if(child.exitCode!==null||child.signalCode!==null)return;await new Promise(done=>child.once('exit',done));}
test('fixed launcher executes only bound bundle/config and retains pointer gate for the actual Node lifetime',async()=>{const f=await fixture();let child;try{child=spawn('python3',[launcher,f.filename],{env:{...process.env,UNTRUSTED_EXTRA:'must-not-pass'},stdio:['ignore','pipe','pipe']});const data=await new Promise((done,reject)=>{child.stdout.once('data',done);child.once('error',reject);child.once('exit',code=>reject(Error('launcher exited '+code)));});const value=JSON.parse(data.toString());assert.deepEqual(value.args,['--config',f.nativeFile]);assert.equal(value.leak,null);assert.notEqual(exclusive(f.config.launcherLockFile).status,0);child.kill('SIGTERM');await exit(child);child=null;assert.equal(exclusive(f.config.launcherLockFile).status,0);}finally{if(child){child.kill('SIGKILL');await exit(child);}await f.close();}});
test('changed staged bundle/config, foreign binding and unapproved environment cannot execute',async()=>{for(const mode of ['bundle','config','binding','environment']){const f=await fixture();try{if(mode==='bundle')await writeFile(f.bundle,'console.log("UNAUTHORIZED")');if(mode==='config')await writeFile(f.nativeFile,'{}');if(mode==='binding'){const pointer=JSON.parse(await readFile(f.config.pointerFile));pointer.repositoryId='other';await writeFile(f.config.pointerFile,canonicalJson(pointer));}if(mode==='environment'){f.config.environment.NODE_OPTIONS='--eval=console.log(1)';await writeFile(f.filename,canonicalJson(f.config));}const p=spawnSync('python3',[launcher,f.filename],{encoding:'utf8',timeout:20000});assert.equal(p.status,111);assert.equal(p.stdout,'');assert.match(p.stderr,/release_launcher_rejected/);}finally{await f.close();}}});
test('exclusive pointer handoff prevents a concurrent old-pointer launcher admission',async()=>{const f=await fixture();let holder;try{holder=spawn('python3',['-c','import os,sys,fcntl,time; f=os.open(sys.argv[1],os.O_CREAT|os.O_RDWR,0o600); fcntl.flock(f,fcntl.LOCK_EX); print("locked",flush=True); time.sleep(30)',f.config.launcherLockFile],{stdio:['ignore','pipe','pipe']});await new Promise((done,reject)=>{holder.stdout.once('data',done);holder.once('error',reject);});const p=spawnSync('python3',[launcher,f.filename],{encoding:'utf8',timeout:20000});assert.equal(p.status,111);assert.equal(p.stdout,'');}finally{if(holder){holder.kill('SIGKILL');await exit(holder);}await f.close();}});
