import test from 'node:test';import assert from 'node:assert/strict';
import {engineWorld} from '../fixtures/engine-world.mjs';import {IntegratedSourceAuthority} from '../../src/release/authority.mjs';import {canonicalJson} from '../../src/contracts/canonical.mjs';
function authority(w){return new IntegratedSourceAuthority({ledger:w.ledger,binding:w.binding,repository:w.repository,remote:w.remote,validation:()=>w.validation,verifyLineage:head=>w.repository.isAncestor(w.binding,w.baseHead,head)});}
async function integrated(w){const created=await w.create('release-source-create','actual-source.mjs','export const answer = 42;\n');const work=await w.engine.work(w.principal,created.workId),admitted=await w.engine.admit(w.principal,{op:'integrate',requestId:'release-source-integrate',workId:work.workId,expectedRevision:work.revision,generation:work.generation,expectedHead:w.baseHead,policyDigest:w.binding.policyDigest});const [done]=await w.finish([admitted.actionId]);assert.equal(done.status,'succeeded',JSON.stringify(done));return w.ledger.transact(tx=>tx.getPrepared(done.resultId));}

test('release source authority joins actual fixture processes, signed required receipt, exact Git effect and canonical readback',async()=>{const w=await engineWorld();try{const result=await integrated(w),source=await authority(w).verify(result.commitOid,w.binding.policyDigest);assert.equal(source.commitOid,result.commitOid);assert.equal(source.source.treeOid,result.resultTreeOid);assert.equal(source.source.manifestDigest,result.resultTreeSha256);assert.equal(source.validationId,w.ledger.transact(tx=>tx.getEffect(w.sends[0].actionId)).validationId);assert.equal(w.profileRuns.length,2);assert.equal(w.sends.length,1);}finally{await w.close();}});

test('source publication alone has no native release authority; tampered signed receipt cannot grant it',async()=>{const w=await engineWorld();try{await assert.rejects(()=>authority(w).verify(w.baseHead,w.binding.policyDigest),{code:'VALIDATION_FAILED'});const result=await integrated(w);w.ledger.transact(tx=>{const row=tx.get('SELECT run_id,record FROM validation WHERE result_id=?',result.resultId),receipt=JSON.parse(String(row.record));receipt.signature='sha256:'+'0'.repeat(64);tx.run('UPDATE validation SET record=? WHERE run_id=?',canonicalJson(receipt),String(row.run_id));});await assert.rejects(()=>authority(w).verify(result.commitOid,w.binding.policyDigest),{code:'VALIDATION_FAILED'});}finally{await w.close();}});

test('integration evidence and policy are rechecked after asynchronous canonical readback',async()=>{const w=await engineWorld();try{const result=await integrated(w),port=authority(w),resolve=port.o.remote.resolve;port.o.remote={...port.o.remote,resolve:async()=>{const current=await resolve();w.binding.policyDigest='sha256:'+'9'.repeat(64);return current;}};await assert.rejects(()=>port.verify(result.commitOid,result.policyDigest),{code:'STALE_RESULT'});}finally{await w.close();}});
