import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,open} from 'node:fs/promises';
import {constants,readSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {canonicalJson,bytesDigest} from '../../src/contracts/canonical.mjs';
const D='sha256:'+'1'.repeat(64),N='sha256:'+'2'.repeat(64),O='sha1:'+'1'.repeat(40),helper=resolve('tools/release-runit-control.py');
async function fixture(){const root=await mkdtemp(join(tmpdir(),'dev2-fifo-fixture-')),serviceDirectory=join(root,'service'),stateDirectory=join(root,'senders');await mkdir(join(serviceDirectory,'supervise'),{recursive:true,mode:0o700});await mkdir(join(stateDirectory,'effect'),{recursive:true,mode:0o700});const serviceRun=Buffer.from('# fixed fixture, never executed\n');await writeFile(join(serviceDirectory,'run'),serviceRun,{mode:0o700});const pointer={schemaVersion:1,installationId:'i',repositoryId:'r',bindingEpoch:'1',deviceReleaseId:D,artifactDigest:D,sourceCommitOid:O,schemaDigest:D,nativeConfigDigest:D},config={schemaVersion:1,installationId:'i',repositoryId:'r',bindingEpoch:'1',serviceDirectory,serviceRunDigest:bytesDigest(serviceRun),stateDirectory,pointerFile:join(root,'pointer.json')};await writeFile(config.pointerFile,canonicalJson(pointer),{mode:0o600});const filename=join(root,'runit.json');await writeFile(filename,canonicalJson(config),{mode:0o600});const request={effectId:'effect',inputDigest:D,step:'device.stop',expectedDeviceReleaseId:D,targetDeviceReleaseId:N};await writeFile(join(stateDirectory,'effect','intent.json'),canonicalJson(request),{mode:0o600});const setStatus=async(wanted,pid,state)=>{const bytes=Buffer.alloc(20);bytes.writeUInt32LE(pid,12);bytes[17]=wanted.charCodeAt(0);bytes[19]=state;await writeFile(join(serviceDirectory,'supervise/status'),bytes,{mode:0o600});};await setStatus('u',123,1);const fifo=join(serviceDirectory,'supervise/control'),created=spawnSync('python3',['-c','import os,sys;os.mkfifo(sys.argv[1],0o600)',fifo]);assert.equal(created.status,0);const fd=await open(fifo,constants.O_RDWR|constants.O_NONBLOCK);const run=mode=>{const r=spawnSync('python3',[helper,mode,filename,'effect'],{encoding:'utf8',timeout:10000});return {status:r.status,value:JSON.parse(r.stdout)};};return {root,config,run,setStatus,fd,request,close:async()=>{await fd.close();await rm(root,{recursive:true,force:true});}};}
function take(f){const b=Buffer.alloc(4);try{return b.subarray(0,readSync(f.fd.fd,b)).toString();}catch(e){if(e.code==='EAGAIN')return '';throw e;}}
test('real FIFO sends once and lost response reconciles only after desired runsv state acknowledges it',async()=>{const f=await fixture();try{const first=f.run('run');assert.equal(first.status,0);assert.equal(first.value.state,'uncertain');assert.equal(take(f),'d');assert.equal(f.run('run').value.delivery,'unknown');assert.equal(take(f),'');await f.setStatus('d',0,0);const replay=f.run('inspect');assert.equal(replay.value.state,'done');assert.equal(replay.value.delivery,'sent');assert.equal(replay.value.senderStopped,true);assert.deepEqual(f.run('run').value,replay.value);assert.equal(take(f),'');const retained=JSON.parse(await readFile(join(f.config.stateDirectory,'effect/state.json')));assert.equal(retained.effectId,'effect');assert.equal(retained.inputDigest,D);}finally{await f.close();}});
test('inspection fences a delayed not-yet-sent run and never interprets it as a service stop',async()=>{const f=await fixture();try{const observed=f.run('inspect');assert.equal(observed.value.state,'fenced');assert.equal(observed.value.delivery,'not_sent');assert.equal(observed.value.service.pid,123);assert.equal(f.run('run').value.state,'fenced');assert.equal(take(f),'');}finally{await f.close();}});
test('already requested down does not emit another delayed stop byte',async()=>{const f=await fixture();try{await f.setStatus('d',0,0);const result=f.run('run');assert.equal(result.value.state,'done');assert.equal(result.value.delivery,'not_sent');assert.equal(take(f),'');}finally{await f.close();}});
test('foreign pointer or source-unsealed runit hook rejects before a FIFO write',async()=>{for(const mode of ['pointer','hook','run']){const f=await fixture();try{if(mode==='pointer'){const p=JSON.parse(await readFile(f.config.pointerFile));p.deviceReleaseId='sha256:'+'3'.repeat(64);await writeFile(f.config.pointerFile,canonicalJson(p));}if(mode==='hook'){await mkdir(join(f.config.serviceDirectory,'control'));await writeFile(join(f.config.serviceDirectory,'control/t'),'custom hook');}if(mode==='run')await writeFile(join(f.config.serviceDirectory,'run'),'changed');assert.notEqual(f.run('run').status,0);assert.equal(take(f),'');}finally{await f.close();}}});
