import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,symlink,chmod} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {ReleaseStore,exclusiveReleaseLock,readRecord} from '../../src/runtime/release-store.mjs';
import {ActivationController} from '../../src/runtime/activation.mjs';
import {bytesDigest} from '../../src/contracts/canonical.mjs';
const d=bytesDigest(Buffer.from('fixture')),h='sha1:'+'a'.repeat(40);
const metadata={sourceCommit:h,sourceManifest:d,toolchainDigest:d,schemaDigest:d,ledgerMinimum:1,ledgerMaximum:1,receiptDigests:[d]};
async function world(){const root=await mkdtemp(join(tmpdir(),'dev2-release-'));const store=new ReleaseStore(join(root,'installation'),randomBytes(32));await store.init();const build=join(root,'build');await mkdir(build);await writeFile(join(build,'main.mjs'),'export const release=1;\n');const a=await store.stage(build,metadata,async()=>{});await writeFile(join(build,'main.mjs'),'export const release=2;\n');const b=await store.stage(build,metadata,async()=>{});const unlock=exclusiveReleaseLock(join(store.root,'activation.lock'));try{await store.switch(null,a.releaseId);}finally{unlock();}
 const state={release:a.releaseId,running:true,enabled:true,failCandidate:false,stopUnknown:false,starts:[],drains:0};
 const services={drain:async()=>{state.drains++;state.enabled=false;return true;},stop:async()=>{if(state.stopUnknown)return false;state.running=false;return true;},start:async release=>{assert.equal(state.running,false,'no concurrent writer');state.running=true;state.enabled=false;state.release=release;state.starts.push(release);return true;},ready:async release=>state.running&&state.release===release&&!(release===b.releaseId&&state.failCandidate),enable:async release=>{if(state.release!==release)return false;state.enabled=true;return true;}};
 return {root,store,a,b,build,state,services,close:()=>rm(root,{recursive:true,force:true})};}
const intent=w=>({activationId:'activation-1',requestDigest:d,expectedRelease:w.a.releaseId,candidateRelease:w.b.releaseId,deadline:Date.now()+120000});
test('release artifacts are sealed, content addressed, replayable and fail closed on changed bytes',async()=>{const w=await world();try{const again=await w.store.stage(w.build,metadata,async()=>{});assert.equal(again.releaseId,w.b.releaseId);const file=join(w.store.root,'releases',w.b.releaseId.slice(7),'artifact/main.mjs');await chmod(file,0o644);await writeFile(file,'corrupt');await assert.rejects(w.store.read(w.b.releaseId),{code:'INTEGRITY_FAILURE'});}finally{await w.close();}});
test('staging denies symlinks and uncertified inputs without changing the active release',async()=>{const w=await world();try{await assert.rejects(w.store.stage(w.build,metadata,async()=>{throw new Error('no proof');}));await symlink('/etc/passwd',join(w.build,'escape'));await assert.rejects(w.store.stage(w.build,metadata,async()=>{}),{code:'FORBIDDEN'});assert.equal(await w.store.active(),w.a.releaseId);}finally{await w.close();}});
test('inherited-fd flock excludes independent owners and releases when closed',async()=>{const root=await mkdtemp(join(tmpdir(),'dev2-lock-'));try{const file=join(root,'lock');const release=exclusiveReleaseLock(file);assert.throws(()=>exclusiveReleaseLock(file),{code:'EXECUTION_UNAVAILABLE'});const other=spawnSync('flock',['--nonblock',file,'true'],{timeout:3000});assert.equal(other.status,1);release();exclusiveReleaseLock(file)();}finally{await rm(root,{recursive:true,force:true});}});
test('typed activation persists intent, verifies one writer and deduplicates terminal retries',async()=>{const w=await world();try{const c=new ActivationController({store:w.store,services:w.services,ledgerVersion:1}),i=intent(w);const p=await c.prepare(i);assert.equal(p.phase,'prepared');const a=await c.run(i.activationId);assert.equal(a.phase,'active');assert.equal(await w.store.active(),w.b.releaseId);assert.equal(w.state.enabled,true);assert.equal(w.state.starts.length,1);assert.equal((await c.prepare(i)).phase,'active');assert.equal((await c.run(i.activationId)).phase,'active');assert.equal(w.state.starts.length,1);}finally{await w.close();}});
test('failed candidate readiness restores the exact original and records rollback, not success',async()=>{const w=await world();try{w.state.failCandidate=true;const c=new ActivationController({store:w.store,services:w.services,ledgerVersion:1}),i=intent(w);await c.prepare(i);const a=await c.run(i.activationId);assert.equal(a.phase,'rolled_back');assert.equal(await w.store.active(),w.a.releaseId);assert.deepEqual(w.state.starts,[w.b.releaseId,w.a.releaseId]);assert.equal(w.state.enabled,true);}finally{await w.close();}});
test('unknown old writer termination blocks only activation; it never switches or starts another writer',async()=>{const w=await world();try{w.state.stopUnknown=true;const c=new ActivationController({store:w.store,services:w.services,ledgerVersion:1}),i=intent(w);await c.prepare(i);assert.equal((await c.run(i.activationId)).phase,'blocked');assert.equal(await w.store.active(),w.a.releaseId);assert.equal(w.state.starts.length,0);}finally{await w.close();}});
test('crash after the pointer switch is recovered from physical state without a second activation',async()=>{const w=await world();try{let crashed=false;const i=intent(w);const c=new ActivationController({store:w.store,services:w.services,ledgerVersion:1,afterPhase:async r=>{if(r.phase==='checking'&&!crashed){crashed=true;throw Error('simulated crash');}}});await c.prepare(i);await assert.rejects(c.run(i.activationId),/simulated crash/);assert.equal(await w.store.active(),w.b.releaseId);assert.equal(w.state.running,false);const restored=new ActivationController({store:w.store,services:w.services,ledgerVersion:1});const done=await restored.run(i.activationId);assert.equal(done.phase,'rolled_back');assert.equal(await w.store.active(),w.a.releaseId);assert.equal(done.activationId,i.activationId);}finally{await w.close();}});
test('incompatible ledger and stale active expectation reject before any handoff',async()=>{const w=await world();try{const incompatible=new ActivationController({store:w.store,services:w.services,ledgerVersion:2});await assert.rejects(incompatible.prepare(intent(w)),{code:'EXECUTION_UNAVAILABLE'});const c=new ActivationController({store:w.store,services:w.services,ledgerVersion:1});await assert.rejects(c.prepare({...intent(w),expectedRelease:w.b.releaseId}),{code:'STALE_RELEASE'});assert.equal(w.state.drains,0);}finally{await w.close();}});

test('a retained activation outcome survives its expired deadline and rejects an altered intent',async()=>{const w=await world();try{let now=Date.now();const c=new ActivationController({store:w.store,services:w.services,ledgerVersion:1,now:()=>now}),i={...intent(w),deadline:now+1000};await c.prepare(i);const done=await c.run(i.activationId);assert.equal(done.phase,'active');now+=2000;assert.equal((await c.prepare(i)).phase,'active');await assert.rejects(c.prepare({...i,requestDigest:bytesDigest(Buffer.from('changed'))}),{code:'IDEMPOTENCY_MISMATCH'});}finally{await w.close();}});
