import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Ledger} from '../../src/storage/ledger.mjs';
import {ManagedSessions} from '../../src/execution/sessions.mjs';
import {SessionReconciler} from '../../src/execution/session-reconcile.mjs';
const D='sha256:'+'1'.repeat(64),C='1'.repeat(40);
async function fixture(capacity=8){const root=await mkdtemp(join(tmpdir(),'dev2-idle-reconcile-')),binding={installationId:'i',repositoryId:'r',providerRepositoryId:'123',bindingEpoch:'1',provider:'github',remote:'https://github.com/fixture/repo.git',ref:'refs/heads/dev-2',policyDigest:D};let ledger=new Ledger(join(root,'native.sqlite'),binding),now=1000,sessions;const compose=()=>{sessions=new ManagedSessions({ledger,now:()=>now,config:{repositoryOwnerId:'456',repositoryFullName:'fixture/repo',approvedCommit:C,trustedRunnerDigest:D,sessionTimeoutMs:1000,capacity,sealDigest:D}});};compose();const make=index=>{const sessionId='session_'+String(index).padStart(3,'0');let s=sessions.reserve(sessionId);sessions.markLaunchSent(sessionId);const p={repositoryId:'123',repositoryOwnerId:'456',runId:String(100+index),runAttempt:'1',headSha:C,headBranch:s.intent.ref.slice(11),event:'push',workflowPath:'.github/workflows/dev2-executor.yml',status:'in_progress',observedAt:now};s=sessions.selectRun(sessionId,p);return s;};const all=Array.from({length:capacity},(_,i)=>make(i));return {root,all,make,now:()=>now,setNow:value=>{now=value;},ledger:()=>ledger,sessions:()=>sessions,restart:()=>{ledger.close();ledger=new Ledger(join(root,'native.sqlite'),binding);compose();},close:async()=>{ledger.close();await rm(root,{recursive:true,force:true});}};}
test('expired native-ready resources release capacity only through exact provider terminal readback',async()=>{const f=await fixture();try{f.setNow(3000);const seen=[],provider={refresh:async(id,force)=>{seen.push(id);assert.equal(force,true);const s=f.sessions().ledger.transact(tx=>f.sessions().session(tx,id));return f.sessions().providerStopped(id,{...s.run,status:'completed',observedAt:f.now()});}},reconciler=new SessionReconciler({sessions:f.sessions(),provider,now:f.now});assert.equal(await reconciler.whenFull(),8);assert.equal(seen.length,8);assert.equal(f.sessions().open().length,0);assert.equal(f.sessions().reserve('new_resource').state,'reserved');assert.equal(f.ledger().transact(tx=>Number(tx.get('SELECT count(*) n FROM managed_assignment').n)),0);for(const before of f.all){const after=f.ledger().transact(tx=>f.sessions().session(tx,before.intent.sessionId));assert.equal(after.intentDigest,before.intentDigest);assert.deepEqual(JSON.parse(JSON.stringify(after.intent)),JSON.parse(JSON.stringify(before.intent)));assert.equal(after.run.runId,before.run.runId);assert.equal(after.state,'closed');}}finally{await f.close();}});
test('unknown/still-running provider resources stay occupied while independent completed resources progress',async()=>{const f=await fixture();try{f.setNow(3000);const provider={refresh:async id=>{const s=f.ledger().transact(tx=>f.sessions().session(tx,id));if(id.endsWith('000'))throw Error('provider read unavailable');if(id.endsWith('001'))return s;return f.sessions().providerStopped(id,{...s.run,status:'completed',observedAt:f.now()});}},reconciler=new SessionReconciler({sessions:f.sessions(),provider,now:f.now});assert.equal(await reconciler.refresh(),6);assert.deepEqual(f.sessions().open().map(s=>s.intent.sessionId),['session_000','session_001']);assert.equal(f.sessions().open().every(s=>s.stoppedAt===null&&!s.cancelRequested),true);}finally{await f.close();}});
test('fresh warm sessions are not churned and concurrent admission coalesces bounded reads',async()=>{const f=await fixture();try{let calls=0;const provider={refresh:async id=>{calls++;await new Promise(done=>setImmediate(done));return f.ledger().transact(tx=>f.sessions().session(tx,id));}},reconciler=new SessionReconciler({sessions:f.sessions(),provider,now:f.now});assert.equal(await reconciler.whenFull(),0);assert.equal(calls,0);f.setNow(12000);await Promise.all(Array.from({length:8},()=>reconciler.whenFull()));assert.equal(calls,8);await reconciler.whenFull();assert.equal(calls,8);assert.equal(f.sessions().open().length,8);}finally{await f.close();}});
test('old-owner live resources can be re-observed without changing attempts or using stale owner handles',async()=>{const f=await fixture(1);try{const oldLedger=f.ledger(),old=new SessionReconciler({sessions:f.sessions(),provider:{refresh:async()=>{throw Error('must not run');}},now:f.now});f.restart();assert.notEqual(f.ledger().ownerEpoch,oldLedger.ownerEpoch);assert.throws(()=>old.whenFull(),{code:'STALE_REVISION'});let calls=0;const next=new SessionReconciler({sessions:f.sessions(),provider:{refresh:async id=>{calls++;return f.ledger().transact(tx=>f.sessions().session(tx,id));}},now:f.now});await next.whenFull();assert.equal(calls,1);assert.equal(f.sessions().open().length,1);}finally{await f.close();}});
test('configuration32 is not an observation ceiling; repeated bounded pages progress through all retained identities',async()=>{const f=await fixture(32);try{f.setNow(3000);const seen=new Set(),reconciler=new SessionReconciler({sessions:f.sessions(),provider:{refresh:async id=>{seen.add(id);const s=f.ledger().transact(tx=>f.sessions().session(tx,id));return f.sessions().providerStopped(id,{...s.run,status:'completed',observedAt:f.now()});}},now:f.now});assert.equal(await reconciler.whenFull(),16);f.setNow(14000);assert.equal(await reconciler.refresh(),16);assert.equal(seen.size,32);assert.equal(f.sessions().open().length,0);}finally{await f.close();}});
