import test from 'node:test';import assert from 'node:assert/strict';
import {engineWorld} from '../fixtures/engine-world.mjs';import {Dev2Error} from '../../src/contracts/errors.mjs';
import {canonicalJson} from '../../src/contracts/canonical.mjs';
const N='sha256:'+'2'.repeat(64),C='sha1:'+'3'.repeat(40);
function input(w,id){return {op:'policy.adopt',requestId:id,repository:'self',integratedCommit:C,policyPath:'config/policy.json',expectedPolicyDigest:w.binding.policyDigest,newPolicyDigest:N};}
function output(w){return {kind:'policy',integratedCommit:C,previousPolicyDigest:w.binding.policyDigest,policyDigest:N};}
// D0001 records deliberately decode to null-prototype objects. Compare every
// canonical field/byte, not a JavaScript prototype absent from the wire contract.
function exactOutput(actual,expected){assert.equal(canonicalJson(actual),canonicalJson(expected));assert.notEqual(canonicalJson(actual),canonicalJson({...expected,policyDigest:'sha256:'+'9'.repeat(64)}));}
async function settled(w,id){const rows=await w.finish([id]);await Promise.allSettled([...w.engine.running.values()]);return rows[0];}
test('response loss after special commit recovers exact output without a second invocation or effect',async()=>{const w=await engineWorld();try{let sends=0,retained=null;w.engine.o.special=async()=>{sends++;retained=output(w);throw new Dev2Error('EXECUTION_UNAVAILABLE');};w.engine.o.specialRecovery=async()=>({stopped:true,effectResolved:true,output:retained});const request=input(w,'lost-special'),a=await w.engine.admit(w.principal,request);assert.equal((await settled(w,a.actionId)).status,'succeeded');exactOutput(w.engine.metadata('action-result:'+a.actionId),retained);const again=await w.engine.admit(w.principal,request);assert.equal(again.actionId,a.actionId);assert.equal(again.deduplicated,true);assert.equal(sends,1);}finally{await w.close();}});
test('managed-container stopped proof cannot terminate an uncertain release/policy effect',async()=>{const w=await engineWorld();try{w.engine.o.special=async()=>{throw new Dev2Error('EFFECT_UNCERTAIN');};w.engine.o.attemptStopped=async()=>true;const a=await w.engine.admit(w.principal,input(w,'uncertain-special'));assert.equal((await settled(w,a.actionId)).status,'blocked');assert.equal(w.ledger.transact(tx=>tx.reservations().length),1);const created=await w.create('unrelated-source','independent.txt','not globally fenced\n');assert.equal(created.status,'succeeded');}finally{await w.close();}});
test('public observation reconciles only an exact retained terminal effect; it never launches a replacement',async()=>{const w=await engineWorld();try{let calls=0,proven=false;w.engine.o.special=async()=>{calls++;throw new Dev2Error('EFFECT_UNCERTAIN');};w.engine.o.specialRecovery=async()=>({stopped:true,effectResolved:proven,output:proven?output(w):null});const a=await w.engine.admit(w.principal,input(w,'observe-special'));assert.equal((await settled(w,a.actionId)).status,'blocked');proven=true;const r=await w.app.invoke(w.principal,'dev_observe',{apiVersion:1,selector:{actionIds:[a.actionId]},limit:8,waitMs:0});assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.data.actions[0].status,'succeeded');assert.equal(r.data.actions[0].step,'complete.recovered');exactOutput(r.data.actions[0].output,output(w));assert.equal(calls,1);}finally{await w.close();}});
test('proved-not-applied retry preserves action, request and original deadline while observation does not execute',async()=>{const w=await engineWorld();try{let calls=0,safe=false;w.engine.o.special=async()=>{calls++;if(calls===1)throw new Dev2Error('EXECUTION_UNAVAILABLE');return output(w);};w.engine.o.specialRecovery=async()=>({stopped:safe,effectResolved:safe,output:null});const request=input(w,'retry-special'),a=await w.engine.admit(w.principal,request),first=await settled(w,a.actionId);assert.equal(first.status,'blocked');safe=true;await w.engine.specialRecovery.observe(w.principal,a.actionId,false);assert.equal(calls,1);assert.equal(w.ledger.transact(tx=>tx.getAction(a.actionId)).status,'blocked');const retry=await w.engine.admit(w.principal,request);assert.equal(retry.actionId,a.actionId);assert.equal(retry.deduplicated,true);const done=await settled(w,a.actionId);assert.equal(done.status,'succeeded');assert.equal(done.attempt,'2');assert.equal(done.deadline,first.deadline);assert.equal(calls,2);}finally{await w.close();}});
