import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm,chmod} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {SystemdBrokerService} from '../../src/runtime/systemd.mjs';
import {ActivationHistory} from '../../src/runtime/activation-history.mjs';
import {recordDigest} from '../../src/contracts/canonical.mjs';
const hash=recordDigest('dev2.release.v1',{id:1});
async function world(){const root=await mkdtemp(join(tmpdir(),'dev2-service-')),group='/user.slice/dev2-broker.service';await mkdir(join(root,group),{recursive:true});await writeFile(join(root,group,'cgroup.events'),'populated 0\nfrozen 0\n');
 const calls=[],control=[];let state={LoadState:'loaded',ActiveState:'inactive',SubState:'dead',MainPID:'0',ControlGroup:group,KillMode:'control-group',Restart:'no'};
 const options={systemctl:'/usr/bin/systemctl',unit:'dev2-broker.service',environment:{PATH:'/usr/bin'},cgroupRoot:root,controlGroup:group,command:async(_exe,args)=>{calls.push(args);return {exitCode:0,signal:null,timedOut:false,spawnFailed:false,discardedBytes:0,stdout:Buffer.from(Object.entries(state).map(([k,v])=>k+'='+v).join('\n')),stderr:Buffer.alloc(0)};},readiness:async()=>({pid:42,releaseId:hash,ready:true}),control:async(op,release)=>{control.push([op,release]);return true;},activeRelease:async()=>hash};
 return {root,group,options,calls,control,service:new SystemdBrokerService(options),setState:next=>{state={...state,...next};},close:()=>rm(root,{recursive:true,force:true})};}
test('inactive service with a populated cgroup is not a stopped writer',async()=>{const w=await world();try{assert.equal((await w.service.observe()).state,'stopped');await writeFile(join(w.root,w.group,'cgroup.events'),'populated 1\n');assert.equal((await w.service.observe()).state,'uncertain');assert.equal(await w.service.stop(),false);}finally{await w.close();}});
test('readiness PID and exact service unit configuration are checked before enable',async()=>{const w=await world();try{w.setState({ActiveState:'active',SubState:'running',MainPID:'42'});assert.equal((await w.service.observe()).releaseId,hash);assert.equal(await w.service.enable(hash),true);w.setState({MainPID:'43'});assert.equal(await w.service.enable(hash),false);w.setState({MainPID:'42',KillMode:'process'});assert.equal((await w.service.observe()).state,'uncertain');}finally{await w.close();}});
test('only one fixed unit and trusted expected active pointer can be started',async()=>{const w=await world();try{await w.service.start(hash);assert.equal(w.calls.at(-1).at(-1),'dev2-broker.service');assert.ok(w.calls.at(-1).includes('--user'));await assert.rejects(()=>w.service.start(recordDigest('dev2.release.v1',{id:2})),{code:'STALE_RELEASE'});for(const unit of ['ssh.service','dev2-x.service --all','../dev2-x.service'])assert.throws(()=>new SystemdBrokerService({...w.options,unit}),{code:'INVALID_ARGUMENT'});}finally{await w.close();}});
test('unavailable system manager never becomes a fabricated stopped or ready state',async()=>{const w=await world();try{w.options.command=async()=>({exitCode:1,signal:null,timedOut:false,spawnFailed:false,discardedBytes:0,stdout:Buffer.alloc(0),stderr:Buffer.from('unavailable')});const service=new SystemdBrokerService(w.options);assert.equal((await service.observe()).state,'uncertain');assert.equal(await service.stop(),false);await assert.rejects(()=>service.start(hash),{code:'EXECUTION_UNAVAILABLE'});}finally{await w.close();}});
test('terminal activation identity survives process-local cache loss and detects corruption',async()=>{const w=await world();try{const history=new ActivationHistory(join(w.root,'retained')),record={activationId:'activation1',requestDigest:hash,expectedRelease:hash,candidateRelease:hash,originalRelease:hash,phase:'active',deadline:1,observedRelease:hash,writerStopped:false,rollbackRequested:false,outcome:'activated'};
 await history.retain(record);const reopened=new ActivationHistory(join(w.root,'retained'));assert.deepEqual(JSON.parse(JSON.stringify(await reopened.lookup(record.activationId))),record);await reopened.retain(record);await assert.rejects(()=>reopened.retain({...record,outcome:'different'}),{code:'IDEMPOTENCY_MISMATCH'});
 await chmod(history.path(record.activationId),0o600);await writeFile(history.path(record.activationId),'{}');await assert.rejects(()=>reopened.lookup(record.activationId));
 }finally{await w.close();}});

test('missing cgroup events in an existing group are uncertainty, not proof of absence',async()=>{const w=await world();try{await rm(join(w.root,w.group,'cgroup.events'));assert.equal((await w.service.observe()).state,'uncertain');assert.equal(await w.service.stop(),false);}finally{await w.close();}});
