import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,chmod,symlink,readdir,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {gitWorld} from '../fixtures/git-world.mjs';
import {controllerDefinition,prepareController,verifyController,CONTROLLER_FILES} from '../../src/validation/controller.mjs';
const D='sha256:'+'1'.repeat(64);
async function fixture(){const files=await Promise.all(CONTROLLER_FILES.map(async path=>({path,content:await readFile(path)})));files.push({path:'test/core/known.test.mjs',content:Buffer.from('mandatory core\n')},{path:'test/integration/known.test.mjs',content:Buffer.from('mandatory integration\n')},{path:'private-control-canary',content:Buffer.from('must not mount\n')});return gitWorld(files);}
test('trusted controller is an exact approved Git artifact, not the checkout, credentials or candidate test files',async()=>{const w=await fixture();try{const definition=controllerDefinition(w.source),options={repository:w.remote,source:w.source,cacheDirectory:join(w.root,'controller-cache'),expectedDigest:definition.digest};const first=await prepareController(options),again=await prepareController(options);assert.equal(first.directory,again.directory);assert.deepEqual(await readdir(join(first.directory,'node_modules')),[]);await assert.rejects(readFile(join(first.directory,'private-control-canary')),{code:'ENOENT'});await assert.rejects(readFile(join(first.directory,'test/core/known.test.mjs')),{code:'ENOENT'});assert.deepEqual(first.definition.tests.core,['test/core/known.test.mjs']);await assert.rejects(prepareController({...options,expectedDigest:D}),{code:'INTEGRITY_FAILURE'});assert.equal((await verifyController(first.directory,first.digest)).digest,first.digest);}finally{await w.close();}});
test('tampered controller bytes and a same-content symlink are refused on reuse',async()=>{const w=await fixture();try{const definition=controllerDefinition(w.source),artifact=await prepareController({repository:w.remote,source:w.source,cacheDirectory:join(w.root,'controller-cache'),expectedDigest:definition.digest}),file=join(artifact.directory,'tools/validate.mjs'),bytes=await readFile(file);await chmod(file,0o644);await writeFile(file,'process.exit(0);\n');await assert.rejects(verifyController(artifact.directory,artifact.digest),{code:'INTEGRITY_FAILURE'});await rm(file);const elsewhere=join(w.root,'same-bytes');await writeFile(elsewhere,bytes);await symlink(elsewhere,file);await assert.rejects(verifyController(artifact.directory,artifact.digest),{code:'INTEGRITY_FAILURE'});}finally{await w.close();}});
