import {canonicalJson,parseRecord,recordDigest} from '../contracts/canonical.mjs';
import {digest,id} from '../contracts/identity.mjs';
import {requireThat} from '../contracts/errors.mjs';
import {releaseIdentity,releaseManifest,releaseNamespace,runtimePair,activationIntent,activationNamespace,compatiblePair} from './manifest.mjs';
import {releaseTransition} from './contract-migration.mjs';
/** @typedef {import('./types.js').RuntimePair} Pair */
/** @typedef {import('./types.js').ActivationIntent} Intent */
/** @typedef {import('./types.js').ActivationRecord} Activation */
/** @typedef {import('./backend.mjs').Build} Build */
/** @typedef {import('./backend.mjs').StageEffect} StageEffect */
/** This service has no work admission or validation authority. Its only admission
 * caller is the installed native owner, authenticated by role-separated private
 * RPC. Native must verify required+production receipts before handing off a build.
 * Helper rechecks fixed artifact/config identities and owns only retained rollout.
 */
export class FixedReleaseService {
 /** @param {{journal:import('./journal.mjs').ActivationJournal,controller:import('./activation.mjs').ActivationController,artifacts:import('./artifacts.mjs').ReleaseArtifactStore,configs:import('./device-configs.mjs').DeviceReleaseConfigs,edge:Pick<import('./cloudflare.mjs').CloudflareReleasePort,'active'|'version'|'verifyVersion'|'reconcileStage'|'upload'|'reconcileActivation'|'activate'>,nativeStatus:()=>Promise<import('./device-port.mjs').NativeStatus>,baseline:Pair,installationId:string,repositoryId:string,bindingEpoch:string,installationSealDigest:string,executor:{sealDigest:string,controllerDigest:string,workflowDigest:string},now?:()=>number}} options */
 constructor(options){this.o=options;this.journal=options.journal;this.epoch=this.journal.ownerEpoch;this.now=options.now??Date.now;this.running=/** @type {Promise<void>|null} */(null);digest(options.installationSealDigest);runtimePair(options.baseline);for(const d of Object.values(options.executor))digest(d);}
 assert(){requireThat(!this.journal.closed&&this.journal.ownerEpoch===this.epoch,'STALE_REVISION');}
 /** @template T @param {string} key @returns {T|null} */
 read(key){this.assert();const row=this.journal.db.prepare('SELECT value FROM meta WHERE key=?').get(key);return row?/** @type {T} */(parseRecord(String(row.value),1048576)):null;}
 /** @param {string} key @param {unknown} value */
 retain(key,value){this.assert();this.journal.transact(()=>{const old=this.read(key);if(old)requireThat(canonicalJson(old)===canonicalJson(value),'IDEMPOTENCY_MISMATCH');else this.journal.db.prepare('INSERT INTO meta VALUES(?,?)').run(key,canonicalJson(value));});}
 /** Last terminal pair is durable in the same activation journal. A crash before
  * any convenience projection cannot erase which exact release became active.
  * @returns {Pair} */
 retainedPair(){this.assert();const row=this.journal.db.prepare("SELECT record FROM activation WHERE active=0 ORDER BY rowid DESC LIMIT 1").get();if(!row)return runtimePair(this.o.baseline);const record=/** @type {Activation} */(parseRecord(String(row.record),1048576));requireThat(record.observedPair,'INTEGRITY_FAILURE');const expected=record.phase==='active'?record.intent.target:record.intent.previous;requireThat(canonicalJson(record.observedPair)===canonicalJson(expected),'INTEGRITY_FAILURE');return runtimePair(record.observedPair);}
 /** @returns {Promise<Pair>} */
 async activePair(){this.assert();requireThat(!this.journal.active(),'EFFECT_UNCERTAIN','Rollout has a retained incomplete effect');const pair=this.retainedPair(),[pointer,native,edge]=await Promise.all([this.o.configs.pointerFor(pair),this.o.nativeStatus(),this.o.edge.active()]);this.assert();requireThat(!this.journal.active()&&canonicalJson(this.retainedPair())===canonicalJson(pair)&&canonicalJson(await this.o.configs.current())===canonicalJson(pointer),'STALE_RESULT');
  requireThat(native.installationId===this.o.installationId&&native.repositoryId===this.o.repositoryId&&native.bindingEpoch===this.o.bindingEpoch&&native.connected&&native.accepting&&native.deviceReleaseId===pair.deviceReleaseId&&native.sourceCommitOid===pair.deviceSourceCommitOid&&native.bundleDigest===pair.deviceArtifactDigest&&native.schemaDigest===pair.schemaDigest&&edge.versionId===pair.edgeVersionId&&native.edge?.versionId===pair.edgeVersionId&&native.edge.bundleDigest===pair.edgeArtifactDigest&&native.edge.sourceCommitOid===pair.edgeSourceCommitOid&&native.edge.schemaDigest===pair.schemaDigest,'EFFECT_UNCERTAIN','Actual active pair is not the retained pair');return pair;
 }
 /** C2-2 bootstrap-only retained-pair edge repair. Inspection is read-only;
  * apply retains one exact plan/effect before the existing provider sender runs.
  * @param {string} expectedReleaseId @param {string|null} [expectedPlanDigest] */
 async recoverEdgeDrift(expectedReleaseId,expectedPlanDigest=null){
  digest(expectedReleaseId);if(expectedPlanDigest!==null)digest(expectedPlanDigest);this.assert();
  /** @param {import('./types.js').ActivationEffect} effect @param {import('./types.js').ActivationReceipt} receipt */
  const checked=(effect,receipt)=>{requireThat(receipt&&receipt.effectId===effect.effectId&&receipt.inputDigest===effect.inputDigest&&['applied','not_applied','pending','failed','conflict'].includes(receipt.kind)&&typeof receipt.senderStopped==='boolean'&&Number.isSafeInteger(receipt.observedAt)&&receipt.observedAt<=this.now()+5000&&receipt.observedAt>=this.now()-60000&&receipt.output&&typeof receipt.output==='object'&&!Array.isArray(receipt.output),'INTEGRITY_FAILURE','Unbound edge-drift recovery readback');if(['applied','not_applied','failed','conflict'].includes(receipt.kind))requireThat(receipt.senderStopped,'EFFECT_UNCERTAIN','Edge repair sender may still be active');if(receipt.kind==='applied')requireThat(receipt.output.edgeVersionId===effect.target.edgeVersionId,'INTEGRITY_FAILURE','Edge repair applied another version');return receipt;};
  const inspect=async()=>{this.assert();requireThat(!this.journal.active(),'EFFECT_UNCERTAIN','An activation owns the helper');const target=this.retainedPair();requireThat(target.releaseId===expectedReleaseId&&target.releaseId!==this.o.baseline.releaseId,'STALE_RELEASE','Edge repair must target the exact retained non-baseline release');
   const admitted=/** @type {{build:Build,previous:Pair}|null} */(this.read('helper.build:'+target.releaseId));requireThat(admitted,'EXECUTION_UNAVAILABLE','Retained release build is unavailable');const m=releaseManifest(admitted.build.manifest),previous=runtimePair(admitted.previous),namespace=releaseNamespace(m),unchanged=m.device.artifactDigest===previous.deviceArtifactDigest&&m.device.sourceCommitOid===previous.deviceSourceCommitOid;
   requireThat(releaseIdentity(m)===target.releaseId&&m.sourceCommitOid===target.sourceCommitOid&&m.schemaDigest===target.schemaDigest&&m.device.artifactDigest===target.deviceArtifactDigest&&m.device.sourceCommitOid===target.deviceSourceCommitOid&&m.edge.artifactDigest===target.edgeArtifactDigest&&m.edge.sourceCommitOid===target.edgeSourceCommitOid&&target.deviceReleaseId===(unchanged?previous.deviceReleaseId:target.releaseId)&&canonicalJson(m.protocol)===canonicalJson(target.protocol)&&canonicalJson(m.ledger)===canonicalJson(target.ledger),'INTEGRITY_FAILURE','Retained build does not define the retained pair');await this.o.artifacts.verify(target.releaseId,m,admitted.build.refs);this.assert();
   const [pointer,native,active]=await Promise.all([this.o.configs.pointerFor(target),this.o.nativeStatus(),this.o.edge.active()]);this.assert();requireThat(!this.journal.active()&&canonicalJson(this.retainedPair())===canonicalJson(target)&&canonicalJson(await this.o.configs.current())===canonicalJson(pointer),'STALE_RESULT','Retained pair changed during edge repair inspection');
   requireThat(native.installationId===this.o.installationId&&native.repositoryId===this.o.repositoryId&&native.bindingEpoch===this.o.bindingEpoch&&native.connected&&native.accepting&&native.deviceReleaseId===target.deviceReleaseId&&native.sourceCommitOid===target.deviceSourceCommitOid&&native.bundleDigest===target.deviceArtifactDigest&&native.schemaDigest===target.schemaDigest&&native.edge&&native.edge.versionId===active.versionId&&native.edge.bundleDigest===target.edgeArtifactDigest&&native.edge.schemaDigest===target.schemaDigest&&active.versionId!==target.edgeVersionId&&native.edge.sourceCommitOid!==target.edgeSourceCommitOid,'EFFECT_UNCERTAIN','Observed runtime is not the bounded same-bytes edge split');
   const observedVersion=this.o.edge.verifyVersion(await this.o.edge.version(active.versionId),native.edge.sourceCommitOid,native.edge.bundleDigest,undefined,namespace),retainedVersion=this.o.edge.verifyVersion(await this.o.edge.version(target.edgeVersionId),target.edgeSourceCommitOid,target.edgeArtifactDigest,m.edge.compatibilityDate,namespace);requireThat(observedVersion.etag===retainedVersion.etag,'INTEGRITY_FAILURE','Observed Worker bytes differ from retained version');this.assert();
   const observed=runtimePair({...target,edgeVersionId:active.versionId,edgeArtifactDigest:native.edge.bundleDigest,edgeSourceCommitOid:native.edge.sourceCommitOid}),basis={installationId:this.o.installationId,repositoryId:this.o.repositoryId,bindingEpoch:this.o.bindingEpoch,retained:target,observed},activationId=recordDigest(namespace+'.retained-edge-drift-repair.v1',basis).slice(7),fields={activationId,direction:/** @type {const} */('rollback'),step:/** @type {const} */('edge.activate'),expected:observed,target},inputDigest=recordDigest(namespace+'.retained-edge-drift-repair-effect-input.v1',fields),effect={...(namespace==='tdev'?{identityNamespace:/** @type {const} */('tdev')}:{ }),...fields,inputDigest,effectId:recordDigest(namespace+'.retained-edge-drift-repair-effect.v1',{activationId,inputDigest}).slice(7)},planBody={schemaVersion:1,retainedReleaseId:target.releaseId,observedEdgeVersionId:observed.edgeVersionId,observedEdgeSourceCommitOid:observed.edgeSourceCommitOid,targetEdgeVersionId:target.edgeVersionId,targetEdgeSourceCommitOid:target.edgeSourceCommitOid,effectId:effect.effectId},planDigest=recordDigest('tdev.release-edge-drift-recovery-plan.v1',{...planBody,retained:target,observed,effect});return {plan:{kind:'tdev.release-edge-drift-recovery-plan',...planBody,planDigest},effect};};
  /** @param {{schemaVersion:1,kind:string,plan:Awaited<ReturnType<typeof inspect>>['plan'],effect:import('./types.js').ActivationEffect}} retained */
  const apply=async retained=>{requireThat(retained.schemaVersion===1&&retained.kind==='tdev.release-edge-drift-recovery'&&retained.plan.planDigest===expectedPlanDigest&&retained.plan.retainedReleaseId===expectedReleaseId,'INTEGRITY_FAILURE','Retained edge repair plan changed');let receipt=checked(retained.effect,await this.o.edge.reconcileActivation(retained.effect));this.assert();if(receipt.kind==='applied')return {kind:'tdev.release-edge-drift-recovered',planDigest:retained.plan.planDigest,retainedReleaseId:expectedReleaseId,effectId:retained.effect.effectId,edgeVersionId:retained.effect.target.edgeVersionId};requireThat(receipt.kind==='not_applied','EFFECT_UNCERTAIN','Exact edge repair effect is not safely sendable');const fresh=await inspect();requireThat(canonicalJson(fresh.plan)===canonicalJson(retained.plan)&&canonicalJson(fresh.effect)===canonicalJson(retained.effect),'STALE_RESULT','Edge drift changed after inspection');receipt=checked(retained.effect,await this.o.edge.activate(retained.effect));this.assert();requireThat(receipt.kind==='applied','EFFECT_UNCERTAIN','Exact edge repair effect is unresolved');return {kind:'tdev.release-edge-drift-recovered',planDigest:retained.plan.planDigest,retainedReleaseId:expectedReleaseId,effectId:retained.effect.effectId,edgeVersionId:retained.effect.target.edgeVersionId};};
  if(expectedPlanDigest!==null){const key='helper.edge-drift-repair:'+expectedPlanDigest,old=/** @type {{schemaVersion:1,kind:string,plan:Awaited<ReturnType<typeof inspect>>['plan'],effect:import('./types.js').ActivationEffect}|null} */(this.read(key));if(old)return apply(old);const fresh=await inspect();requireThat(fresh.plan.planDigest===expectedPlanDigest,'STALE_RESULT','Edge drift plan changed before apply');const retained={schemaVersion:/** @type {const} */(1),kind:'tdev.release-edge-drift-recovery',plan:fresh.plan,effect:fresh.effect};this.retain(key,retained);return apply(retained);}
  return (await inspect()).plan;
 }
 /** Authenticated native handoff only; candidate output cannot call this method.
  * @param {Build} build @param {Pair} previous */
 async admitBuild(build,previous){this.assert();const m=releaseManifest(build.manifest);runtimePair(previous);requireThat(m.repositoryId===this.o.repositoryId&&m.bindingEpoch===this.o.bindingEpoch&&m.installationSealDigest===this.o.installationSealDigest&&canonicalJson(m.executor)===canonicalJson(this.o.executor)&&build.receipt!==null&&typeof build.receipt==='object'&&!Array.isArray(build.receipt),'FORBIDDEN','Unenrolled native release build');
  const releaseId=releaseIdentity(m);requireThat(Buffer.byteLength(canonicalJson(build))<=262144,'LIMIT_EXCEEDED');await this.o.artifacts.verify(releaseId,m,build.refs);this.assert();
  this.retain('helper.build:'+releaseId,{build,previous});await this.o.configs.prepare(build,previous);this.assert();return releaseId;
 }
 /** @param {StageEffect} effect */
 async reconcileStage(effect){this.assert();const admitted=/** @type {{build:Build,previous:Pair}|null} */(this.read('helper.build:'+digest(effect.releaseId)));if(admitted)requireThat(admitted.build.manifest.edge.artifactDigest===effect.artifactDigest&&admitted.previous.edgeVersionId===effect.expectedVersionId,'INTEGRITY_FAILURE');return this.o.edge.reconcileStage(effect);}
 /** @param {StageEffect} effect @param {Build} build */
 async stage(effect,build){const previous=await this.activePair();requireThat(previous.edgeVersionId===effect.expectedVersionId,'STALE_RESULT');const releaseId=await this.admitBuild(build,previous);requireThat(releaseId===effect.releaseId,'INTEGRITY_FAILURE');return this.o.edge.upload(effect,build);}
 /** Same existing activation is observed without manufacturing a fresh effect.
  * Initial authorization has already been checked by native immediately before
  * this authenticated handoff and is retained even across that broker's stop.
  * @param {Intent} input @param {Build} build */
 async begin(input,build){const intent=activationIntent(input);this.assert();requireThat(intent.installationId===this.o.installationId&&intent.repositoryId===this.o.repositoryId&&intent.bindingEpoch===this.o.bindingEpoch,'FORBIDDEN');
  requireThat(!intent.migration?.rollbackOf,'FORBIDDEN','Rollback is derived only by the helper');
  const old=this.journal.read(intent.activationId);if(old){requireThat(canonicalJson(old.intent)===canonicalJson(intent),'IDEMPOTENCY_MISMATCH');return old;}
  requireThat(this.now()<intent.deadline&&intent.createdAt<=this.now()+2000,'EXECUTION_UNAVAILABLE');requireThat(canonicalJson(await this.activePair())===canonicalJson(intent.previous),'STALE_RESULT');
  const releaseId=await this.admitBuild(build,intent.previous),m=build.manifest,t=intent.target,p=intent.previous;
  requireThat(releaseId===t.releaseId&&m.sourceCommitOid===t.sourceCommitOid&&m.schemaDigest===t.schemaDigest&&m.device.artifactDigest===t.deviceArtifactDigest&&m.device.sourceCommitOid===t.deviceSourceCommitOid&&m.edge.artifactDigest===t.edgeArtifactDigest&&m.edge.sourceCommitOid===t.edgeSourceCommitOid&&canonicalJson(m.protocol)===canonicalJson(t.protocol)&&canonicalJson(m.ledger)===canonicalJson(t.ledger),'INTEGRITY_FAILURE','Activation does not name staged bytes');
  const unchanged=m.device.artifactDigest===p.deviceArtifactDigest&&m.device.sourceCommitOid===p.deviceSourceCommitOid;requireThat(t.deviceReleaseId===(unchanged?p.deviceReleaseId:releaseId),'INTEGRITY_FAILURE');
  if(intent.migration)requireThat(canonicalJson(await releaseTransition(this.o.artifacts,p,t))===canonicalJson(intent.migration),'INTEGRITY_FAILURE','Independent helper transition differs');else compatiblePair(p,t,1);
  await this.o.configs.pointerFor(t);
  this.o.edge.verifyVersion(await this.o.edge.version(t.edgeVersionId),t.edgeSourceCommitOid,t.edgeArtifactDigest,m.edge.compatibilityDate,releaseNamespace(m));this.assert();requireThat(!this.journal.active()&&canonicalJson(await this.activePair())===canonicalJson(p),'STALE_RESULT');
  return this.journal.begin(intent);
 }
 /** Explicit operator rollback accepts only the latest successful activation ID.
  * The fixed helper derives the reverse target from that retained intent and never
  * accepts a caller-supplied pair, build, provider target or command. Response-loss
  * retries resolve to one deterministic reverse activation identity.
  * @param {string} sourceActivationId */
 async rollback(sourceActivationId){id(sourceActivationId);this.assert();const source=this.journal.read(sourceActivationId);requireThat(source&&source.phase==='active'&&source.observedPair&&canonicalJson(source.observedPair)===canonicalJson(source.intent.target),'STALE_RELEASE','Only a successful retained activation can be rolled back');
  const namespace=activationNamespace(source.intent),rollbackActivationId=recordDigest(namespace+'.explicit-release-rollback.v1',{installationId:this.o.installationId,sourceActivationId,intentDigest:source.intentDigest}).slice(7),existing=this.journal.read(rollbackActivationId);if(existing)return existing;
  const current=await this.activePair();requireThat(canonicalJson(current)===canonicalJson(source.intent.target),'STALE_RESULT','Rollback source is not the active pair');const target=runtimePair(source.intent.previous);
  const forward=source.intent.migration?await releaseTransition(this.o.artifacts,target,current):null;
  if(forward)requireThat(canonicalJson(forward)===canonicalJson(source.intent.migration),'INTEGRITY_FAILURE','Retained forward transition changed');else compatiblePair(current,target,1);
  const migration=forward?{...forward,previousSchemaDigest:current.schemaDigest,targetSchemaDigest:target.schemaDigest,rollbackOf:sourceActivationId}:undefined;
  if(target.releaseId===this.o.baseline.releaseId)requireThat(canonicalJson(target)===canonicalJson(runtimePair(this.o.baseline)),'INTEGRITY_FAILURE','Baseline rollback pair changed');
  else{const admitted=/** @type {{build:Build,previous:Pair}|null} */(this.read('helper.build:'+target.releaseId));requireThat(admitted,'EXECUTION_UNAVAILABLE','Previous release build is not retained');const m=releaseManifest(admitted.build.manifest),p=admitted.previous,t=target,unchanged=m.device.artifactDigest===p.deviceArtifactDigest&&m.device.sourceCommitOid===p.deviceSourceCommitOid;requireThat(releaseIdentity(m)===t.releaseId&&m.sourceCommitOid===t.sourceCommitOid&&m.schemaDigest===t.schemaDigest&&m.device.artifactDigest===t.deviceArtifactDigest&&m.device.sourceCommitOid===t.deviceSourceCommitOid&&m.edge.artifactDigest===t.edgeArtifactDigest&&m.edge.sourceCommitOid===t.edgeSourceCommitOid&&t.deviceReleaseId===(unchanged?p.deviceReleaseId:t.releaseId)&&canonicalJson(m.protocol)===canonicalJson(t.protocol)&&canonicalJson(m.ledger)===canonicalJson(t.ledger),'INTEGRITY_FAILURE','Retained previous build does not name rollback pair');await this.o.artifacts.verify(t.releaseId,m,admitted.build.refs);this.o.edge.verifyVersion(await this.o.edge.version(t.edgeVersionId),t.edgeSourceCommitOid,t.edgeArtifactDigest,m.edge.compatibilityDate,releaseNamespace(m));}
  await this.o.configs.pointerFor(target);this.assert();requireThat(!this.journal.active()&&canonicalJson(await this.activePair())===canonicalJson(current),'STALE_RESULT');const latestRow=this.journal.db.prepare("SELECT record FROM activation WHERE active=0 ORDER BY rowid DESC LIMIT 1").get(),latest=latestRow?/** @type {Activation} */(parseRecord(String(latestRow.record),1048576)):null;requireThat(latest&&latest.intent.activationId===sourceActivationId&&latest.phase==='active','STALE_RELEASE','Rollback source is no longer the latest successful activation');
  const createdAt=this.now(),intent=activationIntent({...(namespace==='tdev'?{identityNamespace:/** @type {const} */('tdev')}:{ }),activationId:rollbackActivationId,actionId:rollbackActivationId,installationId:this.o.installationId,repositoryId:this.o.repositoryId,bindingEpoch:this.o.bindingEpoch,principalId:'fixed-helper:explicit-rollback',createdAt,deadline:createdAt+300000,previous:current,target,...(migration?{migration}:{})});return this.journal.begin(intent);
 }
 /** Does not wait for broker stop/restart. The fixed service tick, not the HTTP
  * request lifetime, drives durable active work and survives response loss.
  * @returns {Promise<void>} */
 tick(){if(this.running)return this.running;const run=(async()=>{this.assert();const current=this.journal.active();if(current)await this.o.controller.drive(current.intent.activationId);})().finally(()=>{this.running=null;});this.running=run;return run;}
 /** @param {string} activationId */
 observe(activationId){id(activationId);this.assert();return this.journal.read(activationId);}
 /** Startup admission intentionally does not query the restarting native process.
  * HMAC private transport plus actual pointer/journal/artifact identity, not mere
  * repository publication, establishes which staged device bytes may initialize.
  * @param {{deviceReleaseId:string,runtime:{sourceCommitOid:string,sourceTreeOid:string,bundleDigest:string,schemaDigest:string}}} request */
 async runtimeAdmission(request){digest(request.deviceReleaseId);this.assert();const pointer=await this.o.configs.current(),current=this.journal.active(),pairs=current?[current.intent.previous,current.intent.target]:[this.retainedPair()];
  const pair=pairs.find(p=>p.deviceReleaseId===request.deviceReleaseId&&p.deviceSourceCommitOid===request.runtime.sourceCommitOid&&p.deviceArtifactDigest===request.runtime.bundleDigest&&p.schemaDigest===request.runtime.schemaDigest);requireThat(pair&&pointer.deviceReleaseId===pair.deviceReleaseId&&canonicalJson(pointer)===canonicalJson(await this.o.configs.pointerFor(pair)),'FORBIDDEN','No current pointer/activation admission for device');
  const baseline=pair.deviceReleaseId===this.o.baseline.deviceReleaseId,admitted=baseline?null:/** @type {{build:Build,previous:Pair}|null} */(this.read('helper.build:'+pair.deviceReleaseId));
  if(!baseline){requireThat(admitted&&admitted.build.manifest.sourceTreeOid===request.runtime.sourceTreeOid&&admitted.build.manifest.device.artifactDigest===request.runtime.bundleDigest,'INTEGRITY_FAILURE');await this.o.artifacts.verify(pair.deviceReleaseId,admitted.build.manifest,admitted.build.refs);}
  else requireThat(this.o.configs.template?.runtime.sourceTreeOid===request.runtime.sourceTreeOid,'INTEGRITY_FAILURE');
  return {schemaVersion:1,kind:'tdev.installed-runtime-admission',installationId:this.o.installationId,repositoryId:this.o.repositoryId,bindingEpoch:this.o.bindingEpoch,installationSealDigest:this.o.installationSealDigest,executor:this.o.executor,deviceReleaseId:pair.deviceReleaseId,runtime:request.runtime,pair,manifest:admitted?.build.manifest??null,buildReceiptDigest:admitted?recordDigest(releaseNamespace(admitted.build.manifest)+'.helper-admitted-build-receipt.v1',admitted.build.receipt):null,activationId:current?.intent.activationId??null,baseline};
 }
}
